// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class AimCameraOpFixedSettings_tImpl : SchemaClass, AimCameraOpFixedSettings_t {

  public AimCameraOpFixedSettings_tImpl(nint handle) : base(handle) {
  }

  private static readonly nint _ChainIndexOffset = Schema.GetOffset(0xA3971F52A34589B6);

  public ref int ChainIndex {
    get => ref _Handle.AsRef<int>(_ChainIndexOffset);
  }
  private static readonly nint _CameraJointIndexOffset = Schema.GetOffset(0xA3971F52346981DA);

  public ref int CameraJointIndex {
    get => ref _Handle.AsRef<int>(_CameraJointIndexOffset);
  }
  private static readonly nint _PelvisJointIndexOffset = Schema.GetOffset(0xA3971F52800F5FB4);

  public ref int PelvisJointIndex {
    get => ref _Handle.AsRef<int>(_PelvisJointIndexOffset);
  }
  private static readonly nint _ClavicleLeftJointIndexOffset = Schema.GetOffset(0xA3971F5207F7ABDB);

  public ref int ClavicleLeftJointIndex {
    get => ref _Handle.AsRef<int>(_ClavicleLeftJointIndexOffset);
  }
  private static readonly nint _ClavicleRightJointIndexOffset = Schema.GetOffset(0xA3971F522F2C40A4);

  public ref int ClavicleRightJointIndex {
    get => ref _Handle.AsRef<int>(_ClavicleRightJointIndexOffset);
  }
  private static readonly nint _DepenetrationJointIndexOffset = Schema.GetOffset(0xA3971F526307286F);

  public ref int DepenetrationJointIndex {
    get => ref _Handle.AsRef<int>(_DepenetrationJointIndexOffset);
  }
  private static readonly nint _PropJointsOffset = Schema.GetOffset(0xA3971F5224880565);

  public ref CUtlVector<int> PropJoints {
    get => ref _Handle.AsRef<CUtlVector<int>>(_PropJointsOffset);
  }


}