// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class BlendItem_tImpl : SchemaClass, BlendItem_t {

  public BlendItem_tImpl(nint handle) : base(handle) {
  }

  private static readonly nint _TagsOffset = Schema.GetOffset(0x8FC3054B46C8540);

  public ref CUtlVector<TagSpan_t> Tags {
    get => ref _Handle.AsRef<CUtlVector<TagSpan_t>>(_TagsOffset);
  }
  private static readonly nint _ChildOffset = Schema.GetOffset(0x8FC30544A0B773F);

  public CAnimUpdateNodeRef Child {
    get => new CAnimUpdateNodeRefImpl(_Handle + _ChildOffset);
  }
  private static readonly nint _SequenceOffset = Schema.GetOffset(0x8FC3054E0A0598E);

  public HSequence Sequence {
    get => new HSequenceImpl(_Handle + _SequenceOffset);
  }
  private static readonly nint _PosOffset = Schema.GetOffset(0x8FC3054DE9CFC5D);

  public ref Vector2D Pos {
    get => ref _Handle.AsRef<Vector2D>(_PosOffset);
  }
  private static readonly nint _DurationOffset = Schema.GetOffset(0x8FC3054BC5E3BAB);

  public ref float Duration {
    get => ref _Handle.AsRef<float>(_DurationOffset);
  }
  private static readonly nint _UseCustomDurationOffset = Schema.GetOffset(0x8FC3054F9BF05AB);

  public ref bool UseCustomDuration {
    get => ref _Handle.AsRef<bool>(_UseCustomDurationOffset);
  }


}