// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class BoneDemoCaptureSettings_tImpl : SchemaClass, BoneDemoCaptureSettings_t {

  public BoneDemoCaptureSettings_tImpl(nint handle) : base(handle) {
  }

  private static readonly nint _BoneNameOffset = Schema.GetOffset(0x17A5730FDEE0E0C);

  public string BoneName {
    get {
      var ptr = _Handle.Read<nint>(_BoneNameOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _BoneNameOffset, value);
  } 
  private static readonly nint _ErrorSplineRotationMaxOffset = Schema.GetOffset(0x17A5730AB5B6CD2);

  public ref float ErrorSplineRotationMax {
    get => ref _Handle.AsRef<float>(_ErrorSplineRotationMaxOffset);
  }
  private static readonly nint _ErrorSplineTranslationMaxOffset = Schema.GetOffset(0x17A57306248F645);

  public ref float ErrorSplineTranslationMax {
    get => ref _Handle.AsRef<float>(_ErrorSplineTranslationMaxOffset);
  }
  private static readonly nint _ErrorSplineScaleMaxOffset = Schema.GetOffset(0x17A5730A30B95BA);

  public ref float ErrorSplineScaleMax {
    get => ref _Handle.AsRef<float>(_ErrorSplineScaleMaxOffset);
  }
  private static readonly nint _ErrorQuantizationRotationMaxOffset = Schema.GetOffset(0x17A57303509C8AA);

  public ref float ErrorQuantizationRotationMax {
    get => ref _Handle.AsRef<float>(_ErrorQuantizationRotationMaxOffset);
  }
  private static readonly nint _ErrorQuantizationTranslationMaxOffset = Schema.GetOffset(0x17A5730F1E2893D);

  public ref float ErrorQuantizationTranslationMax {
    get => ref _Handle.AsRef<float>(_ErrorQuantizationTranslationMaxOffset);
  }
  private static readonly nint _ErrorQuantizationScaleMaxOffset = Schema.GetOffset(0x17A57302ACF0072);

  public ref float ErrorQuantizationScaleMax {
    get => ref _Handle.AsRef<float>(_ErrorQuantizationScaleMaxOffset);
  }


}