// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_INIT_PositionPlaceOnGroundImpl : CParticleFunctionInitializerImpl, C_INIT_PositionPlaceOnGround {

  public C_INIT_PositionPlaceOnGroundImpl(nint handle) : base(handle) {
  }

  private static readonly nint _OffsetOffset = Schema.GetOffset(0xA022821E7F14BA34);

  public CPerParticleFloatInput Offset {
    get => new CPerParticleFloatInputImpl(_Handle + _OffsetOffset);
  }
  private static readonly nint _MaxTraceLengthOffset = Schema.GetOffset(0xA022821E543C3798);

  public CPerParticleFloatInput MaxTraceLength {
    get => new CPerParticleFloatInputImpl(_Handle + _MaxTraceLengthOffset);
  }
  private static readonly nint _CollisionGroupNameOffset = Schema.GetOffset(0xA022821ED58A3195);

  public string CollisionGroupName {
    get {
      var ptr = _Handle + _CollisionGroupNameOffset;
      return Schema.GetString(ptr);
    }
    set => Schema.SetFixedString(_Handle, _CollisionGroupNameOffset, value, 128);
  } 
  private static readonly nint _TraceSetOffset = Schema.GetOffset(0xA022821EBD26C5B2);

  public ref ParticleTraceSet_t TraceSet {
    get => ref _Handle.AsRef<ParticleTraceSet_t>(_TraceSetOffset);
  }
  private static readonly nint _TraceMissBehaviorOffset = Schema.GetOffset(0xA022821E1F2C7BCC);

  public ref ParticleTraceMissBehavior_t TraceMissBehavior {
    get => ref _Handle.AsRef<ParticleTraceMissBehavior_t>(_TraceMissBehaviorOffset);
  }
  private static readonly nint _IncludeWaterOffset = Schema.GetOffset(0xA022821EEB8D4646);

  public ref bool IncludeWater {
    get => ref _Handle.AsRef<bool>(_IncludeWaterOffset);
  }
  private static readonly nint _SetNormalOffset = Schema.GetOffset(0xA022821E542722AC);

  public ref bool SetNormal {
    get => ref _Handle.AsRef<bool>(_SetNormalOffset);
  }
  private static readonly nint _AttributeOffset = Schema.GetOffset(0xA022821E7FE8DE0B);

  public ParticleAttributeIndex_t Attribute {
    get => new ParticleAttributeIndex_tImpl(_Handle + _AttributeOffset);
  }
  private static readonly nint _SetPXYZOnlyOffset = Schema.GetOffset(0xA022821E93ED3336);

  public ref bool SetPXYZOnly {
    get => ref _Handle.AsRef<bool>(_SetPXYZOnlyOffset);
  }
  private static readonly nint _TraceAlongNormalOffset = Schema.GetOffset(0xA022821EF6E20144);

  public ref bool TraceAlongNormal {
    get => ref _Handle.AsRef<bool>(_TraceAlongNormalOffset);
  }
  private static readonly nint _TraceDirectionAttributeOffset = Schema.GetOffset(0xA022821E00E7482D);

  public ParticleAttributeIndex_t TraceDirectionAttribute {
    get => new ParticleAttributeIndex_tImpl(_Handle + _TraceDirectionAttributeOffset);
  }
  private static readonly nint _OffsetonColOnlyOffset = Schema.GetOffset(0xA022821E0720D19D);

  public ref bool OffsetonColOnly {
    get => ref _Handle.AsRef<bool>(_OffsetonColOnlyOffset);
  }
  private static readonly nint _OffsetByRadiusFactorOffset = Schema.GetOffset(0xA022821E61169F50);

  public ref float OffsetByRadiusFactor {
    get => ref _Handle.AsRef<float>(_OffsetByRadiusFactorOffset);
  }
  private static readonly nint _PreserveOffsetCPOffset = Schema.GetOffset(0xA022821E58AC51C1);

  public ref int PreserveOffsetCP {
    get => ref _Handle.AsRef<int>(_PreserveOffsetCPOffset);
  }
  private static readonly nint _IgnoreCPOffset = Schema.GetOffset(0xA022821EF0DDC7AC);

  public ref int IgnoreCP {
    get => ref _Handle.AsRef<int>(_IgnoreCPOffset);
  }


}