// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_INIT_RemapTransformOrientationToRotationsImpl : CParticleFunctionInitializerImpl, C_INIT_RemapTransformOrientationToRotations {

  public C_INIT_RemapTransformOrientationToRotationsImpl(nint handle) : base(handle) {
  }

  private static readonly nint _TransformInputOffset = Schema.GetOffset(0x51F07293B3FDC289);

  public CParticleTransformInput TransformInput {
    get => new CParticleTransformInputImpl(_Handle + _TransformInputOffset);
  }
  private static readonly nint _RotationOffset = Schema.GetOffset(0x51F072931992E6BF);

  public ref Vector Rotation {
    get => ref _Handle.AsRef<Vector>(_RotationOffset);
  }
  private static readonly nint _UseQuatOffset = Schema.GetOffset(0x51F0729343F0D4DB);

  public ref bool UseQuat {
    get => ref _Handle.AsRef<bool>(_UseQuatOffset);
  }
  private static readonly nint _WriteNormalOffset = Schema.GetOffset(0x51F07293C2EF44FF);

  public ref bool WriteNormal {
    get => ref _Handle.AsRef<bool>(_WriteNormalOffset);
  }


}