// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_INIT_InitialVelocityFromHitboxImpl : CParticleFunctionInitializerImpl, C_INIT_InitialVelocityFromHitbox {

  public C_INIT_InitialVelocityFromHitboxImpl(nint handle) : base(handle) {
  }

  private static readonly nint _VelocityMinOffset = Schema.GetOffset(0x48F25F17FDB3D7E4);

  public ref float VelocityMin {
    get => ref _Handle.AsRef<float>(_VelocityMinOffset);
  }
  private static readonly nint _VelocityMaxOffset = Schema.GetOffset(0x48F25F170BC775A6);

  public ref float VelocityMax {
    get => ref _Handle.AsRef<float>(_VelocityMaxOffset);
  }
  private static readonly nint _ControlPointNumberOffset = Schema.GetOffset(0x48F25F173F31A6BD);

  public ref int ControlPointNumber {
    get => ref _Handle.AsRef<int>(_ControlPointNumberOffset);
  }
  private static readonly nint _HitboxSetNameOffset = Schema.GetOffset(0x48F25F176A21BB0E);

  public string HitboxSetName {
    get {
      var ptr = _Handle + _HitboxSetNameOffset;
      return Schema.GetString(ptr);
    }
    set => Schema.SetFixedString(_Handle, _HitboxSetNameOffset, value, 128);
  } 
  private static readonly nint _UseBonesOffset = Schema.GetOffset(0x48F25F1710D1938B);

  public ref bool UseBones {
    get => ref _Handle.AsRef<bool>(_UseBonesOffset);
  }


}