// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_INIT_RemapInitialDirectionToTransformToVectorImpl : CParticleFunctionInitializerImpl, C_INIT_RemapInitialDirectionToTransformToVector {

  public C_INIT_RemapInitialDirectionToTransformToVectorImpl(nint handle) : base(handle) {
  }

  private static readonly nint _TransformInputOffset = Schema.GetOffset(0xB8FCDAFFB3FDC289);

  public CParticleTransformInput TransformInput {
    get => new CParticleTransformInputImpl(_Handle + _TransformInputOffset);
  }
  private static readonly nint _FieldOutputOffset = Schema.GetOffset(0xB8FCDAFFE5729606);

  public ParticleAttributeIndex_t FieldOutput {
    get => new ParticleAttributeIndex_tImpl(_Handle + _FieldOutputOffset);
  }
  private static readonly nint _ScaleOffset = Schema.GetOffset(0xB8FCDAFFB731A42F);

  public ref float Scale {
    get => ref _Handle.AsRef<float>(_ScaleOffset);
  }
  private static readonly nint _OffsetRotOffset = Schema.GetOffset(0xB8FCDAFFB414F849);

  public ref float OffsetRot {
    get => ref _Handle.AsRef<float>(_OffsetRotOffset);
  }
  private static readonly nint _OffsetAxisOffset = Schema.GetOffset(0xB8FCDAFFFAB4918F);

  public ref Vector OffsetAxis {
    get => ref _Handle.AsRef<Vector>(_OffsetAxisOffset);
  }
  private static readonly nint _NormalizeOffset = Schema.GetOffset(0xB8FCDAFF48BC424C);

  public ref bool Normalize {
    get => ref _Handle.AsRef<bool>(_NormalizeOffset);
  }


}