// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_INIT_CreateSpiralSphereImpl : CParticleFunctionInitializerImpl, C_INIT_CreateSpiralSphere {

  public C_INIT_CreateSpiralSphereImpl(nint handle) : base(handle) {
  }

  private static readonly nint _ControlPointNumberOffset = Schema.GetOffset(0x97C2018A3F31A6BD);

  public ref int ControlPointNumber {
    get => ref _Handle.AsRef<int>(_ControlPointNumberOffset);
  }
  private static readonly nint _OverrideCPOffset = Schema.GetOffset(0x97C2018ADD495162);

  public ref int OverrideCP {
    get => ref _Handle.AsRef<int>(_OverrideCPOffset);
  }
  private static readonly nint _DensityOffset = Schema.GetOffset(0x97C2018AA65E630F);

  public ref int Density {
    get => ref _Handle.AsRef<int>(_DensityOffset);
  }
  private static readonly nint _InitialRadiusOffset = Schema.GetOffset(0x97C2018A8B8AAB8B);

  public ref float InitialRadius {
    get => ref _Handle.AsRef<float>(_InitialRadiusOffset);
  }
  private static readonly nint _InitialSpeedMinOffset = Schema.GetOffset(0x97C2018AE36FD694);

  public ref float InitialSpeedMin {
    get => ref _Handle.AsRef<float>(_InitialSpeedMinOffset);
  }
  private static readonly nint _InitialSpeedMaxOffset = Schema.GetOffset(0x97C2018AD184D4F6);

  public ref float InitialSpeedMax {
    get => ref _Handle.AsRef<float>(_InitialSpeedMaxOffset);
  }
  private static readonly nint _UseParticleCountOffset = Schema.GetOffset(0x97C2018AD4DA0515);

  public ref bool UseParticleCount {
    get => ref _Handle.AsRef<bool>(_UseParticleCountOffset);
  }


}