// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_INIT_CreateParticleImpulseImpl : CParticleFunctionInitializerImpl, C_INIT_CreateParticleImpulse {

  public C_INIT_CreateParticleImpulseImpl(nint handle) : base(handle) {
  }

  private static readonly nint _InputRadiusOffset = Schema.GetOffset(0x1617EF931F5CA2F9);

  public CPerParticleFloatInput InputRadius {
    get => new CPerParticleFloatInputImpl(_Handle + _InputRadiusOffset);
  }
  private static readonly nint _InputMagnitudeOffset = Schema.GetOffset(0x1617EF938E8975B7);

  public CPerParticleFloatInput InputMagnitude {
    get => new CPerParticleFloatInputImpl(_Handle + _InputMagnitudeOffset);
  }
  private static readonly nint _FalloffFunctionOffset = Schema.GetOffset(0x1617EF93A7D5FD7D);

  public ref ParticleFalloffFunction_t FalloffFunction {
    get => ref _Handle.AsRef<ParticleFalloffFunction_t>(_FalloffFunctionOffset);
  }
  private static readonly nint _InputFalloffExpOffset = Schema.GetOffset(0x1617EF9356063396);

  public CPerParticleFloatInput InputFalloffExp {
    get => new CPerParticleFloatInputImpl(_Handle + _InputFalloffExpOffset);
  }
  private static readonly nint _ImpulseTypeOffset = Schema.GetOffset(0x1617EF9309B21020);

  public ref ParticleImpulseType_t ImpulseType {
    get => ref _Handle.AsRef<ParticleImpulseType_t>(_ImpulseTypeOffset);
  }


}