// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_INIT_RandomAlphaImpl : CParticleFunctionInitializerImpl, C_INIT_RandomAlpha {

  public C_INIT_RandomAlphaImpl(nint handle) : base(handle) {
  }

  private static readonly nint _FieldOutputOffset = Schema.GetOffset(0x3D7FD5BE5729606);

  public ParticleAttributeIndex_t FieldOutput {
    get => new ParticleAttributeIndex_tImpl(_Handle + _FieldOutputOffset);
  }
  private static readonly nint _AlphaMinOffset = Schema.GetOffset(0x3D7FD5BD7670531);

  public ref int AlphaMin {
    get => ref _Handle.AsRef<int>(_AlphaMinOffset);
  }
  private static readonly nint _AlphaMaxOffset = Schema.GetOffset(0x3D7FD5BE97AA93F);

  public ref int AlphaMax {
    get => ref _Handle.AsRef<int>(_AlphaMaxOffset);
  }
  private static readonly nint _AlphaRandExponentOffset = Schema.GetOffset(0x3D7FD5BA2C243B5);

  public ref float AlphaRandExponent {
    get => ref _Handle.AsRef<float>(_AlphaRandExponentOffset);
  }


}