// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_INIT_SetHitboxToClosestImpl : CParticleFunctionInitializerImpl, C_INIT_SetHitboxToClosest {

  public C_INIT_SetHitboxToClosestImpl(nint handle) : base(handle) {
  }

  private static readonly nint _ControlPointNumberOffset = Schema.GetOffset(0x10F3322C3F31A6BD);

  public ref int ControlPointNumber {
    get => ref _Handle.AsRef<int>(_ControlPointNumberOffset);
  }
  private static readonly nint _DesiredHitboxOffset = Schema.GetOffset(0x10F3322CFD09531B);

  public ref int DesiredHitbox {
    get => ref _Handle.AsRef<int>(_DesiredHitboxOffset);
  }
  private static readonly nint _HitBoxScaleOffset = Schema.GetOffset(0x10F3322C58EE3FB7);

  public CParticleCollectionVecInput HitBoxScale {
    get => new CParticleCollectionVecInputImpl(_Handle + _HitBoxScaleOffset);
  }
  private static readonly nint _HitboxSetNameOffset = Schema.GetOffset(0x10F3322C6A21BB0E);

  public string HitboxSetName {
    get {
      var ptr = _Handle + _HitboxSetNameOffset;
      return Schema.GetString(ptr);
    }
    set => Schema.SetFixedString(_Handle, _HitboxSetNameOffset, value, 128);
  } 
  private static readonly nint _UseBonesOffset = Schema.GetOffset(0x10F3322C10D1938B);

  public ref bool UseBones {
    get => ref _Handle.AsRef<bool>(_UseBonesOffset);
  }
  private static readonly nint _UseClosestPointOnHitboxOffset = Schema.GetOffset(0x10F3322CA983A934);

  public ref bool UseClosestPointOnHitbox {
    get => ref _Handle.AsRef<bool>(_UseClosestPointOnHitboxOffset);
  }
  private static readonly nint _TestTypeOffset = Schema.GetOffset(0x10F3322CEB021501);

  public ref ClosestPointTestType_t TestType {
    get => ref _Handle.AsRef<ClosestPointTestType_t>(_TestTypeOffset);
  }
  private static readonly nint _HybridRatioOffset = Schema.GetOffset(0x10F3322CC2A9455C);

  public CParticleCollectionFloatInput HybridRatio {
    get => new CParticleCollectionFloatInputImpl(_Handle + _HybridRatioOffset);
  }
  private static readonly nint _UpdatePositionOffset = Schema.GetOffset(0x10F3322C65B36E87);

  public ref bool UpdatePosition {
    get => ref _Handle.AsRef<bool>(_UpdatePositionOffset);
  }


}