// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_RenderScreenShakeImpl : CParticleFunctionRendererImpl, C_OP_RenderScreenShake {

  public C_OP_RenderScreenShakeImpl(nint handle) : base(handle) {
  }

  private static readonly nint _DurationScaleOffset = Schema.GetOffset(0x37508849776D4203);

  public ref float DurationScale {
    get => ref _Handle.AsRef<float>(_DurationScaleOffset);
  }
  private static readonly nint _RadiusScaleOffset = Schema.GetOffset(0x37508849A7A20159);

  public ref float RadiusScale {
    get => ref _Handle.AsRef<float>(_RadiusScaleOffset);
  }
  private static readonly nint _FrequencyScaleOffset = Schema.GetOffset(0x375088494B5C34F7);

  public ref float FrequencyScale {
    get => ref _Handle.AsRef<float>(_FrequencyScaleOffset);
  }
  private static readonly nint _AmplitudeScaleOffset = Schema.GetOffset(0x37508849BF90DF5A);

  public ref float AmplitudeScale {
    get => ref _Handle.AsRef<float>(_AmplitudeScaleOffset);
  }
  private static readonly nint _RadiusFieldOffset = Schema.GetOffset(0x375088494B15FC11);

  public ParticleAttributeIndex_t RadiusField {
    get => new ParticleAttributeIndex_tImpl(_Handle + _RadiusFieldOffset);
  }
  private static readonly nint _DurationFieldOffset = Schema.GetOffset(0x37508849B21EDAAB);

  public ParticleAttributeIndex_t DurationField {
    get => new ParticleAttributeIndex_tImpl(_Handle + _DurationFieldOffset);
  }
  private static readonly nint _FrequencyFieldOffset = Schema.GetOffset(0x37508849DDA055AF);

  public ParticleAttributeIndex_t FrequencyField {
    get => new ParticleAttributeIndex_tImpl(_Handle + _FrequencyFieldOffset);
  }
  private static readonly nint _AmplitudeFieldOffset = Schema.GetOffset(0x37508849F8F54FD2);

  public ParticleAttributeIndex_t AmplitudeField {
    get => new ParticleAttributeIndex_tImpl(_Handle + _AmplitudeFieldOffset);
  }
  private static readonly nint _FilterCPOffset = Schema.GetOffset(0x375088499304E130);

  public ref int FilterCP {
    get => ref _Handle.AsRef<int>(_FilterCPOffset);
  }


}