// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_RemapTransformVisibilityToScalarImpl : CParticleFunctionOperatorImpl, C_OP_RemapTransformVisibilityToScalar {

  public C_OP_RemapTransformVisibilityToScalarImpl(nint handle) : base(handle) {
  }

  private static readonly nint _SetMethodOffset = Schema.GetOffset(0x3CE3C8AFFB53C31E);

  public ref ParticleSetMethod_t SetMethod {
    get => ref _Handle.AsRef<ParticleSetMethod_t>(_SetMethodOffset);
  }
  private static readonly nint _TransformInputOffset = Schema.GetOffset(0x3CE3C8AFB3FDC289);

  public CParticleTransformInput TransformInput {
    get => new CParticleTransformInputImpl(_Handle + _TransformInputOffset);
  }
  private static readonly nint _FieldOutputOffset = Schema.GetOffset(0x3CE3C8AFE5729606);

  public ParticleAttributeIndex_t FieldOutput {
    get => new ParticleAttributeIndex_tImpl(_Handle + _FieldOutputOffset);
  }
  private static readonly nint _InputMinOffset = Schema.GetOffset(0x3CE3C8AFE88A0D0F);

  public ref float InputMin {
    get => ref _Handle.AsRef<float>(_InputMinOffset);
  }
  private static readonly nint _InputMaxOffset = Schema.GetOffset(0x3CE3C8AFD6766901);

  public ref float InputMax {
    get => ref _Handle.AsRef<float>(_InputMaxOffset);
  }
  private static readonly nint _OutputMinOffset = Schema.GetOffset(0x3CE3C8AF5F8D7716);

  public ref float OutputMin {
    get => ref _Handle.AsRef<float>(_OutputMinOffset);
  }
  private static readonly nint _OutputMaxOffset = Schema.GetOffset(0x3CE3C8AF51A0E8C4);

  public ref float OutputMax {
    get => ref _Handle.AsRef<float>(_OutputMaxOffset);
  }
  private static readonly nint _RadiusOffset = Schema.GetOffset(0x3CE3C8AF5ACFC08D);

  public ref float Radius {
    get => ref _Handle.AsRef<float>(_RadiusOffset);
  }


}