// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_RemapScalarOnceTimedImpl : CParticleFunctionOperatorImpl, C_OP_RemapScalarOnceTimed {

  public C_OP_RemapScalarOnceTimedImpl(nint handle) : base(handle) {
  }

  private static readonly nint _ProportionalOffset = Schema.GetOffset(0xF5150932891F328A);

  public ref bool Proportional {
    get => ref _Handle.AsRef<bool>(_ProportionalOffset);
  }
  private static readonly nint _FieldInputOffset = Schema.GetOffset(0xF5150932AE775669);

  public ParticleAttributeIndex_t FieldInput {
    get => new ParticleAttributeIndex_tImpl(_Handle + _FieldInputOffset);
  }
  private static readonly nint _FieldOutputOffset = Schema.GetOffset(0xF5150932E5729606);

  public ParticleAttributeIndex_t FieldOutput {
    get => new ParticleAttributeIndex_tImpl(_Handle + _FieldOutputOffset);
  }
  private static readonly nint _InputMinOffset = Schema.GetOffset(0xF5150932E88A0D0F);

  public ref float InputMin {
    get => ref _Handle.AsRef<float>(_InputMinOffset);
  }
  private static readonly nint _InputMaxOffset = Schema.GetOffset(0xF5150932D6766901);

  public ref float InputMax {
    get => ref _Handle.AsRef<float>(_InputMaxOffset);
  }
  private static readonly nint _OutputMinOffset = Schema.GetOffset(0xF51509325F8D7716);

  public ref float OutputMin {
    get => ref _Handle.AsRef<float>(_OutputMinOffset);
  }
  private static readonly nint _OutputMaxOffset = Schema.GetOffset(0xF515093251A0E8C4);

  public ref float OutputMax {
    get => ref _Handle.AsRef<float>(_OutputMaxOffset);
  }
  private static readonly nint _RemapTimeOffset = Schema.GetOffset(0xF5150932F436AC39);

  public ref float RemapTime {
    get => ref _Handle.AsRef<float>(_RemapTimeOffset);
  }


}