// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_VectorNoiseImpl : CParticleFunctionOperatorImpl, C_OP_VectorNoise {

  public C_OP_VectorNoiseImpl(nint handle) : base(handle) {
  }

  private static readonly nint _FieldOutputOffset = Schema.GetOffset(0xEAAF071CE5729606);

  public ParticleAttributeIndex_t FieldOutput {
    get => new ParticleAttributeIndex_tImpl(_Handle + _FieldOutputOffset);
  }
  private static readonly nint _OutputMinOffset = Schema.GetOffset(0xEAAF071C2EFED678);

  public ref Vector OutputMin {
    get => ref _Handle.AsRef<Vector>(_OutputMinOffset);
  }
  private static readonly nint _OutputMaxOffset = Schema.GetOffset(0xEAAF071C451280D2);

  public ref Vector OutputMax {
    get => ref _Handle.AsRef<Vector>(_OutputMaxOffset);
  }
  private static readonly nint _Fl4NoiseScaleOffset = Schema.GetOffset(0xEAAF071CF340DAD9);

  public ref float Fl4NoiseScale {
    get => ref _Handle.AsRef<float>(_Fl4NoiseScaleOffset);
  }
  private static readonly nint _AdditiveOffset = Schema.GetOffset(0xEAAF071C0FA86105);

  public ref bool Additive {
    get => ref _Handle.AsRef<bool>(_AdditiveOffset);
  }
  private static readonly nint _OffsetOffset = Schema.GetOffset(0xEAAF071C17412B2A);

  public ref bool Offset {
    get => ref _Handle.AsRef<bool>(_OffsetOffset);
  }
  private static readonly nint _NoiseAnimationTimeScaleOffset = Schema.GetOffset(0xEAAF071C504CBE30);

  public ref float NoiseAnimationTimeScale {
    get => ref _Handle.AsRef<float>(_NoiseAnimationTimeScaleOffset);
  }


}