// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_RepeatedTriggerChildGroupImpl : CParticleFunctionPreEmissionImpl, C_OP_RepeatedTriggerChildGroup {

  public C_OP_RepeatedTriggerChildGroupImpl(nint handle) : base(handle) {
  }

  private static readonly nint _ChildGroupIDOffset = Schema.GetOffset(0x3D9A0D4E3F3C965);

  public ref int ChildGroupID {
    get => ref _Handle.AsRef<int>(_ChildGroupIDOffset);
  }
  private static readonly nint _ClusterRefireTimeOffset = Schema.GetOffset(0x3D9A0D47E6BEEAB);

  public CParticleCollectionFloatInput ClusterRefireTime {
    get => new CParticleCollectionFloatInputImpl(_Handle + _ClusterRefireTimeOffset);
  }
  private static readonly nint _ClusterSizeOffset = Schema.GetOffset(0x3D9A0D4A7549FF6);

  public CParticleCollectionFloatInput ClusterSize {
    get => new CParticleCollectionFloatInputImpl(_Handle + _ClusterSizeOffset);
  }
  private static readonly nint _ClusterCooldownOffset = Schema.GetOffset(0x3D9A0D4753687EA);

  public CParticleCollectionFloatInput ClusterCooldown {
    get => new CParticleCollectionFloatInputImpl(_Handle + _ClusterCooldownOffset);
  }
  private static readonly nint _LimitChildCountOffset = Schema.GetOffset(0x3D9A0D4EA978249);

  public ref bool LimitChildCount {
    get => ref _Handle.AsRef<bool>(_LimitChildCountOffset);
  }


}