// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_RemapBoundingVolumetoCPImpl : CParticleFunctionPreEmissionImpl, C_OP_RemapBoundingVolumetoCP {

  public C_OP_RemapBoundingVolumetoCPImpl(nint handle) : base(handle) {
  }

  private static readonly nint _OutControlPointNumberOffset = Schema.GetOffset(0xBFFF451ED021D73F);

  public ref int OutControlPointNumber {
    get => ref _Handle.AsRef<int>(_OutControlPointNumberOffset);
  }
  private static readonly nint _InputMinOffset = Schema.GetOffset(0xBFFF451EE88A0D0F);

  public ref float InputMin {
    get => ref _Handle.AsRef<float>(_InputMinOffset);
  }
  private static readonly nint _InputMaxOffset = Schema.GetOffset(0xBFFF451ED6766901);

  public ref float InputMax {
    get => ref _Handle.AsRef<float>(_InputMaxOffset);
  }
  private static readonly nint _OutputMinOffset = Schema.GetOffset(0xBFFF451E5F8D7716);

  public ref float OutputMin {
    get => ref _Handle.AsRef<float>(_OutputMinOffset);
  }
  private static readonly nint _OutputMaxOffset = Schema.GetOffset(0xBFFF451E51A0E8C4);

  public ref float OutputMax {
    get => ref _Handle.AsRef<float>(_OutputMaxOffset);
  }


}