// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_FadeOutSimpleImpl : CParticleFunctionOperatorImpl, C_OP_FadeOutSimple {

  public C_OP_FadeOutSimpleImpl(nint handle) : base(handle) {
  }

  private static readonly nint _FadeOutTimeOffset = Schema.GetOffset(0xD439658FE86D2FC2);

  public ref float FadeOutTime {
    get => ref _Handle.AsRef<float>(_FadeOutTimeOffset);
  }
  private static readonly nint _FieldOutputOffset = Schema.GetOffset(0xD439658FE5729606);

  public ParticleAttributeIndex_t FieldOutput {
    get => new ParticleAttributeIndex_tImpl(_Handle + _FieldOutputOffset);
  }


}