// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_DistanceCullImpl : CParticleFunctionOperatorImpl, C_OP_DistanceCull {

  public C_OP_DistanceCullImpl(nint handle) : base(handle) {
  }

  private static readonly nint _ControlPointOffset = Schema.GetOffset(0x7252AA520D0DDF8C);

  public ref int ControlPoint {
    get => ref _Handle.AsRef<int>(_ControlPointOffset);
  }
  private static readonly nint _PointOffsetOffset = Schema.GetOffset(0x7252AA52300E046E);

  public ref Vector PointOffset {
    get => ref _Handle.AsRef<Vector>(_PointOffsetOffset);
  }
  private static readonly nint _DistanceOffset = Schema.GetOffset(0x7252AA5200DC4A68);

  public CParticleCollectionFloatInput Distance {
    get => new CParticleCollectionFloatInputImpl(_Handle + _DistanceOffset);
  }
  private static readonly nint _CullInsideOffset = Schema.GetOffset(0x7252AA52293E00AD);

  public ref bool CullInside {
    get => ref _Handle.AsRef<bool>(_CullInsideOffset);
  }
  private static readonly nint _AttributeOffset = Schema.GetOffset(0x7252AA527FE8DE0B);

  public ParticleAttributeIndex_t Attribute {
    get => new ParticleAttributeIndex_tImpl(_Handle + _AttributeOffset);
  }


}