// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_SetCPOrientationToGroundNormalImpl : CParticleFunctionOperatorImpl, C_OP_SetCPOrientationToGroundNormal {

  public C_OP_SetCPOrientationToGroundNormalImpl(nint handle) : base(handle) {
  }

  private static readonly nint _InterpRateOffset = Schema.GetOffset(0x7BC52DA3D3B705A7);

  public ref float InterpRate {
    get => ref _Handle.AsRef<float>(_InterpRateOffset);
  }
  private static readonly nint _MaxTraceLengthOffset = Schema.GetOffset(0x7BC52DA3543C3798);

  public ref float MaxTraceLength {
    get => ref _Handle.AsRef<float>(_MaxTraceLengthOffset);
  }
  private static readonly nint _ToleranceOffset = Schema.GetOffset(0x7BC52DA38C29728E);

  public ref float Tolerance {
    get => ref _Handle.AsRef<float>(_ToleranceOffset);
  }
  private static readonly nint _TraceOffsetOffset = Schema.GetOffset(0x7BC52DA37EF6C397);

  public ref float TraceOffset {
    get => ref _Handle.AsRef<float>(_TraceOffsetOffset);
  }
  private static readonly nint _CollisionGroupNameOffset = Schema.GetOffset(0x7BC52DA3D58A3195);

  public string CollisionGroupName {
    get {
      var ptr = _Handle + _CollisionGroupNameOffset;
      return Schema.GetString(ptr);
    }
    set => Schema.SetFixedString(_Handle, _CollisionGroupNameOffset, value, 128);
  } 
  private static readonly nint _TraceSetOffset = Schema.GetOffset(0x7BC52DA3BD26C5B2);

  public ref ParticleTraceSet_t TraceSet {
    get => ref _Handle.AsRef<ParticleTraceSet_t>(_TraceSetOffset);
  }
  private static readonly nint _InputCPOffset = Schema.GetOffset(0x7BC52DA3F39A3C14);

  public ref int InputCP {
    get => ref _Handle.AsRef<int>(_InputCPOffset);
  }
  private static readonly nint _OutputCPOffset = Schema.GetOffset(0x7BC52DA350DF5703);

  public ref int OutputCP {
    get => ref _Handle.AsRef<int>(_OutputCPOffset);
  }
  private static readonly nint _IncludeWaterOffset = Schema.GetOffset(0x7BC52DA3EB8D4646);

  public ref bool IncludeWater {
    get => ref _Handle.AsRef<bool>(_IncludeWaterOffset);
  }


}