// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_SetFloatCollectionImpl : CParticleFunctionOperatorImpl, C_OP_SetFloatCollection {

  public C_OP_SetFloatCollectionImpl(nint handle) : base(handle) {
  }

  private static readonly nint _InputValueOffset = Schema.GetOffset(0x72EFBE1734445438);

  public CParticleCollectionFloatInput InputValue {
    get => new CParticleCollectionFloatInputImpl(_Handle + _InputValueOffset);
  }
  private static readonly nint _OutputFieldOffset = Schema.GetOffset(0x72EFBE17324F6F74);

  public ParticleAttributeIndex_t OutputField {
    get => new ParticleAttributeIndex_tImpl(_Handle + _OutputFieldOffset);
  }
  private static readonly nint _SetMethodOffset = Schema.GetOffset(0x72EFBE17FB53C31E);

  public ref ParticleSetMethod_t SetMethod {
    get => ref _Handle.AsRef<ParticleSetMethod_t>(_SetMethodOffset);
  }
  private static readonly nint _LerpOffset = Schema.GetOffset(0x72EFBE175C17F8E8);

  public CParticleCollectionFloatInput Lerp {
    get => new CParticleCollectionFloatInputImpl(_Handle + _LerpOffset);
  }


}