// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_PlanarConstraintImpl : CParticleFunctionConstraintImpl, C_OP_PlanarConstraint {

  public C_OP_PlanarConstraintImpl(nint handle) : base(handle) {
  }

  private static readonly nint _PointOnPlaneOffset = Schema.GetOffset(0x1440B2AE4A5806BE);

  public ref Vector PointOnPlane {
    get => ref _Handle.AsRef<Vector>(_PointOnPlaneOffset);
  }
  private static readonly nint _PlaneNormalOffset = Schema.GetOffset(0x1440B2AEEAA80062);

  public ref Vector PlaneNormal {
    get => ref _Handle.AsRef<Vector>(_PlaneNormalOffset);
  }
  private static readonly nint _ControlPointNumberOffset = Schema.GetOffset(0x1440B2AE3F31A6BD);

  public ref int ControlPointNumber {
    get => ref _Handle.AsRef<int>(_ControlPointNumberOffset);
  }
  private static readonly nint _GlobalOriginOffset = Schema.GetOffset(0x1440B2AEDF871518);

  public ref bool GlobalOrigin {
    get => ref _Handle.AsRef<bool>(_GlobalOriginOffset);
  }
  private static readonly nint _GlobalNormalOffset = Schema.GetOffset(0x1440B2AE266C15DD);

  public ref bool GlobalNormal {
    get => ref _Handle.AsRef<bool>(_GlobalNormalOffset);
  }
  private static readonly nint _RadiusScaleOffset = Schema.GetOffset(0x1440B2AEA7A20159);

  public CPerParticleFloatInput RadiusScale {
    get => new CPerParticleFloatInputImpl(_Handle + _RadiusScaleOffset);
  }
  private static readonly nint _MaximumDistanceToCPOffset = Schema.GetOffset(0x1440B2AE91B48FEA);

  public CParticleCollectionFloatInput MaximumDistanceToCP {
    get => new CParticleCollectionFloatInputImpl(_Handle + _MaximumDistanceToCPOffset);
  }
  private static readonly nint _UseOldCodeOffset = Schema.GetOffset(0x1440B2AEB7886300);

  public ref bool UseOldCode {
    get => ref _Handle.AsRef<bool>(_UseOldCodeOffset);
  }


}