// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_SetAttributeToScalarExpressionImpl : CParticleFunctionOperatorImpl, C_OP_SetAttributeToScalarExpression {

  public C_OP_SetAttributeToScalarExpressionImpl(nint handle) : base(handle) {
  }

  private static readonly nint _ExpressionOffset = Schema.GetOffset(0x3D6339D6160B2427);

  public ref ScalarExpressionType_t Expression {
    get => ref _Handle.AsRef<ScalarExpressionType_t>(_ExpressionOffset);
  }
  private static readonly nint _Input1Offset = Schema.GetOffset(0x3D6339D6E9DA2E24);

  public CPerParticleFloatInput Input1 {
    get => new CPerParticleFloatInputImpl(_Handle + _Input1Offset);
  }
  private static readonly nint _Input2Offset = Schema.GetOffset(0x3D6339D6ECDA32DD);

  public CPerParticleFloatInput Input2 {
    get => new CPerParticleFloatInputImpl(_Handle + _Input2Offset);
  }
  private static readonly nint _OutputRemapOffset = Schema.GetOffset(0x3D6339D61239396F);

  public CParticleRemapFloatInput OutputRemap {
    get => new CParticleRemapFloatInputImpl(_Handle + _OutputRemapOffset);
  }
  private static readonly nint _OutputFieldOffset = Schema.GetOffset(0x3D6339D6324F6F74);

  public ParticleAttributeIndex_t OutputField {
    get => new ParticleAttributeIndex_tImpl(_Handle + _OutputFieldOffset);
  }
  private static readonly nint _SetMethodOffset = Schema.GetOffset(0x3D6339D6FB53C31E);

  public ref ParticleSetMethod_t SetMethod {
    get => ref _Handle.AsRef<ParticleSetMethod_t>(_SetMethodOffset);
  }


}