// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_RemapControlPointDirectionToVectorImpl : CParticleFunctionOperatorImpl, C_OP_RemapControlPointDirectionToVector {

  public C_OP_RemapControlPointDirectionToVectorImpl(nint handle) : base(handle) {
  }

  private static readonly nint _FieldOutputOffset = Schema.GetOffset(0xB5467A62E5729606);

  public ParticleAttributeIndex_t FieldOutput {
    get => new ParticleAttributeIndex_tImpl(_Handle + _FieldOutputOffset);
  }
  private static readonly nint _ScaleOffset = Schema.GetOffset(0xB5467A62B731A42F);

  public ref float Scale {
    get => ref _Handle.AsRef<float>(_ScaleOffset);
  }
  private static readonly nint _ControlPointNumberOffset = Schema.GetOffset(0xB5467A623F31A6BD);

  public ref int ControlPointNumber {
    get => ref _Handle.AsRef<int>(_ControlPointNumberOffset);
  }


}