// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_RemapCPVelocityToVectorImpl : CParticleFunctionOperatorImpl, C_OP_RemapCPVelocityToVector {

  public C_OP_RemapCPVelocityToVectorImpl(nint handle) : base(handle) {
  }

  private static readonly nint _ControlPointOffset = Schema.GetOffset(0xAD6CE1DC0D0DDF8C);

  public ref int ControlPoint {
    get => ref _Handle.AsRef<int>(_ControlPointOffset);
  }
  private static readonly nint _FieldOutputOffset = Schema.GetOffset(0xAD6CE1DCE5729606);

  public ParticleAttributeIndex_t FieldOutput {
    get => new ParticleAttributeIndex_tImpl(_Handle + _FieldOutputOffset);
  }
  private static readonly nint _ScaleOffset = Schema.GetOffset(0xAD6CE1DCB731A42F);

  public ref float Scale {
    get => ref _Handle.AsRef<float>(_ScaleOffset);
  }
  private static readonly nint _NormalizeOffset = Schema.GetOffset(0xAD6CE1DC48BC424C);

  public ref bool Normalize {
    get => ref _Handle.AsRef<bool>(_NormalizeOffset);
  }


}