// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_ConnectParentParticleToNearestImpl : CParticleFunctionOperatorImpl, C_OP_ConnectParentParticleToNearest {

  public C_OP_ConnectParentParticleToNearestImpl(nint handle) : base(handle) {
  }

  private static readonly nint _FirstControlPointOffset = Schema.GetOffset(0x9C608BD072117650);

  public ref int FirstControlPoint {
    get => ref _Handle.AsRef<int>(_FirstControlPointOffset);
  }
  private static readonly nint _SecondControlPointOffset = Schema.GetOffset(0x9C608BD04D8D2B44);

  public ref int SecondControlPoint {
    get => ref _Handle.AsRef<int>(_SecondControlPointOffset);
  }
  private static readonly nint _UseRadiusOffset = Schema.GetOffset(0x9C608BD0B7D98E6A);

  public ref bool UseRadius {
    get => ref _Handle.AsRef<bool>(_UseRadiusOffset);
  }
  private static readonly nint _RadiusScaleOffset = Schema.GetOffset(0x9C608BD0A7A20159);

  public CParticleCollectionFloatInput RadiusScale {
    get => new CParticleCollectionFloatInputImpl(_Handle + _RadiusScaleOffset);
  }
  private static readonly nint _ParentRadiusScaleOffset = Schema.GetOffset(0x9C608BD0CD77EF69);

  public CParticleCollectionFloatInput ParentRadiusScale {
    get => new CParticleCollectionFloatInputImpl(_Handle + _ParentRadiusScaleOffset);
  }


}