// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_DirectionBetweenVecsToVecImpl : CParticleFunctionOperatorImpl, C_OP_DirectionBetweenVecsToVec {

  public C_OP_DirectionBetweenVecsToVecImpl(nint handle) : base(handle) {
  }

  private static readonly nint _FieldOutputOffset = Schema.GetOffset(0x6022BA82E5729606);

  public ParticleAttributeIndex_t FieldOutput {
    get => new ParticleAttributeIndex_tImpl(_Handle + _FieldOutputOffset);
  }
  private static readonly nint _Point1Offset = Schema.GetOffset(0x6022BA8204AD2BC0);

  public CPerParticleVecInput Point1 {
    get => new CPerParticleVecInputImpl(_Handle + _Point1Offset);
  }
  private static readonly nint _Point2Offset = Schema.GetOffset(0x6022BA8207AD3079);

  public CPerParticleVecInput Point2 {
    get => new CPerParticleVecInputImpl(_Handle + _Point2Offset);
  }


}