// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_ConstrainDistanceToPathImpl : CParticleFunctionConstraintImpl, C_OP_ConstrainDistanceToPath {

  public C_OP_ConstrainDistanceToPathImpl(nint handle) : base(handle) {
  }

  private static readonly nint _MinDistanceOffset = Schema.GetOffset(0x8146F787F016B7AC);

  public ref float MinDistance {
    get => ref _Handle.AsRef<float>(_MinDistanceOffset);
  }
  private static readonly nint _MaxDistance0Offset = Schema.GetOffset(0x8146F7876FFBC6F0);

  public ref float MaxDistance0 {
    get => ref _Handle.AsRef<float>(_MaxDistance0Offset);
  }
  private static readonly nint _MaxDistanceMidOffset = Schema.GetOffset(0x8146F7872D2B1E5A);

  public ref float MaxDistanceMid {
    get => ref _Handle.AsRef<float>(_MaxDistanceMidOffset);
  }
  private static readonly nint _MaxDistance1Offset = Schema.GetOffset(0x8146F78770FBC883);

  public ref float MaxDistance1 {
    get => ref _Handle.AsRef<float>(_MaxDistance1Offset);
  }
  private static readonly nint _PathParametersOffset = Schema.GetOffset(0x8146F7878C111646);

  public CPathParameters PathParameters {
    get => new CPathParametersImpl(_Handle + _PathParametersOffset);
  }
  private static readonly nint _TravelTimeOffset = Schema.GetOffset(0x8146F7870228B67A);

  public ref float TravelTime {
    get => ref _Handle.AsRef<float>(_TravelTimeOffset);
  }
  private static readonly nint _FieldScaleOffset = Schema.GetOffset(0x8146F787BE94CE93);

  public ParticleAttributeIndex_t FieldScale {
    get => new ParticleAttributeIndex_tImpl(_Handle + _FieldScaleOffset);
  }
  private static readonly nint _ManualTFieldOffset = Schema.GetOffset(0x8146F7871190C51B);

  public ParticleAttributeIndex_t ManualTField {
    get => new ParticleAttributeIndex_tImpl(_Handle + _ManualTFieldOffset);
  }


}