// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_TimeVaryingForceImpl : CParticleFunctionForceImpl, C_OP_TimeVaryingForce {

  public C_OP_TimeVaryingForceImpl(nint handle) : base(handle) {
  }

  private static readonly nint _StartLerpTimeOffset = Schema.GetOffset(0xAC89FC47C1D0DC21);

  public ref float StartLerpTime {
    get => ref _Handle.AsRef<float>(_StartLerpTimeOffset);
  }
  private static readonly nint _StartingForceOffset = Schema.GetOffset(0xAC89FC478FA47818);

  public ref Vector StartingForce {
    get => ref _Handle.AsRef<Vector>(_StartingForceOffset);
  }
  private static readonly nint _EndLerpTimeOffset = Schema.GetOffset(0xAC89FC47AA182894);

  public ref float EndLerpTime {
    get => ref _Handle.AsRef<float>(_EndLerpTimeOffset);
  }
  private static readonly nint _EndingForceOffset = Schema.GetOffset(0xAC89FC47CEB5307D);

  public ref Vector EndingForce {
    get => ref _Handle.AsRef<Vector>(_EndingForceOffset);
  }


}