// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_LerpToOtherAttributeImpl : CParticleFunctionOperatorImpl, C_OP_LerpToOtherAttribute {

  public C_OP_LerpToOtherAttributeImpl(nint handle) : base(handle) {
  }

  private static readonly nint _InterpolationOffset = Schema.GetOffset(0x1F92A80BCF55B987);

  public CPerParticleFloatInput Interpolation {
    get => new CPerParticleFloatInputImpl(_Handle + _InterpolationOffset);
  }
  private static readonly nint _FieldInputFromOffset = Schema.GetOffset(0x1F92A80BB0E75581);

  public ParticleAttributeIndex_t FieldInputFrom {
    get => new ParticleAttributeIndex_tImpl(_Handle + _FieldInputFromOffset);
  }
  private static readonly nint _FieldInputOffset = Schema.GetOffset(0x1F92A80BAE775669);

  public ParticleAttributeIndex_t FieldInput {
    get => new ParticleAttributeIndex_tImpl(_Handle + _FieldInputOffset);
  }
  private static readonly nint _FieldOutputOffset = Schema.GetOffset(0x1F92A80BE5729606);

  public ParticleAttributeIndex_t FieldOutput {
    get => new ParticleAttributeIndex_tImpl(_Handle + _FieldOutputOffset);
  }


}