// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_SpringToVectorConstraintImpl : CParticleFunctionConstraintImpl, C_OP_SpringToVectorConstraint {

  public C_OP_SpringToVectorConstraintImpl(nint handle) : base(handle) {
  }

  private static readonly nint _RestLengthOffset = Schema.GetOffset(0xF442244193AC4079);

  public CPerParticleFloatInput RestLength {
    get => new CPerParticleFloatInputImpl(_Handle + _RestLengthOffset);
  }
  private static readonly nint _MinDistanceOffset = Schema.GetOffset(0xF442244192BCAD06);

  public CPerParticleFloatInput MinDistance {
    get => new CPerParticleFloatInputImpl(_Handle + _MinDistanceOffset);
  }
  private static readonly nint _MaxDistanceOffset = Schema.GetOffset(0xF442244198893360);

  public CPerParticleFloatInput MaxDistance {
    get => new CPerParticleFloatInputImpl(_Handle + _MaxDistanceOffset);
  }
  private static readonly nint _RestingLengthOffset = Schema.GetOffset(0xF4422441BB988EAF);

  public CPerParticleFloatInput RestingLength {
    get => new CPerParticleFloatInputImpl(_Handle + _RestingLengthOffset);
  }
  private static readonly nint _AnchorVectorOffset = Schema.GetOffset(0xF442244180D613F3);

  public CPerParticleVecInput AnchorVector {
    get => new CPerParticleVecInputImpl(_Handle + _AnchorVectorOffset);
  }


}