// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_ColorInterpolateRandomImpl : CParticleFunctionOperatorImpl, C_OP_ColorInterpolateRandom {

  public C_OP_ColorInterpolateRandomImpl(nint handle) : base(handle) {
  }

  private static readonly nint _ColorFadeMinOffset = Schema.GetOffset(0x6185EEC8EFCBE55A);

  public ref Color ColorFadeMin {
    get => ref _Handle.AsRef<Color>(_ColorFadeMinOffset);
  }
  private static readonly nint _ColorFadeMaxOffset = Schema.GetOffset(0x6185EEC8D9DF4A70);

  public ref Color ColorFadeMax {
    get => ref _Handle.AsRef<Color>(_ColorFadeMaxOffset);
  }
  private static readonly nint _FadeStartTimeOffset = Schema.GetOffset(0x6185EEC886B28BFA);

  public ref float FadeStartTime {
    get => ref _Handle.AsRef<float>(_FadeStartTimeOffset);
  }
  private static readonly nint _FadeEndTimeOffset = Schema.GetOffset(0x6185EEC800D5CA4F);

  public ref float FadeEndTime {
    get => ref _Handle.AsRef<float>(_FadeEndTimeOffset);
  }
  private static readonly nint _FieldOutputOffset = Schema.GetOffset(0x6185EEC8E5729606);

  public ParticleAttributeIndex_t FieldOutput {
    get => new ParticleAttributeIndex_tImpl(_Handle + _FieldOutputOffset);
  }
  private static readonly nint _EaseInOutOffset = Schema.GetOffset(0x6185EEC85172CF48);

  public ref bool EaseInOut {
    get => ref _Handle.AsRef<bool>(_EaseInOutOffset);
  }


}