// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_ScreenSpaceRotateTowardTargetImpl : CParticleFunctionOperatorImpl, C_OP_ScreenSpaceRotateTowardTarget {

  public C_OP_ScreenSpaceRotateTowardTargetImpl(nint handle) : base(handle) {
  }

  private static readonly nint _TargetPositionOffset = Schema.GetOffset(0xD66164FC554C563B);

  public CPerParticleVecInput TargetPosition {
    get => new CPerParticleVecInputImpl(_Handle + _TargetPositionOffset);
  }
  private static readonly nint _OutputRemapOffset = Schema.GetOffset(0xD66164FC1239396F);

  public CParticleRemapFloatInput OutputRemap {
    get => new CParticleRemapFloatInputImpl(_Handle + _OutputRemapOffset);
  }
  private static readonly nint _SetMethodOffset = Schema.GetOffset(0xD66164FCFB53C31E);

  public ref ParticleSetMethod_t SetMethod {
    get => ref _Handle.AsRef<ParticleSetMethod_t>(_SetMethodOffset);
  }
  private static readonly nint _ScreenEdgeAlignmentDistanceOffset = Schema.GetOffset(0xD66164FCDB3D3EAC);

  public CPerParticleFloatInput ScreenEdgeAlignmentDistance {
    get => new CPerParticleFloatInputImpl(_Handle + _ScreenEdgeAlignmentDistanceOffset);
  }


}