// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CAimCameraUpdateNodeImpl : CUnaryUpdateNodeImpl, CAimCameraUpdateNode {

  public CAimCameraUpdateNodeImpl(nint handle) : base(handle) {
  }

  private static readonly nint _ParameterPositionOffset = Schema.GetOffset(0xE8DD6D01DA71CD41);

  public CAnimParamHandle ParameterPosition {
    get => new CAnimParamHandleImpl(_Handle + _ParameterPositionOffset);
  }
  private static readonly nint _ParameterOrientationOffset = Schema.GetOffset(0xE8DD6D011320E9C8);

  public CAnimParamHandle ParameterOrientation {
    get => new CAnimParamHandleImpl(_Handle + _ParameterOrientationOffset);
  }
  private static readonly nint _ParameterSpineRotationWeightOffset = Schema.GetOffset(0xE8DD6D013A4DC0C7);

  public CAnimParamHandle ParameterSpineRotationWeight {
    get => new CAnimParamHandleImpl(_Handle + _ParameterSpineRotationWeightOffset);
  }
  private static readonly nint _ParameterPelvisOffsetOffset = Schema.GetOffset(0xE8DD6D01C4C67FA8);

  public CAnimParamHandle ParameterPelvisOffset {
    get => new CAnimParamHandleImpl(_Handle + _ParameterPelvisOffsetOffset);
  }
  private static readonly nint _ParameterUseIKOffset = Schema.GetOffset(0xE8DD6D01C8F88C49);

  public CAnimParamHandle ParameterUseIK {
    get => new CAnimParamHandleImpl(_Handle + _ParameterUseIKOffset);
  }
  private static readonly nint _ParameterCameraOnlyOffset = Schema.GetOffset(0xE8DD6D013A129627);

  public CAnimParamHandle ParameterCameraOnly {
    get => new CAnimParamHandleImpl(_Handle + _ParameterCameraOnlyOffset);
  }
  private static readonly nint _ParameterWeaponDepenetrationDistanceOffset = Schema.GetOffset(0xE8DD6D01316BB0BD);

  public CAnimParamHandle ParameterWeaponDepenetrationDistance {
    get => new CAnimParamHandleImpl(_Handle + _ParameterWeaponDepenetrationDistanceOffset);
  }
  private static readonly nint _ParameterWeaponDepenetrationDeltaOffset = Schema.GetOffset(0xE8DD6D01D6C8CDF0);

  public CAnimParamHandle ParameterWeaponDepenetrationDelta {
    get => new CAnimParamHandleImpl(_Handle + _ParameterWeaponDepenetrationDeltaOffset);
  }
  private static readonly nint _ParameterCameraClearanceDistanceOffset = Schema.GetOffset(0xE8DD6D01F4F2C992);

  public CAnimParamHandle ParameterCameraClearanceDistance {
    get => new CAnimParamHandleImpl(_Handle + _ParameterCameraClearanceDistanceOffset);
  }
  private static readonly nint _OpFixedSettingsOffset = Schema.GetOffset(0xE8DD6D01E533AB09);

  public AimCameraOpFixedSettings_t OpFixedSettings {
    get => new AimCameraOpFixedSettings_tImpl(_Handle + _OpFixedSettingsOffset);
  }


}