// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CAimMatrixUpdateNodeImpl : CUnaryUpdateNodeImpl, CAimMatrixUpdateNode {

  public CAimMatrixUpdateNodeImpl(nint handle) : base(handle) {
  }

  private static readonly nint _OpFixedSettingsOffset = Schema.GetOffset(0xB3687A53E533AB09);

  public AimMatrixOpFixedSettings_t OpFixedSettings {
    get => new AimMatrixOpFixedSettings_tImpl(_Handle + _OpFixedSettingsOffset);
  }
  private static readonly nint _TargetOffset = Schema.GetOffset(0xB3687A53FA08A9E8);

  public ref AnimVectorSource Target {
    get => ref _Handle.AsRef<AnimVectorSource>(_TargetOffset);
  }
  private static readonly nint _ParamIndexOffset = Schema.GetOffset(0xB3687A5361990A86);

  public CAnimParamHandle ParamIndex {
    get => new CAnimParamHandleImpl(_Handle + _ParamIndexOffset);
  }
  private static readonly nint _SequenceOffset = Schema.GetOffset(0xB3687A53E0A0598E);

  public HSequence Sequence {
    get => new HSequenceImpl(_Handle + _SequenceOffset);
  }
  private static readonly nint _ResetChildOffset = Schema.GetOffset(0xB3687A5365CC88B6);

  public ref bool ResetChild {
    get => ref _Handle.AsRef<bool>(_ResetChildOffset);
  }
  private static readonly nint _LockWhenWaningOffset = Schema.GetOffset(0xB3687A53EED48004);

  public ref bool LockWhenWaning {
    get => ref _Handle.AsRef<bool>(_LockWhenWaningOffset);
  }


}