// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CAnimComponentUpdaterImpl : SchemaClass, CAnimComponentUpdater {

  public CAnimComponentUpdaterImpl(nint handle) : base(handle) {
  }

  private static readonly nint _NameOffset = Schema.GetOffset(0x3E0F51C74D8F5786);

  public string Name {
    get {
      var ptr = _Handle.Read<nint>(_NameOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _NameOffset, value);
  } 
  private static readonly nint _IdOffset = Schema.GetOffset(0x3E0F51C7B4B6E980);

  public AnimComponentID Id {
    get => new AnimComponentIDImpl(_Handle + _IdOffset);
  }
  private static readonly nint _NetworkModeOffset = Schema.GetOffset(0x3E0F51C7E3307112);

  public ref AnimNodeNetworkMode NetworkMode {
    get => ref _Handle.AsRef<AnimNodeNetworkMode>(_NetworkModeOffset);
  }
  private static readonly nint _StartEnabledOffset = Schema.GetOffset(0x3E0F51C7500D5C24);

  public ref bool StartEnabled {
    get => ref _Handle.AsRef<bool>(_StartEnabledOffset);
  }


}