// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CAnimFootImpl : SchemaClass, CAnimFoot {

  public CAnimFootImpl(nint handle) : base(handle) {
  }

  private static readonly nint _NameOffset = Schema.GetOffset(0x583A05E34D8F5786);

  public string Name {
    get {
      var ptr = _Handle.Read<nint>(_NameOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _NameOffset, value);
  } 
  private static readonly nint _BallOffsetOffset = Schema.GetOffset(0x583A05E3E3376F1B);

  public ref Vector BallOffset {
    get => ref _Handle.AsRef<Vector>(_BallOffsetOffset);
  }
  private static readonly nint _HeelOffsetOffset = Schema.GetOffset(0x583A05E3306AE608);

  public ref Vector HeelOffset {
    get => ref _Handle.AsRef<Vector>(_HeelOffsetOffset);
  }
  private static readonly nint _AnkleBoneIndexOffset = Schema.GetOffset(0x583A05E31E89F146);

  public ref int AnkleBoneIndex {
    get => ref _Handle.AsRef<int>(_AnkleBoneIndexOffset);
  }
  private static readonly nint _ToeBoneIndexOffset = Schema.GetOffset(0x583A05E3EEF7CC57);

  public ref int ToeBoneIndex {
    get => ref _Handle.AsRef<int>(_ToeBoneIndexOffset);
  }


}