// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CAnimMotorUpdaterBaseImpl : SchemaClass, CAnimMotorUpdaterBase {

  public CAnimMotorUpdaterBaseImpl(nint handle) : base(handle) {
  }

  private static readonly nint _NameOffset = Schema.GetOffset(0x3FB6E1144D8F5786);

  public string Name {
    get {
      var ptr = _Handle.Read<nint>(_NameOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _NameOffset, value);
  } 
  private static readonly nint _DefaultOffset = Schema.GetOffset(0x3FB6E11485F067BE);

  public ref bool Default {
    get => ref _Handle.AsRef<bool>(_DefaultOffset);
  }


}