// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CAnimUpdateSharedDataImpl : SchemaClass, CAnimUpdateSharedData {

  public CAnimUpdateSharedDataImpl(nint handle) : base(handle) {
  }

  private static readonly nint _NodesOffset = Schema.GetOffset(0xA294DB47780F027A);

  public ref CUtlVector<SchemaUntypedField> Nodes {
    get => ref _Handle.AsRef<CUtlVector<SchemaUntypedField>>(_NodesOffset);
  }
  private static readonly nint _NodeIndexMapOffset = Schema.GetOffset(0xA294DB47D3B3E7A3);

  public SchemaUntypedField NodeIndexMap {
    get => new SchemaUntypedField(_Handle + _NodeIndexMapOffset);
  }
  private static readonly nint _ComponentsOffset = Schema.GetOffset(0xA294DB47F87FC409);

  public ref CUtlVector<SchemaUntypedField> Components {
    get => ref _Handle.AsRef<CUtlVector<SchemaUntypedField>>(_ComponentsOffset);
  }
  private static readonly nint _ParamListUpdaterOffset = Schema.GetOffset(0xA294DB4784AA7F15);

  public SchemaUntypedField ParamListUpdater {
    get => new SchemaUntypedField(_Handle + _ParamListUpdaterOffset);
  }
  private static readonly nint _TagManagerUpdaterOffset = Schema.GetOffset(0xA294DB47432E460D);

  public SchemaUntypedField TagManagerUpdater {
    get => new SchemaUntypedField(_Handle + _TagManagerUpdaterOffset);
  }
  private static readonly nint _ScriptManagerOffset = Schema.GetOffset(0xA294DB47F4257D31);

  public SchemaUntypedField ScriptManager {
    get => new SchemaUntypedField(_Handle + _ScriptManagerOffset);
  }
  private static readonly nint _SettingsOffset = Schema.GetOffset(0xA294DB47B3DE33A8);

  public CAnimGraphSettingsManager Settings {
    get => new CAnimGraphSettingsManagerImpl(_Handle + _SettingsOffset);
  }
  private static readonly nint _StaticPoseCacheOffset = Schema.GetOffset(0xA294DB475BFC0C1E);

  public SchemaUntypedField StaticPoseCache {
    get => new SchemaUntypedField(_Handle + _StaticPoseCacheOffset);
  }
  private static readonly nint _SkeletonOffset = Schema.GetOffset(0xA294DB4744BBF688);

  public SchemaUntypedField Skeleton {
    get => new SchemaUntypedField(_Handle + _SkeletonOffset);
  }
  private static readonly nint _RootNodePathOffset = Schema.GetOffset(0xA294DB476893B9EE);

  public CAnimNodePath RootNodePath {
    get => new CAnimNodePathImpl(_Handle + _RootNodePathOffset);
  }


}