// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CAttributeManager__cached_attribute_float_tImpl : SchemaClass, CAttributeManager__cached_attribute_float_t {

  public CAttributeManager__cached_attribute_float_tImpl(nint handle) : base(handle) {
  }

  private static readonly nint _InOffset = Schema.GetOffset(0xE3C5A1BAD526F734);

  public ref float In {
    get => ref _Handle.AsRef<float>(_InOffset);
  }
  private static readonly nint _AttribHookOffset = Schema.GetOffset(0xE3C5A1BACD388D67);

  public string AttribHook {
    get {
      var ptr = _Handle.Read<nint>(_AttribHookOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _AttribHookOffset, value);
  } 
  private static readonly nint _OutOffset = Schema.GetOffset(0xE3C5A1BA546B7BE1);

  public ref float Out {
    get => ref _Handle.AsRef<float>(_OutOffset);
  }


}