// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CBaseAnimGraphImpl : CBaseModelEntityImpl, CBaseAnimGraph {

  public CBaseAnimGraphImpl(nint handle) : base(handle) {
  }

  private static readonly nint _InitiallyPopulateInterpHistoryOffset = Schema.GetOffset(0xE501DB1E3087361C);

  public ref bool InitiallyPopulateInterpHistory {
    get => ref _Handle.AsRef<bool>(_InitiallyPopulateInterpHistoryOffset);
  }
  private static readonly nint _ChoreoServicesOffset = Schema.GetOffset(0xE501DB1E89C6D559);

  public IChoreoServices? ChoreoServices {
    get {
      var ptr = _Handle.Read<nint>(_ChoreoServicesOffset);
      return ptr.IsValidPtr() ? new IChoreoServicesImpl(ptr) : null;
    }
  }
  private static readonly nint _AnimGraphUpdateEnabledOffset = Schema.GetOffset(0xE501DB1E724F7FEE);

  public ref bool AnimGraphUpdateEnabled {
    get => ref _Handle.AsRef<bool>(_AnimGraphUpdateEnabledOffset);
  }
  private static readonly nint _MaxSlopeDistanceOffset = Schema.GetOffset(0xE501DB1E531F618D);

  public ref float MaxSlopeDistance {
    get => ref _Handle.AsRef<float>(_MaxSlopeDistanceOffset);
  }
  private static readonly nint _LastSlopeCheckPosOffset = Schema.GetOffset(0xE501DB1E586A5E32);

  public ref Vector LastSlopeCheckPos {
    get => ref _Handle.AsRef<Vector>(_LastSlopeCheckPosOffset);
  }
  private static readonly nint _AnimationUpdateScheduledOffset = Schema.GetOffset(0xE501DB1E49747BCF);

  public ref bool AnimationUpdateScheduled {
    get => ref _Handle.AsRef<bool>(_AnimationUpdateScheduledOffset);
  }
  private static readonly nint _ForceOffset = Schema.GetOffset(0xE501DB1E566BD764);

  public ref Vector Force {
    get => ref _Handle.AsRef<Vector>(_ForceOffset);
  }
  private static readonly nint _ForceBoneOffset = Schema.GetOffset(0xE501DB1EDDAC019E);

  public ref int ForceBone {
    get => ref _Handle.AsRef<int>(_ForceBoneOffset);
  }
  private static readonly nint _RagdollPoseOffset = Schema.GetOffset(0xE501DB1E49F01F45);

  public PhysicsRagdollPose_t RagdollPose {
    get => new PhysicsRagdollPose_tImpl(_Handle + _RagdollPoseOffset);
  }
  private static readonly nint _RagdollEnabledOffset = Schema.GetOffset(0xE501DB1E03EA7599);

  public ref bool RagdollEnabled {
    get => ref _Handle.AsRef<bool>(_RagdollEnabledOffset);
  }
  private static readonly nint _RagdollClientSideOffset = Schema.GetOffset(0xE501DB1EB6A5159C);

  public ref bool RagdollClientSide {
    get => ref _Handle.AsRef<bool>(_RagdollClientSideOffset);
  }
  private static readonly nint _XParentedRagdollRootInEntitySpaceOffset = Schema.GetOffset(0xE501DB1EFC4C1401);

  public ref CTransform XParentedRagdollRootInEntitySpace {
    get => ref _Handle.AsRef<CTransform>(_XParentedRagdollRootInEntitySpaceOffset);
  }

  public void InitiallyPopulateInterpHistoryUpdated() {
    Schema.Update(_Handle, 0xE501DB1E3087361C);
  }
  public void AnimGraphUpdateEnabledUpdated() {
    Schema.Update(_Handle, 0xE501DB1E724F7FEE);
  }
  public void ForceUpdated() {
    Schema.Update(_Handle, 0xE501DB1E566BD764);
  }
  public void ForceBoneUpdated() {
    Schema.Update(_Handle, 0xE501DB1EDDAC019E);
  }
  public void RagdollPoseUpdated() {
    Schema.Update(_Handle, 0xE501DB1E49F01F45);
  }
  public void RagdollEnabledUpdated() {
    Schema.Update(_Handle, 0xE501DB1E03EA7599);
  }
  public void RagdollClientSideUpdated() {
    Schema.Update(_Handle, 0xE501DB1EB6A5159C);
  }
}