// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CBaseCSGrenadeProjectileImpl : CBaseGrenadeImpl, CBaseCSGrenadeProjectile {

  public CBaseCSGrenadeProjectileImpl(nint handle) : base(handle) {
  }

  private static readonly nint _InitialPositionOffset = Schema.GetOffset(0xC09C67027E9CA9C4);

  public ref Vector InitialPosition {
    get => ref _Handle.AsRef<Vector>(_InitialPositionOffset);
  }
  private static readonly nint _InitialVelocityOffset = Schema.GetOffset(0xC09C67027C20BD90);

  public ref Vector InitialVelocity {
    get => ref _Handle.AsRef<Vector>(_InitialVelocityOffset);
  }
  private static readonly nint _BouncesOffset = Schema.GetOffset(0xC09C67026B81EBCE);

  public ref int Bounces {
    get => ref _Handle.AsRef<int>(_BouncesOffset);
  }
  private static readonly nint _ExplodeEffectIndexOffset = Schema.GetOffset(0xC09C6702178B5975);

  public ref CStrongHandle<InfoForResourceTypeIParticleSystemDefinition> ExplodeEffectIndex {
    get => ref _Handle.AsRef<CStrongHandle<InfoForResourceTypeIParticleSystemDefinition>>(_ExplodeEffectIndexOffset);
  }
  private static readonly nint _ExplodeEffectTickBeginOffset = Schema.GetOffset(0xC09C67022F04F603);

  public ref int ExplodeEffectTickBegin {
    get => ref _Handle.AsRef<int>(_ExplodeEffectTickBeginOffset);
  }
  private static readonly nint _ExplodeEffectOriginOffset = Schema.GetOffset(0xC09C6702AA7B4525);

  public ref Vector ExplodeEffectOrigin {
    get => ref _Handle.AsRef<Vector>(_ExplodeEffectOriginOffset);
  }
  private static readonly nint _SpawnTimeOffset = Schema.GetOffset(0xC09C67029596A16B);

  public GameTime_t SpawnTime {
    get => new GameTime_tImpl(_Handle + _SpawnTimeOffset);
  }
  private static readonly nint _OGSExtraFlagsOffset = Schema.GetOffset(0xC09C670221F95684);

  public ref byte OGSExtraFlags {
    get => ref _Handle.AsRef<byte>(_OGSExtraFlagsOffset);
  }
  private static readonly nint _DetonationRecordedOffset = Schema.GetOffset(0xC09C67024164A13C);

  public ref bool DetonationRecorded {
    get => ref _Handle.AsRef<bool>(_DetonationRecordedOffset);
  }
  private static readonly nint _ItemIndexOffset = Schema.GetOffset(0xC09C67025D8A6E7E);

  public ref ushort ItemIndex {
    get => ref _Handle.AsRef<ushort>(_ItemIndexOffset);
  }
  private static readonly nint _OriginalSpawnLocationOffset = Schema.GetOffset(0xC09C67025E59F382);

  public ref Vector OriginalSpawnLocation {
    get => ref _Handle.AsRef<Vector>(_OriginalSpawnLocationOffset);
  }
  private static readonly nint _LastBounceSoundTimeOffset = Schema.GetOffset(0xC09C670206AF4AB7);

  public GameTime_t LastBounceSoundTime {
    get => new GameTime_tImpl(_Handle + _LastBounceSoundTimeOffset);
  }
  private static readonly nint _GrenadeSpinOffset = Schema.GetOffset(0xC09C67025A836591);

  public SchemaUntypedField GrenadeSpin {
    get => new SchemaUntypedField(_Handle + _GrenadeSpinOffset);
  }
  private static readonly nint _LastHitSurfaceNormalOffset = Schema.GetOffset(0xC09C6702FAEF57FA);

  public ref Vector LastHitSurfaceNormal {
    get => ref _Handle.AsRef<Vector>(_LastHitSurfaceNormalOffset);
  }
  private static readonly nint _TicksAtZeroVelocityOffset = Schema.GetOffset(0xC09C6702A4946C6D);

  public ref int TicksAtZeroVelocity {
    get => ref _Handle.AsRef<int>(_TicksAtZeroVelocityOffset);
  }
  private static readonly nint _HasEverHitEnemyOffset = Schema.GetOffset(0xC09C670259285A50);

  public ref bool HasEverHitEnemy {
    get => ref _Handle.AsRef<bool>(_HasEverHitEnemyOffset);
  }

  public void InitialPositionUpdated() {
    Schema.Update(_Handle, 0xC09C67027E9CA9C4);
  }
  public void InitialVelocityUpdated() {
    Schema.Update(_Handle, 0xC09C67027C20BD90);
  }
  public void BouncesUpdated() {
    Schema.Update(_Handle, 0xC09C67026B81EBCE);
  }
  public void ExplodeEffectIndexUpdated() {
    Schema.Update(_Handle, 0xC09C6702178B5975);
  }
  public void ExplodeEffectTickBeginUpdated() {
    Schema.Update(_Handle, 0xC09C67022F04F603);
  }
  public void ExplodeEffectOriginUpdated() {
    Schema.Update(_Handle, 0xC09C6702AA7B4525);
  }
}