// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CBaseClientUIEntityImpl : CBaseModelEntityImpl, CBaseClientUIEntity {

  public CBaseClientUIEntityImpl(nint handle) : base(handle) {
  }

  private static readonly nint _EnabledOffset = Schema.GetOffset(0x51A22D116154EB7E);

  public ref bool Enabled {
    get => ref _Handle.AsRef<bool>(_EnabledOffset);
  }
  private static readonly nint _DialogXMLNameOffset = Schema.GetOffset(0x51A22D11D13858C9);

  public string DialogXMLName {
    get {
      var ptr = _Handle.Read<nint>(_DialogXMLNameOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _DialogXMLNameOffset, value);
  } 
  private static readonly nint _PanelClassNameOffset = Schema.GetOffset(0x51A22D115C958CBC);

  public string PanelClassName {
    get {
      var ptr = _Handle.Read<nint>(_PanelClassNameOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _PanelClassNameOffset, value);
  } 
  private static readonly nint _PanelIDOffset = Schema.GetOffset(0x51A22D1107A4EF60);

  public string PanelID {
    get {
      var ptr = _Handle.Read<nint>(_PanelIDOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _PanelIDOffset, value);
  } 
  private static readonly nint _CustomOutput0Offset = Schema.GetOffset(0x51A22D119AA5C775);

  public CEntityIOOutput CustomOutput0 {
    get => new CEntityIOOutputImpl(_Handle + _CustomOutput0Offset);
  }
  private static readonly nint _CustomOutput1Offset = Schema.GetOffset(0x51A22D1199A5C5E2);

  public CEntityIOOutput CustomOutput1 {
    get => new CEntityIOOutputImpl(_Handle + _CustomOutput1Offset);
  }
  private static readonly nint _CustomOutput2Offset = Schema.GetOffset(0x51A22D1198A5C44F);

  public CEntityIOOutput CustomOutput2 {
    get => new CEntityIOOutputImpl(_Handle + _CustomOutput2Offset);
  }
  private static readonly nint _CustomOutput3Offset = Schema.GetOffset(0x51A22D1197A5C2BC);

  public CEntityIOOutput CustomOutput3 {
    get => new CEntityIOOutputImpl(_Handle + _CustomOutput3Offset);
  }
  private static readonly nint _CustomOutput4Offset = Schema.GetOffset(0x51A22D1196A5C129);

  public CEntityIOOutput CustomOutput4 {
    get => new CEntityIOOutputImpl(_Handle + _CustomOutput4Offset);
  }
  private static readonly nint _CustomOutput5Offset = Schema.GetOffset(0x51A22D1195A5BF96);

  public CEntityIOOutput CustomOutput5 {
    get => new CEntityIOOutputImpl(_Handle + _CustomOutput5Offset);
  }
  private static readonly nint _CustomOutput6Offset = Schema.GetOffset(0x51A22D1194A5BE03);

  public CEntityIOOutput CustomOutput6 {
    get => new CEntityIOOutputImpl(_Handle + _CustomOutput6Offset);
  }
  private static readonly nint _CustomOutput7Offset = Schema.GetOffset(0x51A22D1193A5BC70);

  public CEntityIOOutput CustomOutput7 {
    get => new CEntityIOOutputImpl(_Handle + _CustomOutput7Offset);
  }
  private static readonly nint _CustomOutput8Offset = Schema.GetOffset(0x51A22D11A2A5D40D);

  public CEntityIOOutput CustomOutput8 {
    get => new CEntityIOOutputImpl(_Handle + _CustomOutput8Offset);
  }
  private static readonly nint _CustomOutput9Offset = Schema.GetOffset(0x51A22D11A1A5D27A);

  public CEntityIOOutput CustomOutput9 {
    get => new CEntityIOOutputImpl(_Handle + _CustomOutput9Offset);
  }

  public void EnabledUpdated() {
    Schema.Update(_Handle, 0x51A22D116154EB7E);
  }
  public void DialogXMLNameUpdated() {
    Schema.Update(_Handle, 0x51A22D11D13858C9);
  }
  public void PanelClassNameUpdated() {
    Schema.Update(_Handle, 0x51A22D115C958CBC);
  }
  public void PanelIDUpdated() {
    Schema.Update(_Handle, 0x51A22D1107A4EF60);
  }
}