// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CBasePlayerVDataImpl : CEntitySubclassVDataBaseImpl, CBasePlayerVData {

  public CBasePlayerVDataImpl(nint handle) : base(handle) {
  }

  private static readonly nint _ModelNameOffset = Schema.GetOffset(0x89A654F0002A227C);

  public SchemaUntypedField ModelName {
    get => new SchemaUntypedField(_Handle + _ModelNameOffset);
  }
  private static readonly nint _HeadDamageMultiplierOffset = Schema.GetOffset(0x89A654F0306CEA07);

  public CSkillFloat HeadDamageMultiplier {
    get => new CSkillFloatImpl(_Handle + _HeadDamageMultiplierOffset);
  }
  private static readonly nint _ChestDamageMultiplierOffset = Schema.GetOffset(0x89A654F0C82E808E);

  public CSkillFloat ChestDamageMultiplier {
    get => new CSkillFloatImpl(_Handle + _ChestDamageMultiplierOffset);
  }
  private static readonly nint _StomachDamageMultiplierOffset = Schema.GetOffset(0x89A654F0F84BFAFA);

  public CSkillFloat StomachDamageMultiplier {
    get => new CSkillFloatImpl(_Handle + _StomachDamageMultiplierOffset);
  }
  private static readonly nint _ArmDamageMultiplierOffset = Schema.GetOffset(0x89A654F071454291);

  public CSkillFloat ArmDamageMultiplier {
    get => new CSkillFloatImpl(_Handle + _ArmDamageMultiplierOffset);
  }
  private static readonly nint _LegDamageMultiplierOffset = Schema.GetOffset(0x89A654F0F2F8B1BB);

  public CSkillFloat LegDamageMultiplier {
    get => new CSkillFloatImpl(_Handle + _LegDamageMultiplierOffset);
  }
  private static readonly nint _HoldBreathTimeOffset = Schema.GetOffset(0x89A654F093F22051);

  public ref float HoldBreathTime {
    get => ref _Handle.AsRef<float>(_HoldBreathTimeOffset);
  }
  private static readonly nint _DrowningDamageIntervalOffset = Schema.GetOffset(0x89A654F05ECD13F9);

  public ref float DrowningDamageInterval {
    get => ref _Handle.AsRef<float>(_DrowningDamageIntervalOffset);
  }
  private static readonly nint _DrowningDamageInitialOffset = Schema.GetOffset(0x89A654F0155618A2);

  public ref int DrowningDamageInitial {
    get => ref _Handle.AsRef<int>(_DrowningDamageInitialOffset);
  }
  private static readonly nint _DrowningDamageMaxOffset = Schema.GetOffset(0x89A654F0E3FA4428);

  public ref int DrowningDamageMax {
    get => ref _Handle.AsRef<int>(_DrowningDamageMaxOffset);
  }
  private static readonly nint _WaterSpeedOffset = Schema.GetOffset(0x89A654F0CED804D7);

  public ref int WaterSpeed {
    get => ref _Handle.AsRef<int>(_WaterSpeedOffset);
  }
  private static readonly nint _UseRangeOffset = Schema.GetOffset(0x89A654F03B375BF3);

  public ref float UseRange {
    get => ref _Handle.AsRef<float>(_UseRangeOffset);
  }
  private static readonly nint _UseAngleToleranceOffset = Schema.GetOffset(0x89A654F01A464300);

  public ref float UseAngleTolerance {
    get => ref _Handle.AsRef<float>(_UseAngleToleranceOffset);
  }
  private static readonly nint _CrouchTimeOffset = Schema.GetOffset(0x89A654F01E805FB4);

  public ref float CrouchTime {
    get => ref _Handle.AsRef<float>(_CrouchTimeOffset);
  }


}