// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CBaseGrenadeImpl : CBaseFlexImpl, CBaseGrenade {

  public CBaseGrenadeImpl(nint handle) : base(handle) {
  }

  private static readonly nint _OnPlayerPickupOffset = Schema.GetOffset(0xB6ACD98FDE81BF25);

  public CEntityIOOutput OnPlayerPickup {
    get => new CEntityIOOutputImpl(_Handle + _OnPlayerPickupOffset);
  }
  private static readonly nint _OnExplodeOffset = Schema.GetOffset(0xB6ACD98F5153ED85);

  public CEntityIOOutput OnExplode {
    get => new CEntityIOOutputImpl(_Handle + _OnExplodeOffset);
  }
  private static readonly nint _HasWarnedAIOffset = Schema.GetOffset(0xB6ACD98F52149340);

  public ref bool HasWarnedAI {
    get => ref _Handle.AsRef<bool>(_HasWarnedAIOffset);
  }
  private static readonly nint _IsSmokeGrenadeOffset = Schema.GetOffset(0xB6ACD98FD26F58DC);

  public ref bool IsSmokeGrenade {
    get => ref _Handle.AsRef<bool>(_IsSmokeGrenadeOffset);
  }
  private static readonly nint _IsLiveOffset = Schema.GetOffset(0xB6ACD98F4DBE6B1F);

  public ref bool IsLive {
    get => ref _Handle.AsRef<bool>(_IsLiveOffset);
  }
  private static readonly nint _DmgRadiusOffset = Schema.GetOffset(0xB6ACD98FB9ADFB35);

  public ref float DmgRadius {
    get => ref _Handle.AsRef<float>(_DmgRadiusOffset);
  }
  private static readonly nint _DetonateTimeOffset = Schema.GetOffset(0xB6ACD98F884102F2);

  public GameTime_t DetonateTime {
    get => new GameTime_tImpl(_Handle + _DetonateTimeOffset);
  }
  private static readonly nint _WarnAITimeOffset = Schema.GetOffset(0xB6ACD98FFC4F4550);

  public ref float WarnAITime {
    get => ref _Handle.AsRef<float>(_WarnAITimeOffset);
  }
  private static readonly nint _DamageOffset = Schema.GetOffset(0xB6ACD98FDC60E53E);

  public ref float Damage {
    get => ref _Handle.AsRef<float>(_DamageOffset);
  }
  private static readonly nint _BounceSoundOffset = Schema.GetOffset(0xB6ACD98F060D1544);

  public string BounceSound {
    get {
      var ptr = _Handle.Read<nint>(_BounceSoundOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _BounceSoundOffset, value);
  } 
  private static readonly nint _ExplosionSoundOffset = Schema.GetOffset(0xB6ACD98FEA1C20EF);

  public string ExplosionSound {
    get {
      var ptr = _Handle.Read<nint>(_ExplosionSoundOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _ExplosionSoundOffset, value);
  } 
  private static readonly nint _ThrowerOffset = Schema.GetOffset(0xB6ACD98FC9CF8702);

  public ref CHandle<CCSPlayerPawn> Thrower {
    get => ref _Handle.AsRef<CHandle<CCSPlayerPawn>>(_ThrowerOffset);
  }
  private static readonly nint _NextAttackOffset = Schema.GetOffset(0xB6ACD98F3DFDCDEA);

  public GameTime_t NextAttack {
    get => new GameTime_tImpl(_Handle + _NextAttackOffset);
  }
  private static readonly nint _OriginalThrowerOffset = Schema.GetOffset(0xB6ACD98F34FD45A3);

  public ref CHandle<CCSPlayerPawn> OriginalThrower {
    get => ref _Handle.AsRef<CHandle<CCSPlayerPawn>>(_OriginalThrowerOffset);
  }

  public void IsLiveUpdated() {
    Schema.Update(_Handle, 0xB6ACD98F4DBE6B1F);
  }
  public void DmgRadiusUpdated() {
    Schema.Update(_Handle, 0xB6ACD98FB9ADFB35);
  }
  public void DetonateTimeUpdated() {
    Schema.Update(_Handle, 0xB6ACD98F884102F2);
  }
  public void DamageUpdated() {
    Schema.Update(_Handle, 0xB6ACD98FDC60E53E);
  }
  public void ThrowerUpdated() {
    Schema.Update(_Handle, 0xB6ACD98FC9CF8702);
  }
}