// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CBlendUpdateNodeImpl : CAnimUpdateNodeBaseImpl, CBlendUpdateNode {

  public CBlendUpdateNodeImpl(nint handle) : base(handle) {
  }

  private static readonly nint _ChildrenOffset = Schema.GetOffset(0xD72498B47415FA72);

  public ref CUtlVector<CAnimUpdateNodeRef> Children {
    get => ref _Handle.AsRef<CUtlVector<CAnimUpdateNodeRef>>(_ChildrenOffset);
  }
  private static readonly nint _SortedOrderOffset = Schema.GetOffset(0xD72498B47CE82340);

  public ref CUtlVector<byte> SortedOrder {
    get => ref _Handle.AsRef<CUtlVector<byte>>(_SortedOrderOffset);
  }
  private static readonly nint _TargetValuesOffset = Schema.GetOffset(0xD72498B4913AEBFE);

  public ref CUtlVector<float> TargetValues {
    get => ref _Handle.AsRef<CUtlVector<float>>(_TargetValuesOffset);
  }
  private static readonly nint _BlendValueSourceOffset = Schema.GetOffset(0xD72498B47AB7C374);

  public ref AnimValueSource BlendValueSource {
    get => ref _Handle.AsRef<AnimValueSource>(_BlendValueSourceOffset);
  }
  private static readonly nint _LinearRootMotionBlendModeOffset = Schema.GetOffset(0xD72498B4580BA151);

  public ref LinearRootMotionBlendMode_t LinearRootMotionBlendMode {
    get => ref _Handle.AsRef<LinearRootMotionBlendMode_t>(_LinearRootMotionBlendModeOffset);
  }
  private static readonly nint _ParamIndexOffset = Schema.GetOffset(0xD72498B461990A86);

  public CAnimParamHandle ParamIndex {
    get => new CAnimParamHandleImpl(_Handle + _ParamIndexOffset);
  }
  private static readonly nint _DampingOffset = Schema.GetOffset(0xD72498B415440FB5);

  public CAnimInputDamping Damping {
    get => new CAnimInputDampingImpl(_Handle + _DampingOffset);
  }
  private static readonly nint _BlendKeyTypeOffset = Schema.GetOffset(0xD72498B4CD00B87F);

  public ref BlendKeyType BlendKeyType {
    get => ref _Handle.AsRef<BlendKeyType>(_BlendKeyTypeOffset);
  }
  private static readonly nint _LockBlendOnResetOffset = Schema.GetOffset(0xD72498B476334223);

  public ref bool LockBlendOnReset {
    get => ref _Handle.AsRef<bool>(_LockBlendOnResetOffset);
  }
  private static readonly nint _SyncCyclesOffset = Schema.GetOffset(0xD72498B4EFFB5395);

  public ref bool SyncCycles {
    get => ref _Handle.AsRef<bool>(_SyncCyclesOffset);
  }
  private static readonly nint _LoopOffset = Schema.GetOffset(0xD72498B4C668A4CB);

  public ref bool Loop {
    get => ref _Handle.AsRef<bool>(_LoopOffset);
  }
  private static readonly nint _LockWhenWaningOffset = Schema.GetOffset(0xD72498B4EED48004);

  public ref bool LockWhenWaning {
    get => ref _Handle.AsRef<bool>(_LockWhenWaningOffset);
  }
  private static readonly nint _IsAngleOffset = Schema.GetOffset(0xD72498B4DE976A88);

  public ref bool IsAngle {
    get => ref _Handle.AsRef<bool>(_IsAngleOffset);
  }


}