// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CBloodImpl : CPointEntityImpl, CBlood {

  public CBloodImpl(nint handle) : base(handle) {
  }

  private static readonly nint _SprayAnglesOffset = Schema.GetOffset(0x68CF460A2BDF444E);

  public ref QAngle SprayAngles {
    get => ref _Handle.AsRef<QAngle>(_SprayAnglesOffset);
  }
  private static readonly nint _SprayDirOffset = Schema.GetOffset(0x68CF460A0A8A2531);

  public ref Vector SprayDir {
    get => ref _Handle.AsRef<Vector>(_SprayDirOffset);
  }
  private static readonly nint _AmountOffset = Schema.GetOffset(0x68CF460A187D1B1B);

  public ref float Amount {
    get => ref _Handle.AsRef<float>(_AmountOffset);
  }
  private static readonly nint _ColorOffset = Schema.GetOffset(0x68CF460AD7D017D8);

  public ref BloodType Color {
    get => ref _Handle.AsRef<BloodType>(_ColorOffset);
  }


}