// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CBtActionAimImpl : CBtNodeImpl, CBtActionAim {

  public CBtActionAimImpl(nint handle) : base(handle) {
  }

  private static readonly nint _SensorInputKeyOffset = Schema.GetOffset(0x43587513D2B0D4C1);

  public string SensorInputKey {
    get {
      var ptr = _Handle.Read<nint>(_SensorInputKeyOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _SensorInputKeyOffset, value);
  } 
  private static readonly nint _AimReadyKeyOffset = Schema.GetOffset(0x435875136718A4C7);

  public string AimReadyKey {
    get {
      var ptr = _Handle.Read<nint>(_AimReadyKeyOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _AimReadyKeyOffset, value);
  } 
  private static readonly nint _ZoomCooldownTimestampOffset = Schema.GetOffset(0x43587513F2898D9F);

  public ref float ZoomCooldownTimestamp {
    get => ref _Handle.AsRef<float>(_ZoomCooldownTimestampOffset);
  }
  private static readonly nint _DoneAimingOffset = Schema.GetOffset(0x43587513F2C3ADDE);

  public ref bool DoneAiming {
    get => ref _Handle.AsRef<bool>(_DoneAimingOffset);
  }
  private static readonly nint _LerpStartTimeOffset = Schema.GetOffset(0x43587513B67B575F);

  public ref float LerpStartTime {
    get => ref _Handle.AsRef<float>(_LerpStartTimeOffset);
  }
  private static readonly nint _NextLookTargetLerpTimeOffset = Schema.GetOffset(0x43587513768D7F08);

  public ref float NextLookTargetLerpTime {
    get => ref _Handle.AsRef<float>(_NextLookTargetLerpTimeOffset);
  }
  private static readonly nint _PenaltyReductionRatioOffset = Schema.GetOffset(0x43587513BB3B4A10);

  public ref float PenaltyReductionRatio {
    get => ref _Handle.AsRef<float>(_PenaltyReductionRatioOffset);
  }
  private static readonly nint _NextLookTargetOffset = Schema.GetOffset(0x43587513C1D3F3CE);

  public ref QAngle NextLookTarget {
    get => ref _Handle.AsRef<QAngle>(_NextLookTargetOffset);
  }
  private static readonly nint _AimTimerOffset = Schema.GetOffset(0x4358751330E31F47);

  public CountdownTimer AimTimer {
    get => new CountdownTimerImpl(_Handle + _AimTimerOffset);
  }
  private static readonly nint _SniperHoldTimerOffset = Schema.GetOffset(0x43587513B206F2AC);

  public CountdownTimer SniperHoldTimer {
    get => new CountdownTimerImpl(_Handle + _SniperHoldTimerOffset);
  }
  private static readonly nint _FocusIntervalTimerOffset = Schema.GetOffset(0x43587513267063CB);

  public CountdownTimer FocusIntervalTimer {
    get => new CountdownTimerImpl(_Handle + _FocusIntervalTimerOffset);
  }
  private static readonly nint _AcquiredOffset = Schema.GetOffset(0x435875131D2FE5B5);

  public ref bool Acquired {
    get => ref _Handle.AsRef<bool>(_AcquiredOffset);
  }


}