// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CCachedPoseImpl : SchemaClass, CCachedPose {

  public CCachedPoseImpl(nint handle) : base(handle) {
  }

  private static readonly nint _TransformsOffset = Schema.GetOffset(0x4B6C235988C82C58);

  public ref CUtlVector<CTransform> Transforms {
    get => ref _Handle.AsRef<CUtlVector<CTransform>>(_TransformsOffset);
  }
  private static readonly nint _MorphWeightsOffset = Schema.GetOffset(0x4B6C23596B6689BE);

  public ref CUtlVector<float> MorphWeights {
    get => ref _Handle.AsRef<CUtlVector<float>>(_MorphWeightsOffset);
  }
  private static readonly nint _SequenceOffset = Schema.GetOffset(0x4B6C2359E0A0598E);

  public HSequence Sequence {
    get => new HSequenceImpl(_Handle + _SequenceOffset);
  }
  private static readonly nint _CycleOffset = Schema.GetOffset(0x4B6C23590C77829F);

  public ref float Cycle {
    get => ref _Handle.AsRef<float>(_CycleOffset);
  }


}