// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CCSPlayerPawnImpl : CCSPlayerPawnBaseImpl, CCSPlayerPawn {

  public CCSPlayerPawnImpl(nint handle) : base(handle) {
  }

  private static readonly nint _BulletServicesOffset = Schema.GetOffset(0xC7614AAB8E2741BB);

  public CCSPlayer_BulletServices? BulletServices {
    get {
      var ptr = _Handle.Read<nint>(_BulletServicesOffset);
      return ptr.IsValidPtr() ? new CCSPlayer_BulletServicesImpl(ptr) : null;
    }
  }
  private static readonly nint _HostageServicesOffset = Schema.GetOffset(0xC7614AAB63EBD1D8);

  public CCSPlayer_HostageServices? HostageServices {
    get {
      var ptr = _Handle.Read<nint>(_HostageServicesOffset);
      return ptr.IsValidPtr() ? new CCSPlayer_HostageServicesImpl(ptr) : null;
    }
  }
  private static readonly nint _BuyServicesOffset = Schema.GetOffset(0xC7614AAB807A410D);

  public CCSPlayer_BuyServices? BuyServices {
    get {
      var ptr = _Handle.Read<nint>(_BuyServicesOffset);
      return ptr.IsValidPtr() ? new CCSPlayer_BuyServicesImpl(ptr) : null;
    }
  }
  private static readonly nint _ActionTrackingServicesOffset = Schema.GetOffset(0xC7614AABB8174144);

  public CCSPlayer_ActionTrackingServices? ActionTrackingServices {
    get {
      var ptr = _Handle.Read<nint>(_ActionTrackingServicesOffset);
      return ptr.IsValidPtr() ? new CCSPlayer_ActionTrackingServicesImpl(ptr) : null;
    }
  }
  private static readonly nint _RadioServicesOffset = Schema.GetOffset(0xC7614AAB6C70C036);

  public CCSPlayer_RadioServices? RadioServices {
    get {
      var ptr = _Handle.Read<nint>(_RadioServicesOffset);
      return ptr.IsValidPtr() ? new CCSPlayer_RadioServicesImpl(ptr) : null;
    }
  }
  private static readonly nint _DamageReactServicesOffset = Schema.GetOffset(0xC7614AABF4CD61D9);

  public CCSPlayer_DamageReactServices? DamageReactServices {
    get {
      var ptr = _Handle.Read<nint>(_DamageReactServicesOffset);
      return ptr.IsValidPtr() ? new CCSPlayer_DamageReactServicesImpl(ptr) : null;
    }
  }
  private static readonly nint _CharacterDefIndexOffset = Schema.GetOffset(0xC7614AABA96BAF31);

  public ref ushort CharacterDefIndex {
    get => ref _Handle.AsRef<ushort>(_CharacterDefIndexOffset);
  }
  private static readonly nint _HasFemaleVoiceOffset = Schema.GetOffset(0xC7614AAB7E7752FF);

  public ref bool HasFemaleVoice {
    get => ref _Handle.AsRef<bool>(_HasFemaleVoiceOffset);
  }
  private static readonly nint _StrVOPrefixOffset = Schema.GetOffset(0xC7614AAB86FA355B);

  public string StrVOPrefix {
    get {
      var ptr = _Handle.Read<nint>(_StrVOPrefixOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _StrVOPrefixOffset, value);
  } 
  private static readonly nint _LastPlaceNameOffset = Schema.GetOffset(0xC7614AAB4C28E3A0);

  public string LastPlaceName {
    get {
      var ptr = _Handle + _LastPlaceNameOffset;
      return Schema.GetString(ptr);
    }
    set => Schema.SetFixedString(_Handle, _LastPlaceNameOffset, value, 18);
  } 
  private static readonly nint _InHostageResetZoneOffset = Schema.GetOffset(0xC7614AAB5C3C71CC);

  public ref bool InHostageResetZone {
    get => ref _Handle.AsRef<bool>(_InHostageResetZoneOffset);
  }
  private static readonly nint _InBuyZoneOffset = Schema.GetOffset(0xC7614AAB3AC1BD10);

  public ref bool InBuyZone {
    get => ref _Handle.AsRef<bool>(_InBuyZoneOffset);
  }
  private static readonly nint _TouchingBuyZonesOffset = Schema.GetOffset(0xC7614AABD244D3EF);

  public ref CUtlVector<CHandle<CBaseEntity>> TouchingBuyZones {
    get => ref _Handle.AsRef<CUtlVector<CHandle<CBaseEntity>>>(_TouchingBuyZonesOffset);
  }
  private static readonly nint _WasInBuyZoneOffset = Schema.GetOffset(0xC7614AABDE7A51C9);

  public ref bool WasInBuyZone {
    get => ref _Handle.AsRef<bool>(_WasInBuyZoneOffset);
  }
  private static readonly nint _InHostageRescueZoneOffset = Schema.GetOffset(0xC7614AABBFE04B90);

  public ref bool InHostageRescueZone {
    get => ref _Handle.AsRef<bool>(_InHostageRescueZoneOffset);
  }
  private static readonly nint _InBombZoneOffset = Schema.GetOffset(0xC7614AABCB89478C);

  public ref bool InBombZone {
    get => ref _Handle.AsRef<bool>(_InBombZoneOffset);
  }
  private static readonly nint _WasInHostageRescueZoneOffset = Schema.GetOffset(0xC7614AAB008C8EF9);

  public ref bool WasInHostageRescueZone {
    get => ref _Handle.AsRef<bool>(_WasInHostageRescueZoneOffset);
  }
  private static readonly nint _RetakesOfferingOffset = Schema.GetOffset(0xC7614AABD729481D);

  public ref int RetakesOffering {
    get => ref _Handle.AsRef<int>(_RetakesOfferingOffset);
  }
  private static readonly nint _RetakesOfferingCardOffset = Schema.GetOffset(0xC7614AAB3C338797);

  public ref int RetakesOfferingCard {
    get => ref _Handle.AsRef<int>(_RetakesOfferingCardOffset);
  }
  private static readonly nint _RetakesHasDefuseKitOffset = Schema.GetOffset(0xC7614AABEFC4B30A);

  public ref bool RetakesHasDefuseKit {
    get => ref _Handle.AsRef<bool>(_RetakesHasDefuseKitOffset);
  }
  private static readonly nint _RetakesMVPLastRoundOffset = Schema.GetOffset(0xC7614AABC87BFEF3);

  public ref bool RetakesMVPLastRound {
    get => ref _Handle.AsRef<bool>(_RetakesMVPLastRoundOffset);
  }
  private static readonly nint _RetakesMVPBoostItemOffset = Schema.GetOffset(0xC7614AABEC8D220C);

  public ref int RetakesMVPBoostItem {
    get => ref _Handle.AsRef<int>(_RetakesMVPBoostItemOffset);
  }
  private static readonly nint _RetakesMVPBoostExtraUtilityOffset = Schema.GetOffset(0xC7614AABADA37062);

  public ref loadout_slot_t RetakesMVPBoostExtraUtility {
    get => ref _Handle.AsRef<loadout_slot_t>(_RetakesMVPBoostExtraUtilityOffset);
  }
  private static readonly nint _HealthShotBoostExpirationTimeOffset = Schema.GetOffset(0xC7614AABEC487ACC);

  public GameTime_t HealthShotBoostExpirationTime {
    get => new GameTime_tImpl(_Handle + _HealthShotBoostExpirationTimeOffset);
  }
  private static readonly nint _LandingTimeSecondsOffset = Schema.GetOffset(0xC7614AAB7D39AEE4);

  public ref float LandingTimeSeconds {
    get => ref _Handle.AsRef<float>(_LandingTimeSecondsOffset);
  }
  private static readonly nint _AimPunchAngleOffset = Schema.GetOffset(0xC7614AAB1E948CB9);

  public ref QAngle AimPunchAngle {
    get => ref _Handle.AsRef<QAngle>(_AimPunchAngleOffset);
  }
  private static readonly nint _AimPunchAngleVelOffset = Schema.GetOffset(0xC7614AABB30DE0EC);

  public ref QAngle AimPunchAngleVel {
    get => ref _Handle.AsRef<QAngle>(_AimPunchAngleVelOffset);
  }
  private static readonly nint _AimPunchTickBaseOffset = Schema.GetOffset(0xC7614AABB9C874A2);

  public GameTick_t AimPunchTickBase {
    get => new GameTick_tImpl(_Handle + _AimPunchTickBaseOffset);
  }
  private static readonly nint _AimPunchTickFractionOffset = Schema.GetOffset(0xC7614AAB90BE3E69);

  public ref float AimPunchTickFraction {
    get => ref _Handle.AsRef<float>(_AimPunchTickFractionOffset);
  }
  private static readonly nint _AimPunchCacheOffset = Schema.GetOffset(0xC7614AAB824312D8);

  public ref CUtlVector<QAngle> AimPunchCache {
    get => ref _Handle.AsRef<CUtlVector<QAngle>>(_AimPunchCacheOffset);
  }
  private static readonly nint _IsBuyMenuOpenOffset = Schema.GetOffset(0xC7614AABFBCDD8EC);

  public ref bool IsBuyMenuOpen {
    get => ref _Handle.AsRef<bool>(_IsBuyMenuOpenOffset);
  }
  private static readonly nint _LastLandTimeOffset = Schema.GetOffset(0xC7614AAB21F4A3D1);

  public GameTime_t LastLandTime {
    get => new GameTime_tImpl(_Handle + _LastLandTimeOffset);
  }
  private static readonly nint _OnGroundLastTickOffset = Schema.GetOffset(0xC7614AABF09CFC72);

  public ref bool OnGroundLastTick {
    get => ref _Handle.AsRef<bool>(_OnGroundLastTickOffset);
  }
  private static readonly nint _PlayerLockedOffset = Schema.GetOffset(0xC7614AABAE9A0717);

  public ref int PlayerLocked {
    get => ref _Handle.AsRef<int>(_PlayerLockedOffset);
  }
  private static readonly nint _TimeOfLastInjuryOffset = Schema.GetOffset(0xC7614AABD7B4663C);

  public GameTime_t TimeOfLastInjury {
    get => new GameTime_tImpl(_Handle + _TimeOfLastInjuryOffset);
  }
  private static readonly nint _NextSprayDecalTimeOffset = Schema.GetOffset(0xC7614AAB53790011);

  public GameTime_t NextSprayDecalTime {
    get => new GameTime_tImpl(_Handle + _NextSprayDecalTimeOffset);
  }
  private static readonly nint _NextSprayDecalTimeExpeditedOffset = Schema.GetOffset(0xC7614AAB8C1B26CB);

  public ref bool NextSprayDecalTimeExpedited {
    get => ref _Handle.AsRef<bool>(_NextSprayDecalTimeExpeditedOffset);
  }
  private static readonly nint _RagdollDamageBoneOffset = Schema.GetOffset(0xC7614AAB31F4732F);

  public ref int RagdollDamageBone {
    get => ref _Handle.AsRef<int>(_RagdollDamageBoneOffset);
  }
  private static readonly nint _RagdollDamageForceOffset = Schema.GetOffset(0xC7614AAB7FBF68CC);

  public ref Vector RagdollDamageForce {
    get => ref _Handle.AsRef<Vector>(_RagdollDamageForceOffset);
  }
  private static readonly nint _RagdollDamagePositionOffset = Schema.GetOffset(0xC7614AAB29671362);

  public ref Vector RagdollDamagePosition {
    get => ref _Handle.AsRef<Vector>(_RagdollDamagePositionOffset);
  }
  private static readonly nint _RagdollDamageWeaponNameOffset = Schema.GetOffset(0xC7614AABDAAFA519);

  public string RagdollDamageWeaponName {
    get {
      var ptr = _Handle + _RagdollDamageWeaponNameOffset;
      return Schema.GetString(ptr);
    }
    set => Schema.SetFixedString(_Handle, _RagdollDamageWeaponNameOffset, value, 64);
  } 
  private static readonly nint _RagdollDamageHeadshotOffset = Schema.GetOffset(0xC7614AAB324979E7);

  public ref bool RagdollDamageHeadshot {
    get => ref _Handle.AsRef<bool>(_RagdollDamageHeadshotOffset);
  }
  private static readonly nint _RagdollServerOriginOffset = Schema.GetOffset(0xC7614AAB24991D61);

  public ref Vector RagdollServerOrigin {
    get => ref _Handle.AsRef<Vector>(_RagdollServerOriginOffset);
  }
  private static readonly nint _EconGlovesOffset = Schema.GetOffset(0xC7614AAB58DEE8E2);

  public CEconItemView EconGloves {
    get => new CEconItemViewImpl(_Handle + _EconGlovesOffset);
  }
  private static readonly nint _EconGlovesChangedOffset = Schema.GetOffset(0xC7614AAB617F6ACA);

  public ref byte EconGlovesChanged {
    get => ref _Handle.AsRef<byte>(_EconGlovesChangedOffset);
  }
  private static readonly nint _DeathEyeAnglesOffset = Schema.GetOffset(0xC7614AAB6F21BE57);

  public ref QAngle DeathEyeAngles {
    get => ref _Handle.AsRef<QAngle>(_DeathEyeAnglesOffset);
  }
  private static readonly nint _SkipOneHeadConstraintUpdateOffset = Schema.GetOffset(0xC7614AAB98DC3AB2);

  public ref bool SkipOneHeadConstraintUpdate {
    get => ref _Handle.AsRef<bool>(_SkipOneHeadConstraintUpdateOffset);
  }
  private static readonly nint _LeftHandedOffset = Schema.GetOffset(0xC7614AAB63906F18);

  public ref bool LeftHanded {
    get => ref _Handle.AsRef<bool>(_LeftHandedOffset);
  }
  private static readonly nint _SwitchedHandednessTimeOffset = Schema.GetOffset(0xC7614AAB40B8D9FE);

  public GameTime_t SwitchedHandednessTime {
    get => new GameTime_tImpl(_Handle + _SwitchedHandednessTimeOffset);
  }
  private static readonly nint _ViewmodelOffsetXOffset = Schema.GetOffset(0xC7614AAB6890E2BC);

  public ref float ViewmodelOffsetX {
    get => ref _Handle.AsRef<float>(_ViewmodelOffsetXOffset);
  }
  private static readonly nint _ViewmodelOffsetYOffset = Schema.GetOffset(0xC7614AAB6990E44F);

  public ref float ViewmodelOffsetY {
    get => ref _Handle.AsRef<float>(_ViewmodelOffsetYOffset);
  }
  private static readonly nint _ViewmodelOffsetZOffset = Schema.GetOffset(0xC7614AAB6A90E5E2);

  public ref float ViewmodelOffsetZ {
    get => ref _Handle.AsRef<float>(_ViewmodelOffsetZOffset);
  }
  private static readonly nint _ViewmodelFOVOffset = Schema.GetOffset(0xC7614AAB08EEBF76);

  public ref float ViewmodelFOV {
    get => ref _Handle.AsRef<float>(_ViewmodelFOVOffset);
  }
  private static readonly nint _IsWalkingOffset = Schema.GetOffset(0xC7614AAB9441C788);

  public ref bool IsWalking {
    get => ref _Handle.AsRef<bool>(_IsWalkingOffset);
  }
  private static readonly nint _LastGivenDefuserTimeOffset = Schema.GetOffset(0xC7614AABDF220E63);

  public ref float LastGivenDefuserTime {
    get => ref _Handle.AsRef<float>(_LastGivenDefuserTimeOffset);
  }
  private static readonly nint _LastGivenBombTimeOffset = Schema.GetOffset(0xC7614AAB99769553);

  public ref float LastGivenBombTime {
    get => ref _Handle.AsRef<float>(_LastGivenBombTimeOffset);
  }
  private static readonly nint _DealtDamageToEnemyMostRecentTimestampOffset = Schema.GetOffset(0xC7614AABAF8A5253);

  public ref float DealtDamageToEnemyMostRecentTimestamp {
    get => ref _Handle.AsRef<float>(_DealtDamageToEnemyMostRecentTimestampOffset);
  }
  private static readonly nint _DisplayHistoryBitsOffset = Schema.GetOffset(0xC7614AAB76E75E62);

  public ref uint DisplayHistoryBits {
    get => ref _Handle.AsRef<uint>(_DisplayHistoryBitsOffset);
  }
  private static readonly nint _LastAttackedTeammateOffset = Schema.GetOffset(0xC7614AABC0E777B2);

  public ref float LastAttackedTeammate {
    get => ref _Handle.AsRef<float>(_LastAttackedTeammateOffset);
  }
  private static readonly nint _AllowAutoFollowTimeOffset = Schema.GetOffset(0xC7614AABA781FC01);

  public GameTime_t AllowAutoFollowTime {
    get => new GameTime_tImpl(_Handle + _AllowAutoFollowTimeOffset);
  }
  private static readonly nint _ResetArmorNextSpawnOffset = Schema.GetOffset(0xC7614AAB6B761085);

  public ref bool ResetArmorNextSpawn {
    get => ref _Handle.AsRef<bool>(_ResetArmorNextSpawnOffset);
  }
  private static readonly nint _LastKillerIndexOffset = Schema.GetOffset(0xC7614AABA4700326);

  public ref uint LastKillerIndex {
    get => ref _Handle.AsRef<uint>(_LastKillerIndexOffset);
  }
  private static readonly nint _EntitySpottedStateOffset = Schema.GetOffset(0xC7614AAB032B547C);

  public EntitySpottedState_t EntitySpottedState {
    get => new EntitySpottedState_tImpl(_Handle + _EntitySpottedStateOffset);
  }
  private static readonly nint _SpotRulesOffset = Schema.GetOffset(0xC7614AAB776CCE44);

  public ref int SpotRules {
    get => ref _Handle.AsRef<int>(_SpotRulesOffset);
  }
  private static readonly nint _IsScopedOffset = Schema.GetOffset(0xC7614AABF3E9A9ED);

  public ref bool IsScoped {
    get => ref _Handle.AsRef<bool>(_IsScopedOffset);
  }
  private static readonly nint _ResumeZoomOffset = Schema.GetOffset(0xC7614AABB4707FB1);

  public ref bool ResumeZoom {
    get => ref _Handle.AsRef<bool>(_ResumeZoomOffset);
  }
  private static readonly nint _IsDefusingOffset = Schema.GetOffset(0xC7614AAB5BDAECC0);

  public ref bool IsDefusing {
    get => ref _Handle.AsRef<bool>(_IsDefusingOffset);
  }
  private static readonly nint _IsGrabbingHostageOffset = Schema.GetOffset(0xC7614AAB43AC7BEA);

  public ref bool IsGrabbingHostage {
    get => ref _Handle.AsRef<bool>(_IsGrabbingHostageOffset);
  }
  private static readonly nint _BlockingUseActionInProgressOffset = Schema.GetOffset(0xC7614AAB6B0B2AC0);

  public ref CSPlayerBlockingUseAction_t BlockingUseActionInProgress {
    get => ref _Handle.AsRef<CSPlayerBlockingUseAction_t>(_BlockingUseActionInProgressOffset);
  }
  private static readonly nint _EmitSoundTimeOffset = Schema.GetOffset(0xC7614AABC6FA84FA);

  public GameTime_t EmitSoundTime {
    get => new GameTime_tImpl(_Handle + _EmitSoundTimeOffset);
  }
  private static readonly nint _InNoDefuseAreaOffset = Schema.GetOffset(0xC7614AAB10C6FF02);

  public ref bool InNoDefuseArea {
    get => ref _Handle.AsRef<bool>(_InNoDefuseAreaOffset);
  }
  private static readonly nint _BombSiteIndexOffset = Schema.GetOffset(0xC7614AAB14DD85B5);

  public ref uint BombSiteIndex {
    get => ref _Handle.AsRef<uint>(_BombSiteIndexOffset);
  }
  private static readonly nint _WhichBombZoneOffset = Schema.GetOffset(0xC7614AAB0D69FABC);

  public ref int WhichBombZone {
    get => ref _Handle.AsRef<int>(_WhichBombZoneOffset);
  }
  private static readonly nint _InBombZoneTriggerOffset = Schema.GetOffset(0xC7614AAB73871310);

  public ref bool InBombZoneTrigger {
    get => ref _Handle.AsRef<bool>(_InBombZoneTriggerOffset);
  }
  private static readonly nint _WasInBombZoneTriggerOffset = Schema.GetOffset(0xC7614AAB2660272D);

  public ref bool WasInBombZoneTrigger {
    get => ref _Handle.AsRef<bool>(_WasInBombZoneTriggerOffset);
  }
  private static readonly nint _ShotsFiredOffset = Schema.GetOffset(0xC7614AABFE518C17);

  public ref int ShotsFired {
    get => ref _Handle.AsRef<int>(_ShotsFiredOffset);
  }
  private static readonly nint _FlinchStackOffset = Schema.GetOffset(0xC7614AAB36439B97);

  public ref float FlinchStack {
    get => ref _Handle.AsRef<float>(_FlinchStackOffset);
  }
  private static readonly nint _VelocityModifierOffset = Schema.GetOffset(0xC7614AAB7AC97631);

  public ref float VelocityModifier {
    get => ref _Handle.AsRef<float>(_VelocityModifierOffset);
  }
  private static readonly nint _HitHeadingOffset = Schema.GetOffset(0xC7614AAB09713C4E);

  public ref float HitHeading {
    get => ref _Handle.AsRef<float>(_HitHeadingOffset);
  }
  private static readonly nint _HitBodyPartOffset = Schema.GetOffset(0xC7614AAB0CA9863B);

  public ref int HitBodyPart {
    get => ref _Handle.AsRef<int>(_HitBodyPartOffset);
  }
  private static readonly nint _TotalBulletForceOffset = Schema.GetOffset(0xC7614AAB1BA998B0);

  public ref Vector TotalBulletForce {
    get => ref _Handle.AsRef<Vector>(_TotalBulletForceOffset);
  }
  private static readonly nint _WaitForNoAttackOffset = Schema.GetOffset(0xC7614AABC3DEC2A0);

  public ref bool WaitForNoAttack {
    get => ref _Handle.AsRef<bool>(_WaitForNoAttackOffset);
  }
  private static readonly nint _IgnoreLadderJumpTimeOffset = Schema.GetOffset(0xC7614AABC0824DB6);

  public ref float IgnoreLadderJumpTime {
    get => ref _Handle.AsRef<float>(_IgnoreLadderJumpTimeOffset);
  }
  private static readonly nint _KilledByHeadshotOffset = Schema.GetOffset(0xC7614AABEF3D732B);

  public ref bool KilledByHeadshot {
    get => ref _Handle.AsRef<bool>(_KilledByHeadshotOffset);
  }
  private static readonly nint _LastHitBoxOffset = Schema.GetOffset(0xC7614AAB9B4C64DB);

  public ref int LastHitBox {
    get => ref _Handle.AsRef<int>(_LastHitBoxOffset);
  }
  private static readonly nint _BotOffset = Schema.GetOffset(0xC7614AAB172AF0B4);

  public CCSBot? Bot {
    get {
      var ptr = _Handle.Read<nint>(_BotOffset);
      return ptr.IsValidPtr() ? new CCSBotImpl(ptr) : null;
    }
  }
  private static readonly nint _BotAllowActiveOffset = Schema.GetOffset(0xC7614AAB673BB7CD);

  public ref bool BotAllowActive {
    get => ref _Handle.AsRef<bool>(_BotAllowActiveOffset);
  }
  private static readonly nint _ThirdPersonHeadingOffset = Schema.GetOffset(0xC7614AABCE47A2A7);

  public ref QAngle ThirdPersonHeading {
    get => ref _Handle.AsRef<QAngle>(_ThirdPersonHeadingOffset);
  }
  private static readonly nint _SlopeDropOffsetOffset = Schema.GetOffset(0xC7614AABFC6CDBF0);

  public ref float SlopeDropOffset {
    get => ref _Handle.AsRef<float>(_SlopeDropOffsetOffset);
  }
  private static readonly nint _SlopeDropHeightOffset = Schema.GetOffset(0xC7614AABD77D930C);

  public ref float SlopeDropHeight {
    get => ref _Handle.AsRef<float>(_SlopeDropHeightOffset);
  }
  private static readonly nint _HeadConstraintOffsetOffset = Schema.GetOffset(0xC7614AABADDDE147);

  public ref Vector HeadConstraintOffset {
    get => ref _Handle.AsRef<Vector>(_HeadConstraintOffsetOffset);
  }
  private static readonly nint _LastPickupPriorityOffset = Schema.GetOffset(0xC7614AAB9D89E5E9);

  public ref int LastPickupPriority {
    get => ref _Handle.AsRef<int>(_LastPickupPriorityOffset);
  }
  private static readonly nint _LastPickupPriorityTimeOffset = Schema.GetOffset(0xC7614AABF154FBF6);

  public ref float LastPickupPriorityTime {
    get => ref _Handle.AsRef<float>(_LastPickupPriorityTimeOffset);
  }
  private static readonly nint _ArmorValueOffset = Schema.GetOffset(0xC7614AAB8937152D);

  public ref int ArmorValue {
    get => ref _Handle.AsRef<int>(_ArmorValueOffset);
  }
  private static readonly nint _CurrentEquipmentValueOffset = Schema.GetOffset(0xC7614AABECE8502A);

  public ref ushort CurrentEquipmentValue {
    get => ref _Handle.AsRef<ushort>(_CurrentEquipmentValueOffset);
  }
  private static readonly nint _RoundStartEquipmentValueOffset = Schema.GetOffset(0xC7614AAB498A2F2B);

  public ref ushort RoundStartEquipmentValue {
    get => ref _Handle.AsRef<ushort>(_RoundStartEquipmentValueOffset);
  }
  private static readonly nint _FreezetimeEndEquipmentValueOffset = Schema.GetOffset(0xC7614AAB84CBC7A4);

  public ref ushort FreezetimeEndEquipmentValue {
    get => ref _Handle.AsRef<ushort>(_FreezetimeEndEquipmentValueOffset);
  }
  private static readonly nint _LastWeaponFireUsercmdOffset = Schema.GetOffset(0xC7614AABBCBC952D);

  public ref int LastWeaponFireUsercmd {
    get => ref _Handle.AsRef<int>(_LastWeaponFireUsercmdOffset);
  }
  private static readonly nint _IsSpawningOffset = Schema.GetOffset(0xC7614AAB8686DDE0);

  public ref bool IsSpawning {
    get => ref _Handle.AsRef<bool>(_IsSpawningOffset);
  }
  private static readonly nint _DeathFlagsOffset = Schema.GetOffset(0xC7614AAB5C202E41);

  public ref int DeathFlags {
    get => ref _Handle.AsRef<int>(_DeathFlagsOffset);
  }
  private static readonly nint _HasDeathInfoOffset = Schema.GetOffset(0xC7614AAB71E17F33);

  public ref bool HasDeathInfo {
    get => ref _Handle.AsRef<bool>(_HasDeathInfoOffset);
  }
  private static readonly nint _DeathInfoTimeOffset = Schema.GetOffset(0xC7614AAB794C7D56);

  public ref float DeathInfoTime {
    get => ref _Handle.AsRef<float>(_DeathInfoTimeOffset);
  }
  private static readonly nint _DeathInfoOriginOffset = Schema.GetOffset(0xC7614AAB05B549A7);

  public ref Vector DeathInfoOrigin {
    get => ref _Handle.AsRef<Vector>(_DeathInfoOriginOffset);
  }
  public ISchemaFixedArray<uint> PlayerPatchEconIndices {
    get => new SchemaFixedArray<uint>(_Handle, 0xC7614AABECA447BC, 5, 4, 4);
  }
  private static readonly nint _GunGameImmunityColorOffset = Schema.GetOffset(0xC7614AAB5C81D4A0);

  public ref Color GunGameImmunityColor {
    get => ref _Handle.AsRef<Color>(_GunGameImmunityColorOffset);
  }
  private static readonly nint _GrenadeParameterStashTimeOffset = Schema.GetOffset(0xC7614AAB86725FE0);

  public GameTime_t GrenadeParameterStashTime {
    get => new GameTime_tImpl(_Handle + _GrenadeParameterStashTimeOffset);
  }
  private static readonly nint _GrenadeParametersStashedOffset = Schema.GetOffset(0xC7614AAB0DC90C1F);

  public ref bool GrenadeParametersStashed {
    get => ref _Handle.AsRef<bool>(_GrenadeParametersStashedOffset);
  }
  private static readonly nint _StashedShootAnglesOffset = Schema.GetOffset(0xC7614AABBD5D41B8);

  public ref QAngle StashedShootAngles {
    get => ref _Handle.AsRef<QAngle>(_StashedShootAnglesOffset);
  }
  private static readonly nint _StashedGrenadeThrowPositionOffset = Schema.GetOffset(0xC7614AABCC07E25A);

  public ref Vector StashedGrenadeThrowPosition {
    get => ref _Handle.AsRef<Vector>(_StashedGrenadeThrowPositionOffset);
  }
  private static readonly nint _StashedVelocityOffset = Schema.GetOffset(0xC7614AAB577972A4);

  public ref Vector StashedVelocity {
    get => ref _Handle.AsRef<Vector>(_StashedVelocityOffset);
  }
  public ISchemaFixedArray<QAngle> ShootAngleHistory {
    get => new SchemaFixedArray<QAngle>(_Handle, 0xC7614AABE9EFCFCF, 2, 12, 4);
  }
  public ISchemaFixedArray<Vector> ThrowPositionHistory {
    get => new SchemaFixedArray<Vector>(_Handle, 0xC7614AAB35A0837C, 2, 12, 4);
  }
  public ISchemaFixedArray<Vector> VelocityHistory {
    get => new SchemaFixedArray<Vector>(_Handle, 0xC7614AAB24AFD9B2, 2, 12, 4);
  }
  private static readonly nint _PredictedDamageTagsOffset = Schema.GetOffset(0xC7614AAB2CCF5943);

  public ref CUtlVector<PredictedDamageTag_t> PredictedDamageTags {
    get => ref _Handle.AsRef<CUtlVector<PredictedDamageTag_t>>(_PredictedDamageTagsOffset);
  }
  private static readonly nint _HighestAppliedDamageTagTickOffset = Schema.GetOffset(0xC7614AAB1703141A);

  public ref int HighestAppliedDamageTagTick {
    get => ref _Handle.AsRef<int>(_HighestAppliedDamageTagTickOffset);
  }
  private static readonly nint _CommittingSuicideOnTeamChangeOffset = Schema.GetOffset(0xC7614AAB353E5ADC);

  public ref bool CommittingSuicideOnTeamChange {
    get => ref _Handle.AsRef<bool>(_CommittingSuicideOnTeamChangeOffset);
  }
  private static readonly nint _WasNotKilledNaturallyOffset = Schema.GetOffset(0xC7614AAB538DBAE4);

  public ref bool WasNotKilledNaturally {
    get => ref _Handle.AsRef<bool>(_WasNotKilledNaturallyOffset);
  }
  private static readonly nint _ImmuneToGunGameDamageTimeOffset = Schema.GetOffset(0xC7614AAB8305FCCB);

  public GameTime_t ImmuneToGunGameDamageTime {
    get => new GameTime_tImpl(_Handle + _ImmuneToGunGameDamageTimeOffset);
  }
  private static readonly nint _GunGameImmunityOffset = Schema.GetOffset(0xC7614AAB9C15080D);

  public ref bool GunGameImmunity {
    get => ref _Handle.AsRef<bool>(_GunGameImmunityOffset);
  }
  private static readonly nint _MolotovDamageTimeOffset = Schema.GetOffset(0xC7614AABD2CDBE21);

  public ref float MolotovDamageTime {
    get => ref _Handle.AsRef<float>(_MolotovDamageTimeOffset);
  }
  private static readonly nint _EyeAnglesOffset = Schema.GetOffset(0xC7614AAB4EE662AC);

  public ref QAngle EyeAngles {
    get => ref _Handle.AsRef<QAngle>(_EyeAnglesOffset);
  }

  public void BulletServicesUpdated() {
    Schema.Update(_Handle, 0xC7614AAB8E2741BB);
  }
  public void HostageServicesUpdated() {
    Schema.Update(_Handle, 0xC7614AAB63EBD1D8);
  }
  public void BuyServicesUpdated() {
    Schema.Update(_Handle, 0xC7614AAB807A410D);
  }
  public void ActionTrackingServicesUpdated() {
    Schema.Update(_Handle, 0xC7614AABB8174144);
  }
  public void HasFemaleVoiceUpdated() {
    Schema.Update(_Handle, 0xC7614AAB7E7752FF);
  }
  public void LastPlaceNameUpdated() {
    Schema.Update(_Handle, 0xC7614AAB4C28E3A0);
  }
  public void InBuyZoneUpdated() {
    Schema.Update(_Handle, 0xC7614AAB3AC1BD10);
  }
  public void InHostageRescueZoneUpdated() {
    Schema.Update(_Handle, 0xC7614AABBFE04B90);
  }
  public void InBombZoneUpdated() {
    Schema.Update(_Handle, 0xC7614AABCB89478C);
  }
  public void RetakesOfferingUpdated() {
    Schema.Update(_Handle, 0xC7614AABD729481D);
  }
  public void RetakesOfferingCardUpdated() {
    Schema.Update(_Handle, 0xC7614AAB3C338797);
  }
  public void RetakesHasDefuseKitUpdated() {
    Schema.Update(_Handle, 0xC7614AABEFC4B30A);
  }
  public void RetakesMVPLastRoundUpdated() {
    Schema.Update(_Handle, 0xC7614AABC87BFEF3);
  }
  public void RetakesMVPBoostItemUpdated() {
    Schema.Update(_Handle, 0xC7614AABEC8D220C);
  }
  public void RetakesMVPBoostExtraUtilityUpdated() {
    Schema.Update(_Handle, 0xC7614AABADA37062);
  }
  public void HealthShotBoostExpirationTimeUpdated() {
    Schema.Update(_Handle, 0xC7614AABEC487ACC);
  }
  public void AimPunchAngleUpdated() {
    Schema.Update(_Handle, 0xC7614AAB1E948CB9);
  }
  public void AimPunchAngleVelUpdated() {
    Schema.Update(_Handle, 0xC7614AABB30DE0EC);
  }
  public void AimPunchTickBaseUpdated() {
    Schema.Update(_Handle, 0xC7614AABB9C874A2);
  }
  public void AimPunchTickFractionUpdated() {
    Schema.Update(_Handle, 0xC7614AAB90BE3E69);
  }
  public void IsBuyMenuOpenUpdated() {
    Schema.Update(_Handle, 0xC7614AABFBCDD8EC);
  }
  public void TimeOfLastInjuryUpdated() {
    Schema.Update(_Handle, 0xC7614AABD7B4663C);
  }
  public void NextSprayDecalTimeUpdated() {
    Schema.Update(_Handle, 0xC7614AAB53790011);
  }
  public void RagdollDamageBoneUpdated() {
    Schema.Update(_Handle, 0xC7614AAB31F4732F);
  }
  public void RagdollDamageForceUpdated() {
    Schema.Update(_Handle, 0xC7614AAB7FBF68CC);
  }
  public void RagdollDamagePositionUpdated() {
    Schema.Update(_Handle, 0xC7614AAB29671362);
  }
  public void RagdollDamageWeaponNameUpdated() {
    Schema.Update(_Handle, 0xC7614AABDAAFA519);
  }
  public void RagdollDamageHeadshotUpdated() {
    Schema.Update(_Handle, 0xC7614AAB324979E7);
  }
  public void RagdollServerOriginUpdated() {
    Schema.Update(_Handle, 0xC7614AAB24991D61);
  }
  public void EconGlovesUpdated() {
    Schema.Update(_Handle, 0xC7614AAB58DEE8E2);
  }
  public void EconGlovesChangedUpdated() {
    Schema.Update(_Handle, 0xC7614AAB617F6ACA);
  }
  public void DeathEyeAnglesUpdated() {
    Schema.Update(_Handle, 0xC7614AAB6F21BE57);
  }
  public void LeftHandedUpdated() {
    Schema.Update(_Handle, 0xC7614AAB63906F18);
  }
  public void SwitchedHandednessTimeUpdated() {
    Schema.Update(_Handle, 0xC7614AAB40B8D9FE);
  }
  public void ViewmodelOffsetXUpdated() {
    Schema.Update(_Handle, 0xC7614AAB6890E2BC);
  }
  public void ViewmodelOffsetYUpdated() {
    Schema.Update(_Handle, 0xC7614AAB6990E44F);
  }
  public void ViewmodelOffsetZUpdated() {
    Schema.Update(_Handle, 0xC7614AAB6A90E5E2);
  }
  public void ViewmodelFOVUpdated() {
    Schema.Update(_Handle, 0xC7614AAB08EEBF76);
  }
  public void IsWalkingUpdated() {
    Schema.Update(_Handle, 0xC7614AAB9441C788);
  }
  public void LastKillerIndexUpdated() {
    Schema.Update(_Handle, 0xC7614AABA4700326);
  }
  public void EntitySpottedStateUpdated() {
    Schema.Update(_Handle, 0xC7614AAB032B547C);
  }
  public void IsScopedUpdated() {
    Schema.Update(_Handle, 0xC7614AABF3E9A9ED);
  }
  public void ResumeZoomUpdated() {
    Schema.Update(_Handle, 0xC7614AABB4707FB1);
  }
  public void IsDefusingUpdated() {
    Schema.Update(_Handle, 0xC7614AAB5BDAECC0);
  }
  public void IsGrabbingHostageUpdated() {
    Schema.Update(_Handle, 0xC7614AAB43AC7BEA);
  }
  public void BlockingUseActionInProgressUpdated() {
    Schema.Update(_Handle, 0xC7614AAB6B0B2AC0);
  }
  public void EmitSoundTimeUpdated() {
    Schema.Update(_Handle, 0xC7614AABC6FA84FA);
  }
  public void InNoDefuseAreaUpdated() {
    Schema.Update(_Handle, 0xC7614AAB10C6FF02);
  }
  public void WhichBombZoneUpdated() {
    Schema.Update(_Handle, 0xC7614AAB0D69FABC);
  }
  public void ShotsFiredUpdated() {
    Schema.Update(_Handle, 0xC7614AABFE518C17);
  }
  public void FlinchStackUpdated() {
    Schema.Update(_Handle, 0xC7614AAB36439B97);
  }
  public void VelocityModifierUpdated() {
    Schema.Update(_Handle, 0xC7614AAB7AC97631);
  }
  public void HitHeadingUpdated() {
    Schema.Update(_Handle, 0xC7614AAB09713C4E);
  }
  public void HitBodyPartUpdated() {
    Schema.Update(_Handle, 0xC7614AAB0CA9863B);
  }
  public void WaitForNoAttackUpdated() {
    Schema.Update(_Handle, 0xC7614AABC3DEC2A0);
  }
  public void KilledByHeadshotUpdated() {
    Schema.Update(_Handle, 0xC7614AABEF3D732B);
  }
  public void ThirdPersonHeadingUpdated() {
    Schema.Update(_Handle, 0xC7614AABCE47A2A7);
  }
  public void SlopeDropOffsetUpdated() {
    Schema.Update(_Handle, 0xC7614AABFC6CDBF0);
  }
  public void SlopeDropHeightUpdated() {
    Schema.Update(_Handle, 0xC7614AABD77D930C);
  }
  public void HeadConstraintOffsetUpdated() {
    Schema.Update(_Handle, 0xC7614AABADDDE147);
  }
  public void ArmorValueUpdated() {
    Schema.Update(_Handle, 0xC7614AAB8937152D);
  }
  public void CurrentEquipmentValueUpdated() {
    Schema.Update(_Handle, 0xC7614AABECE8502A);
  }
  public void RoundStartEquipmentValueUpdated() {
    Schema.Update(_Handle, 0xC7614AAB498A2F2B);
  }
  public void FreezetimeEndEquipmentValueUpdated() {
    Schema.Update(_Handle, 0xC7614AAB84CBC7A4);
  }
  public void PlayerPatchEconIndicesUpdated() {
    Schema.Update(_Handle, 0xC7614AABECA447BC);
  }
  public void GunGameImmunityColorUpdated() {
    Schema.Update(_Handle, 0xC7614AAB5C81D4A0);
  }
  public void PredictedDamageTagsUpdated() {
    Schema.Update(_Handle, 0xC7614AAB2CCF5943);
  }
  public void ImmuneToGunGameDamageTimeUpdated() {
    Schema.Update(_Handle, 0xC7614AAB8305FCCB);
  }
  public void GunGameImmunityUpdated() {
    Schema.Update(_Handle, 0xC7614AAB9C15080D);
  }
  public void MolotovDamageTimeUpdated() {
    Schema.Update(_Handle, 0xC7614AABD2CDBE21);
  }
  public void EyeAnglesUpdated() {
    Schema.Update(_Handle, 0xC7614AAB4EE662AC);
  }
}