// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CCSPlayer_UseServicesImpl : CPlayer_UseServicesImpl, CCSPlayer_UseServices {

  public CCSPlayer_UseServicesImpl(nint handle) : base(handle) {
  }

  private static readonly nint _LastKnownUseEntityOffset = Schema.GetOffset(0xE5F718912806F946);

  public ref CHandle<CBaseEntity> LastKnownUseEntity {
    get => ref _Handle.AsRef<CHandle<CBaseEntity>>(_LastKnownUseEntityOffset);
  }
  private static readonly nint _LastUseTimeStampOffset = Schema.GetOffset(0xE5F7189104BF376E);

  public GameTime_t LastUseTimeStamp {
    get => new GameTime_tImpl(_Handle + _LastUseTimeStampOffset);
  }
  private static readonly nint _TimeLastUsedWindowOffset = Schema.GetOffset(0xE5F7189165762AEB);

  public GameTime_t TimeLastUsedWindow {
    get => new GameTime_tImpl(_Handle + _TimeLastUsedWindowOffset);
  }


}