// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CCycleControlClipUpdateNodeImpl : CLeafUpdateNodeImpl, CCycleControlClipUpdateNode {

  public CCycleControlClipUpdateNodeImpl(nint handle) : base(handle) {
  }

  private static readonly nint _TagsOffset = Schema.GetOffset(0x57FEB5AAB46C8540);

  public ref CUtlVector<TagSpan_t> Tags {
    get => ref _Handle.AsRef<CUtlVector<TagSpan_t>>(_TagsOffset);
  }
  private static readonly nint _SequenceOffset = Schema.GetOffset(0x57FEB5AAE0A0598E);

  public HSequence Sequence {
    get => new HSequenceImpl(_Handle + _SequenceOffset);
  }
  private static readonly nint _DurationOffset = Schema.GetOffset(0x57FEB5AA3D9FF5AD);

  public ref float Duration {
    get => ref _Handle.AsRef<float>(_DurationOffset);
  }
  private static readonly nint _ValueSourceOffset = Schema.GetOffset(0x57FEB5AAD4D5B6B7);

  public ref AnimValueSource ValueSource {
    get => ref _Handle.AsRef<AnimValueSource>(_ValueSourceOffset);
  }
  private static readonly nint _ParamIndexOffset = Schema.GetOffset(0x57FEB5AA61990A86);

  public CAnimParamHandle ParamIndex {
    get => new CAnimParamHandleImpl(_Handle + _ParamIndexOffset);
  }
  private static readonly nint _LockWhenWaningOffset = Schema.GetOffset(0x57FEB5AAEED48004);

  public ref bool LockWhenWaning {
    get => ref _Handle.AsRef<bool>(_LockWhenWaningOffset);
  }


}