// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CDirectPlaybackTagDataImpl : SchemaClass, CDirectPlaybackTagData {

  public CDirectPlaybackTagDataImpl(nint handle) : base(handle) {
  }

  private static readonly nint _SequenceNameOffset = Schema.GetOffset(0xAADCE162B4A24CB);

  public string SequenceName {
    get {
      var ptr = _Handle.Read<nint>(_SequenceNameOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _SequenceNameOffset, value);
  } 
  private static readonly nint _TagsOffset = Schema.GetOffset(0xAADCE16B46C8540);

  public ref CUtlVector<TagSpan_t> Tags {
    get => ref _Handle.AsRef<CUtlVector<TagSpan_t>>(_TagsOffset);
  }


}