// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CEconItemViewImpl : IEconItemInterfaceImpl, CEconItemView {

  public CEconItemViewImpl(nint handle) : base(handle) {
  }

  private static readonly nint _ItemDefinitionIndexOffset = Schema.GetOffset(0xE1A93F25A2CCB41A);

  public ref ushort ItemDefinitionIndex {
    get => ref _Handle.AsRef<ushort>(_ItemDefinitionIndexOffset);
  }
  private static readonly nint _EntityQualityOffset = Schema.GetOffset(0xE1A93F256A67D4C4);

  public ref int EntityQuality {
    get => ref _Handle.AsRef<int>(_EntityQualityOffset);
  }
  private static readonly nint _EntityLevelOffset = Schema.GetOffset(0xE1A93F2555EF3B5F);

  public ref uint EntityLevel {
    get => ref _Handle.AsRef<uint>(_EntityLevelOffset);
  }
  private static readonly nint _ItemIDOffset = Schema.GetOffset(0xE1A93F2534B55816);

  public ref ulong ItemID {
    get => ref _Handle.AsRef<ulong>(_ItemIDOffset);
  }
  private static readonly nint _ItemIDHighOffset = Schema.GetOffset(0xE1A93F25373EE446);

  public ref uint ItemIDHigh {
    get => ref _Handle.AsRef<uint>(_ItemIDHighOffset);
  }
  private static readonly nint _ItemIDLowOffset = Schema.GetOffset(0xE1A93F250DF29C2C);

  public ref uint ItemIDLow {
    get => ref _Handle.AsRef<uint>(_ItemIDLowOffset);
  }
  private static readonly nint _AccountIDOffset = Schema.GetOffset(0xE1A93F25C65DE986);

  public ref uint AccountID {
    get => ref _Handle.AsRef<uint>(_AccountIDOffset);
  }
  private static readonly nint _InventoryPositionOffset = Schema.GetOffset(0xE1A93F2592F42873);

  public ref uint InventoryPosition {
    get => ref _Handle.AsRef<uint>(_InventoryPositionOffset);
  }
  private static readonly nint _InitializedOffset = Schema.GetOffset(0xE1A93F250710ABDD);

  public ref bool Initialized {
    get => ref _Handle.AsRef<bool>(_InitializedOffset);
  }
  private static readonly nint _AttributeListOffset = Schema.GetOffset(0xE1A93F25EF065D97);

  public CAttributeList AttributeList {
    get => new CAttributeListImpl(_Handle + _AttributeListOffset);
  }
  private static readonly nint _NetworkedDynamicAttributesOffset = Schema.GetOffset(0xE1A93F25B576449C);

  public CAttributeList NetworkedDynamicAttributes {
    get => new CAttributeListImpl(_Handle + _NetworkedDynamicAttributesOffset);
  }
  private static readonly nint _CustomNameOffset = Schema.GetOffset(0xE1A93F25AFD12EE8);

  public string CustomName {
    get {
      var ptr = _Handle + _CustomNameOffset;
      return Schema.GetString(ptr);
    }
    set => Schema.SetFixedString(_Handle, _CustomNameOffset, value, 161);
  } 
  private static readonly nint _CustomNameOverrideOffset = Schema.GetOffset(0xE1A93F25A74A6ED8);

  public string CustomNameOverride {
    get {
      var ptr = _Handle + _CustomNameOverrideOffset;
      return Schema.GetString(ptr);
    }
    set => Schema.SetFixedString(_Handle, _CustomNameOverrideOffset, value, 161);
  } 

  public void ItemDefinitionIndexUpdated() {
    Schema.Update(_Handle, 0xE1A93F25A2CCB41A);
  }
  public void EntityQualityUpdated() {
    Schema.Update(_Handle, 0xE1A93F256A67D4C4);
  }
  public void EntityLevelUpdated() {
    Schema.Update(_Handle, 0xE1A93F2555EF3B5F);
  }
  public void ItemIDHighUpdated() {
    Schema.Update(_Handle, 0xE1A93F25373EE446);
  }
  public void ItemIDLowUpdated() {
    Schema.Update(_Handle, 0xE1A93F250DF29C2C);
  }
  public void AccountIDUpdated() {
    Schema.Update(_Handle, 0xE1A93F25C65DE986);
  }
  public void InventoryPositionUpdated() {
    Schema.Update(_Handle, 0xE1A93F2592F42873);
  }
  public void InitializedUpdated() {
    Schema.Update(_Handle, 0xE1A93F250710ABDD);
  }
  public void AttributeListUpdated() {
    Schema.Update(_Handle, 0xE1A93F25EF065D97);
  }
  public void NetworkedDynamicAttributesUpdated() {
    Schema.Update(_Handle, 0xE1A93F25B576449C);
  }
  public void CustomNameUpdated() {
    Schema.Update(_Handle, 0xE1A93F25AFD12EE8);
  }
}