// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CEntityComponentHelperImpl : SchemaClass, CEntityComponentHelper {

  public CEntityComponentHelperImpl(nint handle) : base(handle) {
  }

  private static readonly nint _FlagsOffset = Schema.GetOffset(0x714DB384DC74A14C);

  public ref uint Flags {
    get => ref _Handle.AsRef<uint>(_FlagsOffset);
  }
  private static readonly nint _InfoOffset = Schema.GetOffset(0x714DB3840F0BFD1B);

  public EntComponentInfo_t? Info {
    get {
      var ptr = _Handle.Read<nint>(_InfoOffset);
      return ptr.IsValidPtr() ? new EntComponentInfo_tImpl(ptr) : null;
    }
  }
  private static readonly nint _PriorityOffset = Schema.GetOffset(0x714DB384E7EFB335);

  public ref int Priority {
    get => ref _Handle.AsRef<int>(_PriorityOffset);
  }
  private static readonly nint _NextOffset = Schema.GetOffset(0x714DB38432B11E0E);

  public CEntityComponentHelper? Next {
    get {
      var ptr = _Handle.Read<nint>(_NextOffset);
      return ptr.IsValidPtr() ? new CEntityComponentHelperImpl(ptr) : null;
    }
  }


}