// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CEnvTiltImpl : CPointEntityImpl, CEnvTilt {

  public CEnvTiltImpl(nint handle) : base(handle) {
  }

  private static readonly nint _DurationOffset = Schema.GetOffset(0xF90425169879A98D);

  public ref float Duration {
    get => ref _Handle.AsRef<float>(_DurationOffset);
  }
  private static readonly nint _RadiusOffset = Schema.GetOffset(0xF90425167C5B0533);

  public ref float Radius {
    get => ref _Handle.AsRef<float>(_RadiusOffset);
  }
  private static readonly nint _TiltTimeOffset = Schema.GetOffset(0xF9042516B3956BFF);

  public ref float TiltTime {
    get => ref _Handle.AsRef<float>(_TiltTimeOffset);
  }
  private static readonly nint _StopTimeOffset = Schema.GetOffset(0xF90425166BFFEDC4);

  public GameTime_t StopTime {
    get => new GameTime_tImpl(_Handle + _StopTimeOffset);
  }


}