// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CFollowTargetUpdateNodeImpl : CUnaryUpdateNodeImpl, CFollowTargetUpdateNode {

  public CFollowTargetUpdateNodeImpl(nint handle) : base(handle) {
  }

  private static readonly nint _OpFixedDataOffset = Schema.GetOffset(0x2A45E9CB6960AF8C);

  public FollowTargetOpFixedSettings_t OpFixedData {
    get => new FollowTargetOpFixedSettings_tImpl(_Handle + _OpFixedDataOffset);
  }
  private static readonly nint _ParameterPositionOffset = Schema.GetOffset(0x2A45E9CBDA71CD41);

  public CAnimParamHandle ParameterPosition {
    get => new CAnimParamHandleImpl(_Handle + _ParameterPositionOffset);
  }
  private static readonly nint _ParameterOrientationOffset = Schema.GetOffset(0x2A45E9CB1320E9C8);

  public CAnimParamHandle ParameterOrientation {
    get => new CAnimParamHandleImpl(_Handle + _ParameterOrientationOffset);
  }


}