// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CFootstepControlImpl : CBaseTriggerImpl, CFootstepControl {

  public CFootstepControlImpl(nint handle) : base(handle) {
  }

  private static readonly nint _SourceOffset = Schema.GetOffset(0x85B34315D0835C78);

  public string Source {
    get {
      var ptr = _Handle.Read<nint>(_SourceOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _SourceOffset, value);
  } 
  private static readonly nint _DestinationOffset = Schema.GetOffset(0x85B343156E5C12DF);

  public string Destination {
    get {
      var ptr = _Handle.Read<nint>(_DestinationOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _DestinationOffset, value);
  } 

  public void SourceUpdated() {
    Schema.Update(_Handle, 0x85B34315D0835C78);
  }
  public void DestinationUpdated() {
    Schema.Update(_Handle, 0x85B343156E5C12DF);
  }
}