// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CFootPinningUpdateNodeImpl : CUnaryUpdateNodeImpl, CFootPinningUpdateNode {

  public CFootPinningUpdateNodeImpl(nint handle) : base(handle) {
  }

  private static readonly nint _PoseOpFixedDataOffset = Schema.GetOffset(0x9D0C68166EC45627);

  public FootPinningPoseOpFixedData_t PoseOpFixedData {
    get => new FootPinningPoseOpFixedData_tImpl(_Handle + _PoseOpFixedDataOffset);
  }
  private static readonly nint _TimingSourceOffset = Schema.GetOffset(0x9D0C68164D5A2DD7);

  public ref FootPinningTimingSource TimingSource {
    get => ref _Handle.AsRef<FootPinningTimingSource>(_TimingSourceOffset);
  }
  private static readonly nint _ParamsOffset = Schema.GetOffset(0x9D0C6816640EA8F3);

  public ref CUtlVector<CAnimParamHandle> Params {
    get => ref _Handle.AsRef<CUtlVector<CAnimParamHandle>>(_ParamsOffset);
  }
  private static readonly nint _ResetChildOffset = Schema.GetOffset(0x9D0C681665CC88B6);

  public ref bool ResetChild {
    get => ref _Handle.AsRef<bool>(_ResetChildOffset);
  }


}