// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CFuseProgramImpl : SchemaClass, CFuseProgram {

  public CFuseProgramImpl(nint handle) : base(handle) {
  }

  private static readonly nint _ProgramBufferOffset = Schema.GetOffset(0x81E69119349962E1);

  public ref CUtlVector<byte> ProgramBuffer {
    get => ref _Handle.AsRef<CUtlVector<byte>>(_ProgramBufferOffset);
  }
  private static readonly nint _VariablesReadOffset = Schema.GetOffset(0x81E691194C160BEA);

  public ref CUtlVector<FuseVariableIndex_t> VariablesRead {
    get => ref _Handle.AsRef<CUtlVector<FuseVariableIndex_t>>(_VariablesReadOffset);
  }
  private static readonly nint _VariablesWrittenOffset = Schema.GetOffset(0x81E69119E9491C49);

  public ref CUtlVector<FuseVariableIndex_t> VariablesWritten {
    get => ref _Handle.AsRef<CUtlVector<FuseVariableIndex_t>>(_VariablesWrittenOffset);
  }
  private static readonly nint _MaxTempVarsUsedOffset = Schema.GetOffset(0x81E69119981A1518);

  public ref int MaxTempVarsUsed {
    get => ref _Handle.AsRef<int>(_MaxTempVarsUsedOffset);
  }


}