// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CGameGibManagerImpl : CBaseEntityImpl, CGameGibManager {

  public CGameGibManagerImpl(nint handle) : base(handle) {
  }

  private static readonly nint _AllowNewGibsOffset = Schema.GetOffset(0x1068CB09FD80F507);

  public ref bool AllowNewGibs {
    get => ref _Handle.AsRef<bool>(_AllowNewGibsOffset);
  }
  private static readonly nint _CurrentMaxPiecesOffset = Schema.GetOffset(0x1068CB0999B0D602);

  public ref int CurrentMaxPieces {
    get => ref _Handle.AsRef<int>(_CurrentMaxPiecesOffset);
  }
  private static readonly nint _MaxPiecesOffset = Schema.GetOffset(0x1068CB092DDFB63D);

  public ref int MaxPieces {
    get => ref _Handle.AsRef<int>(_MaxPiecesOffset);
  }
  private static readonly nint _LastFrameOffset = Schema.GetOffset(0x1068CB09F0B58C21);

  public ref int LastFrame {
    get => ref _Handle.AsRef<int>(_LastFrameOffset);
  }


}