// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CGameSceneNodeHandleImpl : SchemaClass, CGameSceneNodeHandle {

  public CGameSceneNodeHandleImpl(nint handle) : base(handle) {
  }

  private static readonly nint _OwnerOffset = Schema.GetOffset(0x9A961FAF6D89572);

  public ref CHandle<CEntityInstance> Owner {
    get => ref _Handle.AsRef<CHandle<CEntityInstance>>(_OwnerOffset);
  }
  private static readonly nint _NameOffset = Schema.GetOffset(0x9A961FA4D8F5786);

  public ref CUtlStringToken Name {
    get => ref _Handle.AsRef<CUtlStringToken>(_NameOffset);
  }

  public void OwnerUpdated() {
    Schema.Update(_Handle, 0x9A961FAF6D89572);
  }
  public void NameUpdated() {
    Schema.Update(_Handle, 0x9A961FA4D8F5786);
  }
}