// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CGunTargetImpl : CBaseToggleImpl, CGunTarget {

  public CGunTargetImpl(nint handle) : base(handle) {
  }

  private static readonly nint _OnOffset = Schema.GetOffset(0x4CB42969DEB2AE70);

  public ref bool On {
    get => ref _Handle.AsRef<bool>(_OnOffset);
  }
  private static readonly nint _TargetEntOffset = Schema.GetOffset(0x4CB429692DD292D7);

  public ref CHandle<CBaseEntity> TargetEnt {
    get => ref _Handle.AsRef<CHandle<CBaseEntity>>(_TargetEntOffset);
  }
  private static readonly nint _OnDeathOffset = Schema.GetOffset(0x4CB429696F756BD2);

  public CEntityIOOutput OnDeath {
    get => new CEntityIOOutputImpl(_Handle + _OnDeathOffset);
  }


}