// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class ChainToSolveData_tImpl : SchemaClass, ChainToSolveData_t {

  public ChainToSolveData_tImpl(nint handle) : base(handle) {
  }

  private static readonly nint _ChainIndexOffset = Schema.GetOffset(0x87A241BDA34589B6);

  public ref int ChainIndex {
    get => ref _Handle.AsRef<int>(_ChainIndexOffset);
  }
  private static readonly nint _SolverSettingsOffset = Schema.GetOffset(0x87A241BDE19D8233);

  public IKSolverSettings_t SolverSettings {
    get => new IKSolverSettings_tImpl(_Handle + _SolverSettingsOffset);
  }
  private static readonly nint _TargetSettingsOffset = Schema.GetOffset(0x87A241BDD6828E35);

  public IKTargetSettings_t TargetSettings {
    get => new IKTargetSettings_tImpl(_Handle + _TargetSettingsOffset);
  }
  private static readonly nint _DebugSettingOffset = Schema.GetOffset(0x87A241BD624CC0B4);

  public ref SolveIKChainAnimNodeDebugSetting DebugSetting {
    get => ref _Handle.AsRef<SolveIKChainAnimNodeDebugSetting>(_DebugSettingOffset);
  }
  private static readonly nint _DebugNormalizedValueOffset = Schema.GetOffset(0x87A241BD0F331460);

  public ref float DebugNormalizedValue {
    get => ref _Handle.AsRef<float>(_DebugNormalizedValueOffset);
  }
  private static readonly nint _DebugOffsetOffset = Schema.GetOffset(0x87A241BD2FF28BBF);

  public ref Vector DebugOffset {
    get => ref _Handle.AsRef<Vector>(_DebugOffsetOffset);
  }


}