// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CHandleTestImpl : CBaseEntityImpl, CHandleTest {

  public CHandleTestImpl(nint handle) : base(handle) {
  }

  private static readonly nint _HandleOffset = Schema.GetOffset(0xCC5023E89D208453);

  public ref CHandle<CBaseEntity> Handle {
    get => ref _Handle.AsRef<CHandle<CBaseEntity>>(_HandleOffset);
  }
  private static readonly nint _SendHandleOffset = Schema.GetOffset(0xCC5023E8EACC8501);

  public ref bool SendHandle {
    get => ref _Handle.AsRef<bool>(_SendHandleOffset);
  }

  public void HandleUpdated() {
    Schema.Update(_Handle, 0xCC5023E89D208453);
  }
  public void SendHandleUpdated() {
    Schema.Update(_Handle, 0xCC5023E8EACC8501);
  }
}