// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CHintMessageImpl : SchemaClass, CHintMessage {

  public CHintMessageImpl(nint handle) : base(handle) {
  }

  private static readonly nint _HintStringOffset = Schema.GetOffset(0x7663729E433E2101);

  public string HintString {
    get {
      var ptr = _Handle.Read<nint>(_HintStringOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _HintStringOffset, value);
  } 
  private static readonly nint _ArgsOffset = Schema.GetOffset(0x7663729E5D6040DC);

  public ref CUtlVector<CString> Args {
    get => ref _Handle.AsRef<CUtlVector<CString>>(_ArgsOffset);
  }
  private static readonly nint _DurationOffset = Schema.GetOffset(0x7663729E3D9FF5AD);

  public ref float Duration {
    get => ref _Handle.AsRef<float>(_DurationOffset);
  }


}