// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CInfoDynamicShadowHintImpl : CPointEntityImpl, CInfoDynamicShadowHint {

  public CInfoDynamicShadowHintImpl(nint handle) : base(handle) {
  }

  private static readonly nint _DisabledOffset = Schema.GetOffset(0x46DDE8EE3A7C5965);

  public ref bool Disabled {
    get => ref _Handle.AsRef<bool>(_DisabledOffset);
  }
  private static readonly nint _RangeOffset = Schema.GetOffset(0x46DDE8EE3FC92844);

  public ref float Range {
    get => ref _Handle.AsRef<float>(_RangeOffset);
  }
  private static readonly nint _ImportanceOffset = Schema.GetOffset(0x46DDE8EE85D7F083);

  public ref int Importance {
    get => ref _Handle.AsRef<int>(_ImportanceOffset);
  }
  private static readonly nint _LightChoiceOffset = Schema.GetOffset(0x46DDE8EED82DFBD8);

  public ref int LightChoice {
    get => ref _Handle.AsRef<int>(_LightChoiceOffset);
  }
  private static readonly nint _LightOffset = Schema.GetOffset(0x46DDE8EEF68359B1);

  public ref CHandle<CBaseEntity> Light {
    get => ref _Handle.AsRef<CHandle<CBaseEntity>>(_LightOffset);
  }


}