// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CItemDefuserImpl : CItemImpl, CItemDefuser {

  public CItemDefuserImpl(nint handle) : base(handle) {
  }

  private static readonly nint _EntitySpottedStateOffset = Schema.GetOffset(0xC9362933032B547C);

  public EntitySpottedState_t EntitySpottedState {
    get => new EntitySpottedState_tImpl(_Handle + _EntitySpottedStateOffset);
  }
  private static readonly nint _SpotRulesOffset = Schema.GetOffset(0xC9362933776CCE44);

  public ref int SpotRules {
    get => ref _Handle.AsRef<int>(_SpotRulesOffset);
  }


}