// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CLogicDistanceCheckImpl : CLogicalEntityImpl, CLogicDistanceCheck {

  public CLogicDistanceCheckImpl(nint handle) : base(handle) {
  }

  private static readonly nint _EntityAOffset = Schema.GetOffset(0x523E7E6D07823CB9);

  public string EntityA {
    get {
      var ptr = _Handle.Read<nint>(_EntityAOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _EntityAOffset, value);
  } 
  private static readonly nint _EntityBOffset = Schema.GetOffset(0x523E7E6D04823800);

  public string EntityB {
    get {
      var ptr = _Handle.Read<nint>(_EntityBOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _EntityBOffset, value);
  } 
  private static readonly nint _Zone1DistanceOffset = Schema.GetOffset(0x523E7E6DFF385A8F);

  public ref float Zone1Distance {
    get => ref _Handle.AsRef<float>(_Zone1DistanceOffset);
  }
  private static readonly nint _Zone2DistanceOffset = Schema.GetOffset(0x523E7E6DE1734A1A);

  public ref float Zone2Distance {
    get => ref _Handle.AsRef<float>(_Zone2DistanceOffset);
  }
  private static readonly nint _InZone1Offset = Schema.GetOffset(0x523E7E6D25378DB3);

  public CEntityIOOutput InZone1 {
    get => new CEntityIOOutputImpl(_Handle + _InZone1Offset);
  }
  private static readonly nint _InZone2Offset = Schema.GetOffset(0x523E7E6D26378F46);

  public CEntityIOOutput InZone2 {
    get => new CEntityIOOutputImpl(_Handle + _InZone2Offset);
  }
  private static readonly nint _InZone3Offset = Schema.GetOffset(0x523E7E6D273790D9);

  public CEntityIOOutput InZone3 {
    get => new CEntityIOOutputImpl(_Handle + _InZone3Offset);
  }


}