// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CMorphConstraintImpl : CBaseConstraintImpl, CMorphConstraint {

  public CMorphConstraintImpl(nint handle) : base(handle) {
  }

  private static readonly nint _TargetMorphOffset = Schema.GetOffset(0xC24859C39FF7D337);

  public string TargetMorph {
    get {
      var ptr = _Handle.Read<nint>(_TargetMorphOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _TargetMorphOffset, value);
  } 
  private static readonly nint _SlaveChannelOffset = Schema.GetOffset(0xC24859C3A439DE4F);

  public ref int SlaveChannel {
    get => ref _Handle.AsRef<int>(_SlaveChannelOffset);
  }
  private static readonly nint _MinOffset = Schema.GetOffset(0xC24859C33B1A5649);

  public ref float Min {
    get => ref _Handle.AsRef<float>(_MinOffset);
  }
  private static readonly nint _MaxOffset = Schema.GetOffset(0xC24859C32D06B887);

  public ref float Max {
    get => ref _Handle.AsRef<float>(_MaxOffset);
  }


}