// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CMotionGraphImpl : SchemaClass, CMotionGraph {

  public CMotionGraphImpl(nint handle) : base(handle) {
  }

  private static readonly nint _ParamSpansOffset = Schema.GetOffset(0xA24822FCDAC91553);

  public CParamSpanUpdater ParamSpans {
    get => new CParamSpanUpdaterImpl(_Handle + _ParamSpansOffset);
  }
  private static readonly nint _TagsOffset = Schema.GetOffset(0xA24822FCB46C8540);

  public ref CUtlVector<TagSpan_t> Tags {
    get => ref _Handle.AsRef<CUtlVector<TagSpan_t>>(_TagsOffset);
  }
  private static readonly nint _RootNodeOffset = Schema.GetOffset(0xA24822FC8BB07023);

  public SchemaUntypedField RootNode {
    get => new SchemaUntypedField(_Handle + _RootNodeOffset);
  }
  private static readonly nint _ParameterCountOffset = Schema.GetOffset(0xA24822FC3B0EE24B);

  public ref int ParameterCount {
    get => ref _Handle.AsRef<int>(_ParameterCountOffset);
  }
  private static readonly nint _ConfigStartIndexOffset = Schema.GetOffset(0xA24822FCEB4B0D77);

  public ref int ConfigStartIndex {
    get => ref _Handle.AsRef<int>(_ConfigStartIndexOffset);
  }
  private static readonly nint _ConfigCountOffset = Schema.GetOffset(0xA24822FC16549AD2);

  public ref int ConfigCount {
    get => ref _Handle.AsRef<int>(_ConfigCountOffset);
  }
  private static readonly nint _LoopOffset = Schema.GetOffset(0xA24822FCC668A4CB);

  public ref bool Loop {
    get => ref _Handle.AsRef<bool>(_LoopOffset);
  }


}