// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CMoverPathNodeImpl : CPointEntityImpl, CMoverPathNode {

  public CMoverPathNodeImpl(nint handle) : base(handle) {
  }

  private static readonly nint _InTangentLocalOffset = Schema.GetOffset(0x5847AABC46C1388A);

  public ref Vector InTangentLocal {
    get => ref _Handle.AsRef<Vector>(_InTangentLocalOffset);
  }
  private static readonly nint _OutTangentLocalOffset = Schema.GetOffset(0x5847AABC788EFFFB);

  public ref Vector OutTangentLocal {
    get => ref _Handle.AsRef<Vector>(_OutTangentLocalOffset);
  }
  private static readonly nint _ParentPathUniqueIDOffset = Schema.GetOffset(0x5847AABCC2958DE1);

  public string ParentPathUniqueID {
    get {
      var ptr = _Handle.Read<nint>(_ParentPathUniqueIDOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _ParentPathUniqueIDOffset, value);
  } 
  private static readonly nint _PathNodeParameterOffset = Schema.GetOffset(0x5847AABC5B2492DE);

  public string PathNodeParameter {
    get {
      var ptr = _Handle.Read<nint>(_PathNodeParameterOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _PathNodeParameterOffset, value);
  } 
  private static readonly nint _OnStartFromOrInSegmentOffset = Schema.GetOffset(0x5847AABC6622BECB);

  public CEntityIOOutput OnStartFromOrInSegment {
    get => new CEntityIOOutputImpl(_Handle + _OnStartFromOrInSegmentOffset);
  }
  private static readonly nint _OnStoppedAtOrInSegmentOffset = Schema.GetOffset(0x5847AABCBF4204DB);

  public CEntityIOOutput OnStoppedAtOrInSegment {
    get => new CEntityIOOutputImpl(_Handle + _OnStoppedAtOrInSegmentOffset);
  }
  private static readonly nint _OnPassThroughOffset = Schema.GetOffset(0x5847AABC3A5F20B6);

  public CEntityIOOutput OnPassThrough {
    get => new CEntityIOOutputImpl(_Handle + _OnPassThroughOffset);
  }
  private static readonly nint _OnPassThroughForwardOffset = Schema.GetOffset(0x5847AABCA62F443B);

  public CEntityIOOutput OnPassThroughForward {
    get => new CEntityIOOutputImpl(_Handle + _OnPassThroughForwardOffset);
  }
  private static readonly nint _OnPassThroughReverseOffset = Schema.GetOffset(0x5847AABC37667FA8);

  public CEntityIOOutput OnPassThroughReverse {
    get => new CEntityIOOutputImpl(_Handle + _OnPassThroughReverseOffset);
  }
  private static readonly nint _MoverOffset = Schema.GetOffset(0x5847AABC3629FA74);

  public ref CHandle<CPathMover> Mover {
    get => ref _Handle.AsRef<CHandle<CPathMover>>(_MoverOffset);
  }
  private static readonly nint _XWSPrevParentOffset = Schema.GetOffset(0x5847AABC2AEC980C);

  public ref CTransform XWSPrevParent {
    get => ref _Handle.AsRef<CTransform>(_XWSPrevParentOffset);
  }


}