// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmChainLookatTaskImpl : CNmPoseTaskImpl, CNmChainLookatTask {

  public CNmChainLookatTaskImpl(nint handle) : base(handle) {
  }

  private static readonly nint _ChainEndBoneIdxOffset = Schema.GetOffset(0x4021FFEBC513D7B8);

  public ref int ChainEndBoneIdx {
    get => ref _Handle.AsRef<int>(_ChainEndBoneIdxOffset);
  }
  private static readonly nint _NumBonesInChainOffset = Schema.GetOffset(0x4021FFEBCAD2EB3E);

  public ref int NumBonesInChain {
    get => ref _Handle.AsRef<int>(_NumBonesInChainOffset);
  }
  private static readonly nint _ChainForwardDirOffset = Schema.GetOffset(0x4021FFEB98A5355A);

  public ref Vector ChainForwardDir {
    get => ref _Handle.AsRef<Vector>(_ChainForwardDirOffset);
  }
  private static readonly nint _BlendWeightOffset = Schema.GetOffset(0x4021FFEBE5D6B9CE);

  public ref float BlendWeight {
    get => ref _Handle.AsRef<float>(_BlendWeightOffset);
  }
  private static readonly nint _HorizontalAngleLimitDegreesOffset = Schema.GetOffset(0x4021FFEB0D028F1E);

  public ref float HorizontalAngleLimitDegrees {
    get => ref _Handle.AsRef<float>(_HorizontalAngleLimitDegreesOffset);
  }
  private static readonly nint _VerticalAngleLimitDegreesOffset = Schema.GetOffset(0x4021FFEBC3214250);

  public ref float VerticalAngleLimitDegrees {
    get => ref _Handle.AsRef<float>(_VerticalAngleLimitDegreesOffset);
  }
  private static readonly nint _LookatTargetOffset = Schema.GetOffset(0x4021FFEBBD59D4D6);

  public ref Vector LookatTarget {
    get => ref _Handle.AsRef<Vector>(_LookatTargetOffset);
  }
  private static readonly nint _IsTargetInWorldSpaceOffset = Schema.GetOffset(0x4021FFEB5F56E0C5);

  public ref bool IsTargetInWorldSpace {
    get => ref _Handle.AsRef<bool>(_IsTargetInWorldSpaceOffset);
  }
  private static readonly nint _IsRunningFromDeserializedDataOffset = Schema.GetOffset(0x4021FFEB4791111D);

  public ref bool IsRunningFromDeserializedData {
    get => ref _Handle.AsRef<bool>(_IsRunningFromDeserializedDataOffset);
  }
  private static readonly nint _HorizontalAngleDegreesOffset = Schema.GetOffset(0x4021FFEB25C3867F);

  public ref float HorizontalAngleDegrees {
    get => ref _Handle.AsRef<float>(_HorizontalAngleDegreesOffset);
  }
  private static readonly nint _VerticalAngleDegreesOffset = Schema.GetOffset(0x4021FFEBF1DC7205);

  public ref float VerticalAngleDegrees {
    get => ref _Handle.AsRef<float>(_VerticalAngleDegreesOffset);
  }


}