// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmFloatComparisonNode__CDefinitionImpl : CNmBoolValueNode__CDefinitionImpl, CNmFloatComparisonNode__CDefinition {

  public CNmFloatComparisonNode__CDefinitionImpl(nint handle) : base(handle) {
  }

  private static readonly nint _InputValueNodeIdxOffset = Schema.GetOffset(0x48A96E9A95E89F27);

  public ref short InputValueNodeIdx {
    get => ref _Handle.AsRef<short>(_InputValueNodeIdxOffset);
  }
  private static readonly nint _ComparandValueNodeIdxOffset = Schema.GetOffset(0x48A96E9AF7CFFAF6);

  public ref short ComparandValueNodeIdx {
    get => ref _Handle.AsRef<short>(_ComparandValueNodeIdxOffset);
  }
  private static readonly nint _ComparisonOffset = Schema.GetOffset(0x48A96E9A897F8DE4);

  public ref CNmFloatComparisonNode__Comparison_t Comparison {
    get => ref _Handle.AsRef<CNmFloatComparisonNode__Comparison_t>(_ComparisonOffset);
  }
  private static readonly nint _EpsilonOffset = Schema.GetOffset(0x48A96E9A34090A67);

  public ref float Epsilon {
    get => ref _Handle.AsRef<float>(_EpsilonOffset);
  }
  private static readonly nint _ComparisonValueOffset = Schema.GetOffset(0x48A96E9A4C176B7F);

  public ref float ComparisonValue {
    get => ref _Handle.AsRef<float>(_ComparisonValueOffset);
  }


}