// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmFootstepEventPercentageThroughNode__CDefinitionImpl : CNmFloatValueNode__CDefinitionImpl, CNmFootstepEventPercentageThroughNode__CDefinition {

  public CNmFootstepEventPercentageThroughNode__CDefinitionImpl(nint handle) : base(handle) {
  }

  private static readonly nint _SourceStateNodeIdxOffset = Schema.GetOffset(0x998F83E463F0228C);

  public ref short SourceStateNodeIdx {
    get => ref _Handle.AsRef<short>(_SourceStateNodeIdxOffset);
  }
  private static readonly nint _PhaseConditionOffset = Schema.GetOffset(0x998F83E479D4BD7D);

  public ref NmFootPhaseCondition_t PhaseCondition {
    get => ref _Handle.AsRef<NmFootPhaseCondition_t>(_PhaseConditionOffset);
  }
  private static readonly nint _EventConditionRulesOffset = Schema.GetOffset(0x998F83E4A904315F);

  public CNmBitFlags EventConditionRules {
    get => new CNmBitFlagsImpl(_Handle + _EventConditionRulesOffset);
  }


}