// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmFloatCurveEventNode__CDefinitionImpl : CNmFloatValueNode__CDefinitionImpl, CNmFloatCurveEventNode__CDefinition {

  public CNmFloatCurveEventNode__CDefinitionImpl(nint handle) : base(handle) {
  }

  private static readonly nint _EventIDOffset = Schema.GetOffset(0x4512F5A69D798A72);

  public ref CGlobalSymbol EventID {
    get => ref _Handle.AsRef<CGlobalSymbol>(_EventIDOffset);
  }
  private static readonly nint _DefaultNodeIdxOffset = Schema.GetOffset(0x4512F5A6C14C9521);

  public ref short DefaultNodeIdx {
    get => ref _Handle.AsRef<short>(_DefaultNodeIdxOffset);
  }
  private static readonly nint _DefaultValueOffset = Schema.GetOffset(0x4512F5A6700AB429);

  public ref float DefaultValue {
    get => ref _Handle.AsRef<float>(_DefaultValueOffset);
  }
  private static readonly nint _EventConditionRulesOffset = Schema.GetOffset(0x4512F5A6A904315F);

  public CNmBitFlags EventConditionRules {
    get => new CNmBitFlagsImpl(_Handle + _EventConditionRulesOffset);
  }


}