// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmGraphDefinition__ReferencedGraphSlot_tImpl : SchemaClass, CNmGraphDefinition__ReferencedGraphSlot_t {

  public CNmGraphDefinition__ReferencedGraphSlot_tImpl(nint handle) : base(handle) {
  }

  private static readonly nint _NodeIdxOffset = Schema.GetOffset(0x33C2E12E124AB5CC);

  public ref short NodeIdx {
    get => ref _Handle.AsRef<short>(_NodeIdxOffset);
  }
  private static readonly nint _DataSlotIdxOffset = Schema.GetOffset(0x33C2E12E7115A3B4);

  public ref short DataSlotIdx {
    get => ref _Handle.AsRef<short>(_DataSlotIdxOffset);
  }


}