// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmIKRigImpl : SchemaClass, CNmIKRig {

  public CNmIKRigImpl(nint handle) : base(handle) {
  }

  private static readonly nint _SkeletonOffset = Schema.GetOffset(0x9C509BCFE77F030E);

  public ref CStrongHandle<InfoForResourceTypeCNmSkeleton> Skeleton {
    get => ref _Handle.AsRef<CStrongHandle<InfoForResourceTypeCNmSkeleton>>(_SkeletonOffset);
  }
  private static readonly nint _BodiesOffset = Schema.GetOffset(0x9C509BCF24483A49);

  public ref CUtlVector<CNmIKBody> Bodies {
    get => ref _Handle.AsRef<CUtlVector<CNmIKBody>>(_BodiesOffset);
  }
  private static readonly nint _JointsOffset = Schema.GetOffset(0x9C509BCF364EA4AC);

  public ref CUtlVector<CNmIKJoint> Joints {
    get => ref _Handle.AsRef<CUtlVector<CNmIKJoint>>(_JointsOffset);
  }


}