// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmIDToFloatNode__CDefinitionImpl : CNmFloatValueNode__CDefinitionImpl, CNmIDToFloatNode__CDefinition {

  public CNmIDToFloatNode__CDefinitionImpl(nint handle) : base(handle) {
  }

  private static readonly nint _InputValueNodeIdxOffset = Schema.GetOffset(0x9F6F687D95E89F27);

  public ref short InputValueNodeIdx {
    get => ref _Handle.AsRef<short>(_InputValueNodeIdxOffset);
  }
  private static readonly nint _DefaultValueOffset = Schema.GetOffset(0x9F6F687DBBE0341F);

  public ref float DefaultValue {
    get => ref _Handle.AsRef<float>(_DefaultValueOffset);
  }
  private static readonly nint _IDsOffset = Schema.GetOffset(0x9F6F687D0C180009);

  public SchemaUntypedField IDs {
    get => new SchemaUntypedField(_Handle + _IDsOffset);
  }
  private static readonly nint _ValuesOffset = Schema.GetOffset(0x9F6F687DFBEDDADB);

  public SchemaUntypedField Values {
    get => new SchemaUntypedField(_Handle + _ValuesOffset);
  }


}