// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmLayerBlendNode__LayerDefinition_tImpl : SchemaClass, CNmLayerBlendNode__LayerDefinition_t {

  public CNmLayerBlendNode__LayerDefinition_tImpl(nint handle) : base(handle) {
  }

  private static readonly nint _InputNodeIdxOffset = Schema.GetOffset(0xB5F2C492B0A177F6);

  public ref short InputNodeIdx {
    get => ref _Handle.AsRef<short>(_InputNodeIdxOffset);
  }
  private static readonly nint _WeightValueNodeIdxOffset = Schema.GetOffset(0xB5F2C4924E4CD159);

  public ref short WeightValueNodeIdx {
    get => ref _Handle.AsRef<short>(_WeightValueNodeIdxOffset);
  }
  private static readonly nint _BoneMaskValueNodeIdxOffset = Schema.GetOffset(0xB5F2C49284E70B17);

  public ref short BoneMaskValueNodeIdx {
    get => ref _Handle.AsRef<short>(_BoneMaskValueNodeIdxOffset);
  }
  private static readonly nint _RootMotionWeightValueNodeIdxOffset = Schema.GetOffset(0xB5F2C492C355D4CF);

  public ref short RootMotionWeightValueNodeIdx {
    get => ref _Handle.AsRef<short>(_RootMotionWeightValueNodeIdxOffset);
  }
  private static readonly nint _IsSynchronizedOffset = Schema.GetOffset(0xB5F2C492DCF1E06B);

  public ref bool IsSynchronized {
    get => ref _Handle.AsRef<bool>(_IsSynchronizedOffset);
  }
  private static readonly nint _IgnoreEventsOffset = Schema.GetOffset(0xB5F2C4920E574CA6);

  public ref bool IgnoreEvents {
    get => ref _Handle.AsRef<bool>(_IgnoreEventsOffset);
  }
  private static readonly nint _IsStateMachineLayerOffset = Schema.GetOffset(0xB5F2C492EE48C9D0);

  public ref bool IsStateMachineLayer {
    get => ref _Handle.AsRef<bool>(_IsStateMachineLayerOffset);
  }
  private static readonly nint _BlendModeOffset = Schema.GetOffset(0xB5F2C4928D5006AB);

  public ref NmPoseBlendMode_t BlendMode {
    get => ref _Handle.AsRef<NmPoseBlendMode_t>(_BlendModeOffset);
  }


}