// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmParameterizedBlendNode__BlendRange_tImpl : SchemaClass, CNmParameterizedBlendNode__BlendRange_t {

  public CNmParameterizedBlendNode__BlendRange_tImpl(nint handle) : base(handle) {
  }

  private static readonly nint _InputIdx0Offset = Schema.GetOffset(0x17812ECC5A8983D2);

  public ref short InputIdx0 {
    get => ref _Handle.AsRef<short>(_InputIdx0Offset);
  }
  private static readonly nint _InputIdx1Offset = Schema.GetOffset(0x17812ECC5B898565);

  public ref short InputIdx1 {
    get => ref _Handle.AsRef<short>(_InputIdx1Offset);
  }
  private static readonly nint _ParameterValueRangeOffset = Schema.GetOffset(0x17812ECC64AF37AE);

  public SchemaUntypedField ParameterValueRange {
    get => new SchemaUntypedField(_Handle + _ParameterValueRangeOffset);
  }


}