// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmRootMotionOverrideNode__CDefinitionImpl : CNmPassthroughNode__CDefinitionImpl, CNmRootMotionOverrideNode__CDefinition {

  public CNmRootMotionOverrideNode__CDefinitionImpl(nint handle) : base(handle) {
  }

  private static readonly nint _DesiredMovingVelocityNodeIdxOffset = Schema.GetOffset(0x63AAD28BA5EFD80B);

  public ref short DesiredMovingVelocityNodeIdx {
    get => ref _Handle.AsRef<short>(_DesiredMovingVelocityNodeIdxOffset);
  }
  private static readonly nint _DesiredFacingDirectionNodeIdxOffset = Schema.GetOffset(0x63AAD28BAC723A63);

  public ref short DesiredFacingDirectionNodeIdx {
    get => ref _Handle.AsRef<short>(_DesiredFacingDirectionNodeIdxOffset);
  }
  private static readonly nint _LinearVelocityLimitNodeIdxOffset = Schema.GetOffset(0x63AAD28B56A698BD);

  public ref short LinearVelocityLimitNodeIdx {
    get => ref _Handle.AsRef<short>(_LinearVelocityLimitNodeIdxOffset);
  }
  private static readonly nint _AngularVelocityLimitNodeIdxOffset = Schema.GetOffset(0x63AAD28BCC9208F8);

  public ref short AngularVelocityLimitNodeIdx {
    get => ref _Handle.AsRef<short>(_AngularVelocityLimitNodeIdxOffset);
  }
  private static readonly nint _MaxLinearVelocityOffset = Schema.GetOffset(0x63AAD28B70FC93F7);

  public ref float MaxLinearVelocity {
    get => ref _Handle.AsRef<float>(_MaxLinearVelocityOffset);
  }
  private static readonly nint _MaxAngularVelocityRadiansOffset = Schema.GetOffset(0x63AAD28BC15BAB90);

  public ref float MaxAngularVelocityRadians {
    get => ref _Handle.AsRef<float>(_MaxAngularVelocityRadiansOffset);
  }
  private static readonly nint _OverrideFlagsOffset = Schema.GetOffset(0x63AAD28BBDB571A4);

  public CNmBitFlags OverrideFlags {
    get => new CNmBitFlagsImpl(_Handle + _OverrideFlagsOffset);
  }


}