// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmSyncTrackImpl : SchemaClass, CNmSyncTrack {

  public CNmSyncTrackImpl(nint handle) : base(handle) {
  }

  private static readonly nint _SyncEventsOffset = Schema.GetOffset(0x29C7FA0336BAB4FF);

  public SchemaUntypedField SyncEvents {
    get => new SchemaUntypedField(_Handle + _SyncEventsOffset);
  }
  private static readonly nint _StartEventOffsetOffset = Schema.GetOffset(0x29C7FA03DDBC640E);

  public ref int StartEventOffset {
    get => ref _Handle.AsRef<int>(_StartEventOffsetOffset);
  }


}