// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmSkeletonImpl : SchemaClass, CNmSkeleton {

  public CNmSkeletonImpl(nint handle) : base(handle) {
  }

  private static readonly nint _IDOffset = Schema.GetOffset(0xC923251495066900);

  public ref CGlobalSymbol ID {
    get => ref _Handle.AsRef<CGlobalSymbol>(_IDOffset);
  }
  private static readonly nint _BoneIDsOffset = Schema.GetOffset(0xC92325140909C443);

  public ref CUtlLeanVector<CGlobalSymbol, int> BoneIDs {
    get => ref _Handle.AsRef<CUtlLeanVector<CGlobalSymbol, int>>(_BoneIDsOffset);
  }
  private static readonly nint _ParentIndicesOffset = Schema.GetOffset(0xC923251480CFB2AA);

  public ref CUtlVector<int> ParentIndices {
    get => ref _Handle.AsRef<CUtlVector<int>>(_ParentIndicesOffset);
  }
  private static readonly nint _ParentSpaceReferencePoseOffset = Schema.GetOffset(0xC92325145BF1EDE7);

  public ref CUtlVector<CTransform> ParentSpaceReferencePose {
    get => ref _Handle.AsRef<CUtlVector<CTransform>>(_ParentSpaceReferencePoseOffset);
  }
  private static readonly nint _ModelSpaceReferencePoseOffset = Schema.GetOffset(0xC92325147B025328);

  public ref CUtlVector<CTransform> ModelSpaceReferencePose {
    get => ref _Handle.AsRef<CUtlVector<CTransform>>(_ModelSpaceReferencePoseOffset);
  }
  private static readonly nint _NumBonesToSampleAtLowLODOffset = Schema.GetOffset(0xC9232514813C419D);

  public ref int NumBonesToSampleAtLowLOD {
    get => ref _Handle.AsRef<int>(_NumBonesToSampleAtLowLODOffset);
  }
  private static readonly nint _MaskDefinitionsOffset = Schema.GetOffset(0xC92325147196574D);

  public ref CUtlLeanVector<NmBoneMaskSetDefinition_t, int> MaskDefinitions {
    get => ref _Handle.AsRef<CUtlLeanVector<NmBoneMaskSetDefinition_t, int>>(_MaskDefinitionsOffset);
  }
  private static readonly nint _SecondarySkeletonsOffset = Schema.GetOffset(0xC9232514782F396B);

  public ref CUtlLeanVector<CNmSkeleton__SecondarySkeleton_t, int> SecondarySkeletons {
    get => ref _Handle.AsRef<CUtlLeanVector<CNmSkeleton__SecondarySkeleton_t, int>>(_SecondarySkeletonsOffset);
  }
  private static readonly nint _IsPropSkeletonOffset = Schema.GetOffset(0xC9232514FD7D351F);

  public ref bool IsPropSkeleton {
    get => ref _Handle.AsRef<bool>(_IsPropSkeletonOffset);
  }


}