// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNPCPhysicsHullImpl : SchemaClass, CNPCPhysicsHull {

  public CNPCPhysicsHullImpl(nint handle) : base(handle) {
  }

  private static readonly nint _NameOffset = Schema.GetOffset(0x6C27881963D22D49);

  public ref CGlobalSymbol Name {
    get => ref _Handle.AsRef<CGlobalSymbol>(_NameOffset);
  }
  private static readonly nint _TypeOffset = Schema.GetOffset(0x6C27881921B39888);

  public ref NPCPhysicsHullType_t Type {
    get => ref _Handle.AsRef<NPCPhysicsHullType_t>(_TypeOffset);
  }
  private static readonly nint _CapsuleHeightOffset = Schema.GetOffset(0x6C278819043CF691);

  public ref float CapsuleHeight {
    get => ref _Handle.AsRef<float>(_CapsuleHeightOffset);
  }
  private static readonly nint _CapsuleRadiusOffset = Schema.GetOffset(0x6C278819A1A593D0);

  public ref float CapsuleRadius {
    get => ref _Handle.AsRef<float>(_CapsuleRadiusOffset);
  }
  private static readonly nint _CapsuleCenter1Offset = Schema.GetOffset(0x6C278819A5E81978);

  public ref Vector CapsuleCenter1 {
    get => ref _Handle.AsRef<Vector>(_CapsuleCenter1Offset);
  }
  private static readonly nint _CapsuleCenter2Offset = Schema.GetOffset(0x6C278819A8E81E31);

  public ref Vector CapsuleCenter2 {
    get => ref _Handle.AsRef<Vector>(_CapsuleCenter2Offset);
  }
  private static readonly nint _GroundBoxHeightOffset = Schema.GetOffset(0x6C2788195B2D099E);

  public ref float GroundBoxHeight {
    get => ref _Handle.AsRef<float>(_GroundBoxHeightOffset);
  }
  private static readonly nint _GroundBoxWidthOffset = Schema.GetOffset(0x6C2788194A30F5E3);

  public ref float GroundBoxWidth {
    get => ref _Handle.AsRef<float>(_GroundBoxWidthOffset);
  }


}