// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CovMatrix3Impl : SchemaClass, CovMatrix3 {

  public CovMatrix3Impl(nint handle) : base(handle) {
  }

  private static readonly nint _DiagOffset = Schema.GetOffset(0xA222FA6F7CC0D332);

  public ref Vector Diag {
    get => ref _Handle.AsRef<Vector>(_DiagOffset);
  }
  private static readonly nint _XYOffset = Schema.GetOffset(0xA222FA6FA58DC304);

  public ref float XY {
    get => ref _Handle.AsRef<float>(_XYOffset);
  }
  private static readonly nint _XZOffset = Schema.GetOffset(0xA222FA6FA88DC7BD);

  public ref float XZ {
    get => ref _Handle.AsRef<float>(_XZOffset);
  }
  private static readonly nint _YZOffset = Schema.GetOffset(0xA222FA6F9E8B7968);

  public ref float YZ {
    get => ref _Handle.AsRef<float>(_YZOffset);
  }


}