// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CParticleVecInputImpl : CParticleInputImpl, CParticleVecInput {

  public CParticleVecInputImpl(nint handle) : base(handle) {
  }

  private static readonly nint _TypeOffset = Schema.GetOffset(0xD598DA0A18853D59);

  public ref ParticleVecType_t Type {
    get => ref _Handle.AsRef<ParticleVecType_t>(_TypeOffset);
  }
  private static readonly nint _LiteralValueOffset = Schema.GetOffset(0xD598DA0A80638A21);

  public ref Vector LiteralValue {
    get => ref _Handle.AsRef<Vector>(_LiteralValueOffset);
  }
  private static readonly nint _LiteralColorOffset = Schema.GetOffset(0xD598DA0A75AE86AB);

  public ref Color LiteralColor {
    get => ref _Handle.AsRef<Color>(_LiteralColorOffset);
  }
  private static readonly nint _NamedValueOffset = Schema.GetOffset(0xD598DA0AE0618727);

  public SchemaUntypedField NamedValue {
    get => new SchemaUntypedField(_Handle + _NamedValueOffset);
  }
  private static readonly nint _FollowNamedValueOffset = Schema.GetOffset(0xD598DA0A0F6CBBBA);

  public ref bool FollowNamedValue {
    get => ref _Handle.AsRef<bool>(_FollowNamedValueOffset);
  }
  private static readonly nint _VectorAttributeOffset = Schema.GetOffset(0xD598DA0A2B36D79A);

  public ParticleAttributeIndex_t VectorAttribute {
    get => new ParticleAttributeIndex_tImpl(_Handle + _VectorAttributeOffset);
  }
  private static readonly nint _VectorAttributeScaleOffset = Schema.GetOffset(0xD598DA0A69912478);

  public ref Vector VectorAttributeScale {
    get => ref _Handle.AsRef<Vector>(_VectorAttributeScaleOffset);
  }
  private static readonly nint _ControlPointOffset = Schema.GetOffset(0xD598DA0A0D0DDF8C);

  public ref int ControlPoint {
    get => ref _Handle.AsRef<int>(_ControlPointOffset);
  }
  private static readonly nint _DeltaControlPointOffset = Schema.GetOffset(0xD598DA0AC74F7C50);

  public ref int DeltaControlPoint {
    get => ref _Handle.AsRef<int>(_DeltaControlPointOffset);
  }
  private static readonly nint _CPValueScaleOffset = Schema.GetOffset(0xD598DA0A9A43168B);

  public ref Vector CPValueScale {
    get => ref _Handle.AsRef<Vector>(_CPValueScaleOffset);
  }
  private static readonly nint _CPRelativePositionOffset = Schema.GetOffset(0xD598DA0A1964C465);

  public ref Vector CPRelativePosition {
    get => ref _Handle.AsRef<Vector>(_CPRelativePositionOffset);
  }
  private static readonly nint _CPRelativeDirOffset = Schema.GetOffset(0xD598DA0A23334FC1);

  public ref Vector CPRelativeDir {
    get => ref _Handle.AsRef<Vector>(_CPRelativeDirOffset);
  }
  private static readonly nint _FloatComponentXOffset = Schema.GetOffset(0xD598DA0A8D4D4148);

  public CParticleFloatInput FloatComponentX {
    get => new CParticleFloatInputImpl(_Handle + _FloatComponentXOffset);
  }
  private static readonly nint _FloatComponentYOffset = Schema.GetOffset(0xD598DA0A8E4D42DB);

  public CParticleFloatInput FloatComponentY {
    get => new CParticleFloatInputImpl(_Handle + _FloatComponentYOffset);
  }
  private static readonly nint _FloatComponentZOffset = Schema.GetOffset(0xD598DA0A8F4D446E);

  public CParticleFloatInput FloatComponentZ {
    get => new CParticleFloatInputImpl(_Handle + _FloatComponentZOffset);
  }
  private static readonly nint _FloatInterpOffset = Schema.GetOffset(0xD598DA0AF81AB0BB);

  public CParticleFloatInput FloatInterp {
    get => new CParticleFloatInputImpl(_Handle + _FloatInterpOffset);
  }
  private static readonly nint _InterpInput0Offset = Schema.GetOffset(0xD598DA0A55806CD1);

  public ref float InterpInput0 {
    get => ref _Handle.AsRef<float>(_InterpInput0Offset);
  }
  private static readonly nint _InterpInput1Offset = Schema.GetOffset(0xD598DA0A54806B3E);

  public ref float InterpInput1 {
    get => ref _Handle.AsRef<float>(_InterpInput1Offset);
  }
  private static readonly nint _InterpOutput0Offset = Schema.GetOffset(0xD598DA0AD54AF42E);

  public ref Vector InterpOutput0 {
    get => ref _Handle.AsRef<Vector>(_InterpOutput0Offset);
  }
  private static readonly nint _InterpOutput1Offset = Schema.GetOffset(0xD598DA0AD64AF5C1);

  public ref Vector InterpOutput1 {
    get => ref _Handle.AsRef<Vector>(_InterpOutput1Offset);
  }
  private static readonly nint _GradientOffset = Schema.GetOffset(0xD598DA0A05C95F25);

  public SchemaUntypedField Gradient {
    get => new SchemaUntypedField(_Handle + _GradientOffset);
  }
  private static readonly nint _RandomMinOffset = Schema.GetOffset(0xD598DA0AC6B45DA2);

  public ref Vector RandomMin {
    get => ref _Handle.AsRef<Vector>(_RandomMinOffset);
  }
  private static readonly nint _RandomMaxOffset = Schema.GetOffset(0xD598DA0AB0A0B348);

  public ref Vector RandomMax {
    get => ref _Handle.AsRef<Vector>(_RandomMaxOffset);
  }


}