// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPhysPulleyImpl : CPhysConstraintImpl, CPhysPulley {

  public CPhysPulleyImpl(nint handle) : base(handle) {
  }

  private static readonly nint _Position2Offset = Schema.GetOffset(0xDCB3A22333568F48);

  public ref Vector Position2 {
    get => ref _Handle.AsRef<Vector>(_Position2Offset);
  }
  public ISchemaFixedArray<Vector> Offset {
    get => new SchemaFixedArray<Vector>(_Handle, 0xDCB3A223F836806A, 2, 12, 4);
  }
  private static readonly nint _AddLengthOffset = Schema.GetOffset(0xDCB3A223A30AA6D8);

  public ref float AddLength {
    get => ref _Handle.AsRef<float>(_AddLengthOffset);
  }
  private static readonly nint _GearRatioOffset = Schema.GetOffset(0xDCB3A223DF6EB135);

  public ref float GearRatio {
    get => ref _Handle.AsRef<float>(_GearRatioOffset);
  }


}