// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPhysSlideConstraintImpl : CPhysConstraintImpl, CPhysSlideConstraint {

  public CPhysSlideConstraintImpl(nint handle) : base(handle) {
  }

  private static readonly nint _AxisEndOffset = Schema.GetOffset(0xA91FF5D04F9CAA89);

  public ref Vector AxisEnd {
    get => ref _Handle.AsRef<Vector>(_AxisEndOffset);
  }
  private static readonly nint _SlideFrictionOffset = Schema.GetOffset(0xA91FF5D0A21A9E94);

  public ref float SlideFriction {
    get => ref _Handle.AsRef<float>(_SlideFrictionOffset);
  }
  private static readonly nint _SystemLoadScaleOffset = Schema.GetOffset(0xA91FF5D09C24DB62);

  public ref float SystemLoadScale {
    get => ref _Handle.AsRef<float>(_SystemLoadScaleOffset);
  }
  private static readonly nint _InitialOffsetOffset = Schema.GetOffset(0xA91FF5D0A52C9850);

  public ref float InitialOffset {
    get => ref _Handle.AsRef<float>(_InitialOffsetOffset);
  }
  private static readonly nint _EnableLinearConstraintOffset = Schema.GetOffset(0xA91FF5D068F4518C);

  public ref bool EnableLinearConstraint {
    get => ref _Handle.AsRef<bool>(_EnableLinearConstraintOffset);
  }
  private static readonly nint _EnableAngularConstraintOffset = Schema.GetOffset(0xA91FF5D0F98A5C8B);

  public ref bool EnableAngularConstraint {
    get => ref _Handle.AsRef<bool>(_EnableAngularConstraintOffset);
  }
  private static readonly nint _MotorFrequencyOffset = Schema.GetOffset(0xA91FF5D056F7120A);

  public ref float MotorFrequency {
    get => ref _Handle.AsRef<float>(_MotorFrequencyOffset);
  }
  private static readonly nint _MotorDampingRatioOffset = Schema.GetOffset(0xA91FF5D0D8669699);

  public ref float MotorDampingRatio {
    get => ref _Handle.AsRef<float>(_MotorDampingRatioOffset);
  }
  private static readonly nint _UseEntityPivotOffset = Schema.GetOffset(0xA91FF5D0240C4065);

  public ref bool UseEntityPivot {
    get => ref _Handle.AsRef<bool>(_UseEntityPivotOffset);
  }
  private static readonly nint _SoundInfoOffset = Schema.GetOffset(0xA91FF5D085F704E8);

  public ConstraintSoundInfo SoundInfo {
    get => new ConstraintSoundInfoImpl(_Handle + _SoundInfoOffset);
  }


}