// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPhysImpactImpl : CPointEntityImpl, CPhysImpact {

  public CPhysImpactImpl(nint handle) : base(handle) {
  }

  private static readonly nint _DamageOffset = Schema.GetOffset(0x2C5E7E549C988CE0);

  public ref float Damage {
    get => ref _Handle.AsRef<float>(_DamageOffset);
  }
  private static readonly nint _DistanceOffset = Schema.GetOffset(0x2C5E7E543CB20D02);

  public ref float Distance {
    get => ref _Handle.AsRef<float>(_DistanceOffset);
  }
  private static readonly nint _DirectionEntityNameOffset = Schema.GetOffset(0x2C5E7E54329C8132);

  public string DirectionEntityName {
    get {
      var ptr = _Handle.Read<nint>(_DirectionEntityNameOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _DirectionEntityNameOffset, value);
  } 


}