// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPhysSurfacePropertiesSoundNamesImpl : SchemaClass, CPhysSurfacePropertiesSoundNames {

  public CPhysSurfacePropertiesSoundNamesImpl(nint handle) : base(handle) {
  }

  private static readonly nint _ImpactSoftOffset = Schema.GetOffset(0xF2658A3949E7237B);

  public string ImpactSoft {
    get {
      var ptr = _Handle.Read<nint>(_ImpactSoftOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _ImpactSoftOffset, value);
  } 
  private static readonly nint _ImpactHardOffset = Schema.GetOffset(0xF2658A3934A77BB2);

  public string ImpactHard {
    get {
      var ptr = _Handle.Read<nint>(_ImpactHardOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _ImpactHardOffset, value);
  } 
  private static readonly nint _ScrapeSmoothOffset = Schema.GetOffset(0xF2658A3902EA935F);

  public string ScrapeSmooth {
    get {
      var ptr = _Handle.Read<nint>(_ScrapeSmoothOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _ScrapeSmoothOffset, value);
  } 
  private static readonly nint _ScrapeRoughOffset = Schema.GetOffset(0xF2658A39CE764A7E);

  public string ScrapeRough {
    get {
      var ptr = _Handle.Read<nint>(_ScrapeRoughOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _ScrapeRoughOffset, value);
  } 
  private static readonly nint _BulletImpactOffset = Schema.GetOffset(0xF2658A3943E056BB);

  public string BulletImpact {
    get {
      var ptr = _Handle.Read<nint>(_BulletImpactOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _BulletImpactOffset, value);
  } 
  private static readonly nint _RollingOffset = Schema.GetOffset(0xF2658A39E0171912);

  public string Rolling {
    get {
      var ptr = _Handle.Read<nint>(_RollingOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _RollingOffset, value);
  } 
  private static readonly nint _BreakOffset = Schema.GetOffset(0xF2658A39382B2298);

  public string Break {
    get {
      var ptr = _Handle.Read<nint>(_BreakOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _BreakOffset, value);
  } 
  private static readonly nint _StrainOffset = Schema.GetOffset(0xF2658A397EDA2E10);

  public string Strain {
    get {
      var ptr = _Handle.Read<nint>(_StrainOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _StrainOffset, value);
  } 
  private static readonly nint _MeleeImpactOffset = Schema.GetOffset(0xF2658A3976A52491);

  public string MeleeImpact {
    get {
      var ptr = _Handle.Read<nint>(_MeleeImpactOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _MeleeImpactOffset, value);
  } 
  private static readonly nint _PushOffOffset = Schema.GetOffset(0xF2658A39C825B1A2);

  public string PushOff {
    get {
      var ptr = _Handle.Read<nint>(_PushOffOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _PushOffOffset, value);
  } 
  private static readonly nint _SkidStopOffset = Schema.GetOffset(0xF2658A3976C778AE);

  public string SkidStop {
    get {
      var ptr = _Handle.Read<nint>(_SkidStopOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _SkidStopOffset, value);
  } 
  private static readonly nint _ResonantOffset = Schema.GetOffset(0xF2658A396BA8FAF5);

  public string Resonant {
    get {
      var ptr = _Handle.Read<nint>(_ResonantOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _ResonantOffset, value);
  } 


}