// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPointAngularVelocitySensorImpl : CPointEntityImpl, CPointAngularVelocitySensor {

  public CPointAngularVelocitySensorImpl(nint handle) : base(handle) {
  }

  private static readonly nint _TargetEntityOffset = Schema.GetOffset(0x5B09D8F25D042A9);

  public ref CHandle<CBaseEntity> TargetEntity {
    get => ref _Handle.AsRef<CHandle<CBaseEntity>>(_TargetEntityOffset);
  }
  private static readonly nint _ThresholdOffset = Schema.GetOffset(0x5B09D8F7872FFEA);

  public ref float Threshold {
    get => ref _Handle.AsRef<float>(_ThresholdOffset);
  }
  private static readonly nint _LastCompareResultOffset = Schema.GetOffset(0x5B09D8F696B400D);

  public ref int LastCompareResult {
    get => ref _Handle.AsRef<int>(_LastCompareResultOffset);
  }
  private static readonly nint _LastFireResultOffset = Schema.GetOffset(0x5B09D8FBC50E238);

  public ref int LastFireResult {
    get => ref _Handle.AsRef<int>(_LastFireResultOffset);
  }
  private static readonly nint _FireTimeOffset = Schema.GetOffset(0x5B09D8F873CD172);

  public GameTime_t FireTime {
    get => new GameTime_tImpl(_Handle + _FireTimeOffset);
  }
  private static readonly nint _FireIntervalOffset = Schema.GetOffset(0x5B09D8F1B1AA6D2);

  public ref float FireInterval {
    get => ref _Handle.AsRef<float>(_FireIntervalOffset);
  }
  private static readonly nint _LastAngVelocityOffset = Schema.GetOffset(0x5B09D8F10D82166);

  public ref float LastAngVelocity {
    get => ref _Handle.AsRef<float>(_LastAngVelocityOffset);
  }
  private static readonly nint _LastOrientationOffset = Schema.GetOffset(0x5B09D8FBB4E87E5);

  public ref QAngle LastOrientation {
    get => ref _Handle.AsRef<QAngle>(_LastOrientationOffset);
  }
  private static readonly nint _AxisOffset = Schema.GetOffset(0x5B09D8F0AF9CE54);

  public ref Vector Axis {
    get => ref _Handle.AsRef<Vector>(_AxisOffset);
  }
  private static readonly nint _UseHelperOffset = Schema.GetOffset(0x5B09D8F7370F54C);

  public ref bool UseHelper {
    get => ref _Handle.AsRef<bool>(_UseHelperOffset);
  }
  private static readonly nint _AngularVelocityOffset = Schema.GetOffset(0x5B09D8FA4D9E2BE);

  public SchemaUntypedField AngularVelocity {
    get => new SchemaUntypedField(_Handle + _AngularVelocityOffset);
  }
  private static readonly nint _OnLessThanOffset = Schema.GetOffset(0x5B09D8FB6AC02FE);

  public CEntityIOOutput OnLessThan {
    get => new CEntityIOOutputImpl(_Handle + _OnLessThanOffset);
  }
  private static readonly nint _OnLessThanOrEqualToOffset = Schema.GetOffset(0x5B09D8F28E696D8);

  public CEntityIOOutput OnLessThanOrEqualTo {
    get => new CEntityIOOutputImpl(_Handle + _OnLessThanOrEqualToOffset);
  }
  private static readonly nint _OnGreaterThanOffset = Schema.GetOffset(0x5B09D8F50BD472D);

  public CEntityIOOutput OnGreaterThan {
    get => new CEntityIOOutputImpl(_Handle + _OnGreaterThanOffset);
  }
  private static readonly nint _OnGreaterThanOrEqualToOffset = Schema.GetOffset(0x5B09D8F6483CABD);

  public CEntityIOOutput OnGreaterThanOrEqualTo {
    get => new CEntityIOOutputImpl(_Handle + _OnGreaterThanOrEqualToOffset);
  }
  private static readonly nint _OnEqualToOffset = Schema.GetOffset(0x5B09D8F87EEC581);

  public CEntityIOOutput OnEqualTo {
    get => new CEntityIOOutputImpl(_Handle + _OnEqualToOffset);
  }


}