// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPointTemplateImpl : CLogicalEntityImpl, CPointTemplate {

  public CPointTemplateImpl(nint handle) : base(handle) {
  }

  private static readonly nint _WorldNameOffset = Schema.GetOffset(0x7085DB4EB1FC5B40);

  public string WorldName {
    get {
      var ptr = _Handle.Read<nint>(_WorldNameOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _WorldNameOffset, value);
  } 
  private static readonly nint _Source2EntityLumpNameOffset = Schema.GetOffset(0x7085DB4EC0B648BC);

  public string Source2EntityLumpName {
    get {
      var ptr = _Handle.Read<nint>(_Source2EntityLumpNameOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _Source2EntityLumpNameOffset, value);
  } 
  private static readonly nint _EntityFilterNameOffset = Schema.GetOffset(0x7085DB4E3BCB3E97);

  public string EntityFilterName {
    get {
      var ptr = _Handle.Read<nint>(_EntityFilterNameOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _EntityFilterNameOffset, value);
  } 
  private static readonly nint _TimeoutIntervalOffset = Schema.GetOffset(0x7085DB4E354D6687);

  public ref float TimeoutInterval {
    get => ref _Handle.AsRef<float>(_TimeoutIntervalOffset);
  }
  private static readonly nint _AsynchronouslySpawnEntitiesOffset = Schema.GetOffset(0x7085DB4E5371B8CE);

  public ref bool AsynchronouslySpawnEntities {
    get => ref _Handle.AsRef<bool>(_AsynchronouslySpawnEntitiesOffset);
  }
  private static readonly nint _ClientOnlyEntityBehaviorOffset = Schema.GetOffset(0x7085DB4EF26096D5);

  public ref PointTemplateClientOnlyEntityBehavior_t ClientOnlyEntityBehavior {
    get => ref _Handle.AsRef<PointTemplateClientOnlyEntityBehavior_t>(_ClientOnlyEntityBehaviorOffset);
  }
  private static readonly nint _OwnerSpawnGroupTypeOffset = Schema.GetOffset(0x7085DB4EFAC3C132);

  public ref PointTemplateOwnerSpawnGroupType_t OwnerSpawnGroupType {
    get => ref _Handle.AsRef<PointTemplateOwnerSpawnGroupType_t>(_OwnerSpawnGroupTypeOffset);
  }
  private static readonly nint _CreatedSpawnGroupHandlesOffset = Schema.GetOffset(0x7085DB4EF66F13E4);

  public ref CUtlVector<uint> CreatedSpawnGroupHandles {
    get => ref _Handle.AsRef<CUtlVector<uint>>(_CreatedSpawnGroupHandlesOffset);
  }
  private static readonly nint _SpawnedEntityHandlesOffset = Schema.GetOffset(0x7085DB4EAFF1C191);

  public ref CUtlVector<CHandle<CEntityInstance>> SpawnedEntityHandles {
    get => ref _Handle.AsRef<CUtlVector<CHandle<CEntityInstance>>>(_SpawnedEntityHandlesOffset);
  }
  private static readonly nint _ScriptSpawnCallbackOffset = Schema.GetOffset(0x7085DB4EAD74D892);

  public SchemaUntypedField ScriptSpawnCallback {
    get => new SchemaUntypedField(_Handle + _ScriptSpawnCallbackOffset);
  }
  private static readonly nint _ScriptCallbackScopeOffset = Schema.GetOffset(0x7085DB4E3B18B033);

  public SchemaUntypedField ScriptCallbackScope {
    get => new SchemaUntypedField(_Handle + _ScriptCallbackScopeOffset);
  }


}