// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPointPrefabImpl : CServerOnlyPointEntityImpl, CPointPrefab {

  public CPointPrefabImpl(nint handle) : base(handle) {
  }

  private static readonly nint _TargetMapNameOffset = Schema.GetOffset(0x2C6EB7C6129742FD);

  public string TargetMapName {
    get {
      var ptr = _Handle.Read<nint>(_TargetMapNameOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _TargetMapNameOffset, value);
  } 
  private static readonly nint _ForceWorldGroupIDOffset = Schema.GetOffset(0x2C6EB7C61F55F68E);

  public string ForceWorldGroupID {
    get {
      var ptr = _Handle.Read<nint>(_ForceWorldGroupIDOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _ForceWorldGroupIDOffset, value);
  } 
  private static readonly nint _AssociatedRelayTargetNameOffset = Schema.GetOffset(0x2C6EB7C6A6960E7A);

  public string AssociatedRelayTargetName {
    get {
      var ptr = _Handle.Read<nint>(_AssociatedRelayTargetNameOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _AssociatedRelayTargetNameOffset, value);
  } 
  private static readonly nint _FixupNamesOffset = Schema.GetOffset(0x2C6EB7C6821D8FCF);

  public ref bool FixupNames {
    get => ref _Handle.AsRef<bool>(_FixupNamesOffset);
  }
  private static readonly nint _LoadDynamicOffset = Schema.GetOffset(0x2C6EB7C6A3437F12);

  public ref bool LoadDynamic {
    get => ref _Handle.AsRef<bool>(_LoadDynamicOffset);
  }
  private static readonly nint _AssociatedRelayEntityOffset = Schema.GetOffset(0x2C6EB7C683435943);

  public ref CHandle<CPointPrefab> AssociatedRelayEntity {
    get => ref _Handle.AsRef<CHandle<CPointPrefab>>(_AssociatedRelayEntityOffset);
  }


}