// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPointVelocitySensorImpl : CPointEntityImpl, CPointVelocitySensor {

  public CPointVelocitySensorImpl(nint handle) : base(handle) {
  }

  private static readonly nint _TargetEntityOffset = Schema.GetOffset(0x96CA232125D042A9);

  public ref CHandle<CBaseEntity> TargetEntity {
    get => ref _Handle.AsRef<CHandle<CBaseEntity>>(_TargetEntityOffset);
  }
  private static readonly nint _AxisOffset = Schema.GetOffset(0x96CA23210AF9CE54);

  public ref Vector Axis {
    get => ref _Handle.AsRef<Vector>(_AxisOffset);
  }
  private static readonly nint _EnabledOffset = Schema.GetOffset(0x96CA23216154EB7E);

  public ref bool Enabled {
    get => ref _Handle.AsRef<bool>(_EnabledOffset);
  }
  private static readonly nint _PrevVelocityOffset = Schema.GetOffset(0x96CA23211F9ACE5F);

  public ref float PrevVelocity {
    get => ref _Handle.AsRef<float>(_PrevVelocityOffset);
  }
  private static readonly nint _AvgIntervalOffset = Schema.GetOffset(0x96CA2321D6693004);

  public ref float AvgInterval {
    get => ref _Handle.AsRef<float>(_AvgIntervalOffset);
  }
  private static readonly nint _VelocityOffset = Schema.GetOffset(0x96CA23219B4CC8B2);

  public SchemaUntypedField Velocity {
    get => new SchemaUntypedField(_Handle + _VelocityOffset);
  }


}