// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPulseCell_Outflow_ScriptedSequenceImpl : CPulseCell_BaseYieldingInflowImpl, CPulseCell_Outflow_ScriptedSequence {

  public CPulseCell_Outflow_ScriptedSequenceImpl(nint handle) : base(handle) {
  }

  private static readonly nint _SyncGroupOffset = Schema.GetOffset(0x462EA7DEF9E8183A);

  public string SyncGroup {
    get {
      var ptr = _Handle.Read<nint>(_SyncGroupOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _SyncGroupOffset, value);
  } 
  private static readonly nint _ExpectedNumSequencesInSyncGroupOffset = Schema.GetOffset(0x462EA7DE0C6AAD7A);

  public ref int ExpectedNumSequencesInSyncGroup {
    get => ref _Handle.AsRef<int>(_ExpectedNumSequencesInSyncGroupOffset);
  }
  private static readonly nint _EnsureOnNavmeshOnFinishOffset = Schema.GetOffset(0x462EA7DE802BA0B0);

  public ref bool EnsureOnNavmeshOnFinish {
    get => ref _Handle.AsRef<bool>(_EnsureOnNavmeshOnFinishOffset);
  }
  private static readonly nint _DontTeleportAtEndOffset = Schema.GetOffset(0x462EA7DE59E02641);

  public ref bool DontTeleportAtEnd {
    get => ref _Handle.AsRef<bool>(_DontTeleportAtEndOffset);
  }
  private static readonly nint _DisallowInterruptsOffset = Schema.GetOffset(0x462EA7DE939D3840);

  public ref bool DisallowInterrupts {
    get => ref _Handle.AsRef<bool>(_DisallowInterruptsOffset);
  }
  private static readonly nint _ScriptedSequenceDataMainOffset = Schema.GetOffset(0x462EA7DE03F2FF03);

  public PulseScriptedSequenceData_t ScriptedSequenceDataMain {
    get => new PulseScriptedSequenceData_tImpl(_Handle + _ScriptedSequenceDataMainOffset);
  }
  private static readonly nint _AdditionalActorsOffset = Schema.GetOffset(0x462EA7DE8E5DB532);

  public ref CUtlVector<PulseScriptedSequenceData_t> AdditionalActors {
    get => ref _Handle.AsRef<CUtlVector<PulseScriptedSequenceData_t>>(_AdditionalActorsOffset);
  }
  private static readonly nint _OnFinishedOffset = Schema.GetOffset(0x462EA7DE8D903E5E);

  public CPulse_ResumePoint OnFinished {
    get => new CPulse_ResumePointImpl(_Handle + _OnFinishedOffset);
  }
  private static readonly nint _OnCanceledOffset = Schema.GetOffset(0x462EA7DEF02162DB);

  public CPulse_ResumePoint OnCanceled {
    get => new CPulse_ResumePointImpl(_Handle + _OnCanceledOffset);
  }
  private static readonly nint _TriggersOffset = Schema.GetOffset(0x462EA7DE6E7B12D0);

  public ref CUtlVector<CPulse_OutflowConnection> Triggers {
    get => ref _Handle.AsRef<CUtlVector<CPulse_OutflowConnection>>(_TriggersOffset);
  }


}