// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPulseCell_WaitForCursorsWithTagBaseImpl : CPulseCell_BaseYieldingInflowImpl, CPulseCell_WaitForCursorsWithTagBase {

  public CPulseCell_WaitForCursorsWithTagBaseImpl(nint handle) : base(handle) {
  }

  private static readonly nint _CursorsAllowedToWaitOffset = Schema.GetOffset(0xA8108DB0236617EC);

  public ref int CursorsAllowedToWait {
    get => ref _Handle.AsRef<int>(_CursorsAllowedToWaitOffset);
  }
  private static readonly nint _WaitCompleteOffset = Schema.GetOffset(0xA8108DB02C41AD97);

  public CPulse_ResumePoint WaitComplete {
    get => new CPulse_ResumePointImpl(_Handle + _WaitCompleteOffset);
  }


}