// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPulseTurtleGraphicsCursorImpl : CPulseExecCursorImpl, CPulseTurtleGraphicsCursor {

  public CPulseTurtleGraphicsCursorImpl(nint handle) : base(handle) {
  }

  private static readonly nint _ColorOffset = Schema.GetOffset(0x6153058ED7D017D8);

  public ref Color Color {
    get => ref _Handle.AsRef<Color>(_ColorOffset);
  }
  private static readonly nint _PosOffset = Schema.GetOffset(0x6153058EDE9CFC5D);

  public ref Vector2D Pos {
    get => ref _Handle.AsRef<Vector2D>(_PosOffset);
  }
  private static readonly nint _HeadingDegOffset = Schema.GetOffset(0x6153058E63288B7D);

  public ref float HeadingDeg {
    get => ref _Handle.AsRef<float>(_HeadingDegOffset);
  }
  private static readonly nint _PenUpOffset = Schema.GetOffset(0x6153058E2252C6FD);

  public ref bool PenUp {
    get => ref _Handle.AsRef<bool>(_PenUpOffset);
  }


}