// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPulseCell_Step_TestDomainEntFireImpl : CPulseCell_BaseFlowImpl, CPulseCell_Step_TestDomainEntFire {

  public CPulseCell_Step_TestDomainEntFireImpl(nint handle) : base(handle) {
  }

  private static readonly nint _InputOffset = Schema.GetOffset(0x22A0E258942A24FB);

  public string Input {
    get {
      var ptr = _Handle.Read<nint>(_InputOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _InputOffset, value);
  } 


}