// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPulseCell_Outflow_ListenForAnimgraphTagImpl : CPulseCell_BaseYieldingInflowImpl, CPulseCell_Outflow_ListenForAnimgraphTag {

  public CPulseCell_Outflow_ListenForAnimgraphTagImpl(nint handle) : base(handle) {
  }

  private static readonly nint _OnStartOffset = Schema.GetOffset(0xAD79BF78C3FE848C);

  public CPulse_ResumePoint OnStart {
    get => new CPulse_ResumePointImpl(_Handle + _OnStartOffset);
  }
  private static readonly nint _OnEndOffset = Schema.GetOffset(0xAD79BF78B88A4375);

  public CPulse_ResumePoint OnEnd {
    get => new CPulse_ResumePointImpl(_Handle + _OnEndOffset);
  }
  private static readonly nint _OnCanceledOffset = Schema.GetOffset(0xAD79BF78F02162DB);

  public CPulse_ResumePoint OnCanceled {
    get => new CPulse_ResumePointImpl(_Handle + _OnCanceledOffset);
  }
  private static readonly nint _TagNameOffset = Schema.GetOffset(0xAD79BF78647DC278);

  public ref CGlobalSymbol TagName {
    get => ref _Handle.AsRef<CGlobalSymbol>(_TagNameOffset);
  }


}