// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPulse_BlackboardReferenceImpl : SchemaClass, CPulse_BlackboardReference {

  public CPulse_BlackboardReferenceImpl(nint handle) : base(handle) {
  }

  private static readonly nint _BlackboardResourceOffset = Schema.GetOffset(0xEF83970A45E704DE);

  public ref CStrongHandle<InfoForResourceTypeIPulseGraphDef> BlackboardResource {
    get => ref _Handle.AsRef<CStrongHandle<InfoForResourceTypeIPulseGraphDef>>(_BlackboardResourceOffset);
  }
  private static readonly nint _BlackboardResource1Offset = Schema.GetOffset(0xEF83970A83127470);

  public SchemaUntypedField BlackboardResource1 {
    get => new SchemaUntypedField(_Handle + _BlackboardResource1Offset);
  }
  private static readonly nint _NodeIDOffset = Schema.GetOffset(0xEF83970A0FD6755C);

  public PulseDocNodeID_t NodeID {
    get => new PulseDocNodeID_tImpl(_Handle + _NodeIDOffset);
  }
  private static readonly nint _NodeNameOffset = Schema.GetOffset(0xEF83970A3FB4DAAE);

  public ref CGlobalSymbol NodeName {
    get => ref _Handle.AsRef<CGlobalSymbol>(_NodeNameOffset);
  }


}