// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CRagdollMagnetImpl : CPointEntityImpl, CRagdollMagnet {

  public CRagdollMagnetImpl(nint handle) : base(handle) {
  }

  private static readonly nint _DisabledOffset = Schema.GetOffset(0x7C6BA43F3A7C5965);

  public ref bool Disabled {
    get => ref _Handle.AsRef<bool>(_DisabledOffset);
  }
  private static readonly nint _RadiusOffset = Schema.GetOffset(0x7C6BA43FA921CA53);

  public ref float Radius {
    get => ref _Handle.AsRef<float>(_RadiusOffset);
  }
  private static readonly nint _ForceOffset = Schema.GetOffset(0x7C6BA43FB9B6AFA4);

  public ref float Force {
    get => ref _Handle.AsRef<float>(_ForceOffset);
  }
  private static readonly nint _AxisOffset = Schema.GetOffset(0x7C6BA43F2B06DE94);

  public ref Vector Axis {
    get => ref _Handle.AsRef<Vector>(_AxisOffset);
  }


}