// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CRandSimTimerImpl : CSimpleSimTimerImpl, CRandSimTimer {

  public CRandSimTimerImpl(nint handle) : base(handle) {
  }

  private static readonly nint _MinIntervalOffset = Schema.GetOffset(0x6268F694BB35EE4);

  public ref float MinInterval {
    get => ref _Handle.AsRef<float>(_MinIntervalOffset);
  }
  private static readonly nint _MaxIntervalOffset = Schema.GetOffset(0x6268F69400B2156);

  public ref float MaxInterval {
    get => ref _Handle.AsRef<float>(_MaxIntervalOffset);
  }


}