// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CRelativeLocationImpl : SchemaClass, CRelativeLocation {

  public CRelativeLocationImpl(nint handle) : base(handle) {
  }

  private static readonly nint _TypeOffset = Schema.GetOffset(0xA25CE2418ED6D5CD);

  public ref RelativeLocationType_t Type {
    get => ref _Handle.AsRef<RelativeLocationType_t>(_TypeOffset);
  }
  private static readonly nint _RelativeOffsetOffset = Schema.GetOffset(0xA25CE241B6F2D296);

  public ref Vector RelativeOffset {
    get => ref _Handle.AsRef<Vector>(_RelativeOffsetOffset);
  }
  private static readonly nint _WorldSpacePosOffset = Schema.GetOffset(0xA25CE2410A43E96B);

  public ref Vector WorldSpacePos {
    get => ref _Handle.AsRef<Vector>(_WorldSpacePosOffset);
  }
  private static readonly nint _EntityOffset = Schema.GetOffset(0xA25CE2416EBADCB0);

  public ref CHandle<CBaseEntity> Entity {
    get => ref _Handle.AsRef<CHandle<CBaseEntity>>(_EntityOffset);
  }


}