// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CRenderComponentImpl : CEntityComponentImpl, CRenderComponent {

  public CRenderComponentImpl(nint handle) : base(handle) {
  }

  private static readonly nint ___m_pChainEntityOffset = Schema.GetOffset(0x8830FA5F63F0E7D);

  public ref CNetworkVarChainer __m_pChainEntity {
    get => ref _Handle.AsRef<CNetworkVarChainer>(___m_pChainEntityOffset);
  }
  private static readonly nint _IsRenderingWithViewModelsOffset = Schema.GetOffset(0x8830FA5700AA428);

  public ref bool IsRenderingWithViewModels {
    get => ref _Handle.AsRef<bool>(_IsRenderingWithViewModelsOffset);
  }
  private static readonly nint _SplitscreenFlagsOffset = Schema.GetOffset(0x8830FA5CACF9032);

  public ref uint SplitscreenFlags {
    get => ref _Handle.AsRef<uint>(_SplitscreenFlagsOffset);
  }
  private static readonly nint _EnableRenderingOffset = Schema.GetOffset(0x8830FA50FAC7C5E);

  public ref bool EnableRendering {
    get => ref _Handle.AsRef<bool>(_EnableRenderingOffset);
  }
  private static readonly nint _InterpolationReadyToDrawOffset = Schema.GetOffset(0x8830FA51A075A53);

  public ref bool InterpolationReadyToDraw {
    get => ref _Handle.AsRef<bool>(_InterpolationReadyToDrawOffset);
  }


}