// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CSceneListManagerImpl : CLogicalEntityImpl, CSceneListManager {

  public CSceneListManagerImpl(nint handle) : base(handle) {
  }

  private static readonly nint _ListManagersOffset = Schema.GetOffset(0x6DF51C6DAD7882DF);

  public ref CUtlVector<CHandle<CSceneListManager>> ListManagers {
    get => ref _Handle.AsRef<CUtlVector<CHandle<CSceneListManager>>>(_ListManagersOffset);
  }
  private static readonly nint _ScenesOffset = Schema.GetOffset(0x6DF51C6D967363E8);

  public string Scenes {
    get {
      var ptr = _Handle.Read<nint>(_ScenesOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _ScenesOffset, value);
  } 
  public ISchemaFixedArray<CHandle<CBaseEntity>> Scenes1 {
    get => new SchemaFixedArray<CHandle<CBaseEntity>>(_Handle, 0x6DF51C6D2B7EE872, 16, 4, 4);
  }


}