// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CShatterGlassShardImpl : SchemaClass, CShatterGlassShard {

  public CShatterGlassShardImpl(nint handle) : base(handle) {
  }

  private static readonly nint _ShardHandleOffset = Schema.GetOffset(0x1350BEC3018E384F);

  public ref uint ShardHandle {
    get => ref _Handle.AsRef<uint>(_ShardHandleOffset);
  }
  private static readonly nint _PanelVerticesOffset = Schema.GetOffset(0x1350BEC349BB3ECE);

  public ref CUtlVector<Vector2D> PanelVertices {
    get => ref _Handle.AsRef<CUtlVector<Vector2D>>(_PanelVerticesOffset);
  }
  private static readonly nint _LocalPanelSpaceOriginOffset = Schema.GetOffset(0x1350BEC3D2F782FE);

  public ref Vector2D LocalPanelSpaceOrigin {
    get => ref _Handle.AsRef<Vector2D>(_LocalPanelSpaceOriginOffset);
  }
  private static readonly nint _ModelOffset = Schema.GetOffset(0x1350BEC3E100C814);

  public ref CStrongHandle<InfoForResourceTypeCModel> Model {
    get => ref _Handle.AsRef<CStrongHandle<InfoForResourceTypeCModel>>(_ModelOffset);
  }
  private static readonly nint _PhysicsEntityOffset = Schema.GetOffset(0x1350BEC396EA280F);

  public ref CHandle<CShatterGlassShardPhysics> PhysicsEntity {
    get => ref _Handle.AsRef<CHandle<CShatterGlassShardPhysics>>(_PhysicsEntityOffset);
  }
  private static readonly nint _ParentPanelOffset = Schema.GetOffset(0x1350BEC3385216AF);

  public ref CHandle<CFuncShatterglass> ParentPanel {
    get => ref _Handle.AsRef<CHandle<CFuncShatterglass>>(_ParentPanelOffset);
  }
  private static readonly nint _ParentShardOffset = Schema.GetOffset(0x1350BEC3E3717B41);

  public ref uint ParentShard {
    get => ref _Handle.AsRef<uint>(_ParentShardOffset);
  }
  private static readonly nint _ShatterStressTypeOffset = Schema.GetOffset(0x1350BEC300D3667A);

  public ref ShatterGlassStressType ShatterStressType {
    get => ref _Handle.AsRef<ShatterGlassStressType>(_ShatterStressTypeOffset);
  }
  private static readonly nint _StressVelocityOffset = Schema.GetOffset(0x1350BEC3A4B62C52);

  public ref Vector StressVelocity {
    get => ref _Handle.AsRef<Vector>(_StressVelocityOffset);
  }
  private static readonly nint _CreatedModelOffset = Schema.GetOffset(0x1350BEC3CC206618);

  public ref bool CreatedModel {
    get => ref _Handle.AsRef<bool>(_CreatedModelOffset);
  }
  private static readonly nint _LongestEdgeOffset = Schema.GetOffset(0x1350BEC3B6906D8E);

  public ref float LongestEdge {
    get => ref _Handle.AsRef<float>(_LongestEdgeOffset);
  }
  private static readonly nint _ShortestEdgeOffset = Schema.GetOffset(0x1350BEC30012FB38);

  public ref float ShortestEdge {
    get => ref _Handle.AsRef<float>(_ShortestEdgeOffset);
  }
  private static readonly nint _LongestAcrossOffset = Schema.GetOffset(0x1350BEC398AEE1F6);

  public ref float LongestAcross {
    get => ref _Handle.AsRef<float>(_LongestAcrossOffset);
  }
  private static readonly nint _ShortestAcrossOffset = Schema.GetOffset(0x1350BEC3A14E5348);

  public ref float ShortestAcross {
    get => ref _Handle.AsRef<float>(_ShortestAcrossOffset);
  }
  private static readonly nint _SumOfAllEdgesOffset = Schema.GetOffset(0x1350BEC31E8C597C);

  public ref float SumOfAllEdges {
    get => ref _Handle.AsRef<float>(_SumOfAllEdgesOffset);
  }
  private static readonly nint _AreaOffset = Schema.GetOffset(0x1350BEC3623D1622);

  public ref float Area {
    get => ref _Handle.AsRef<float>(_AreaOffset);
  }
  private static readonly nint _OnFrameEdgeOffset = Schema.GetOffset(0x1350BEC34F0A3650);

  public ref OnFrame OnFrameEdge {
    get => ref _Handle.AsRef<OnFrame>(_OnFrameEdgeOffset);
  }
  private static readonly nint _SubShardGenerationOffset = Schema.GetOffset(0x1350BEC34106ACCD);

  public ref int SubShardGeneration {
    get => ref _Handle.AsRef<int>(_SubShardGenerationOffset);
  }
  private static readonly nint _AverageVertPositionOffset = Schema.GetOffset(0x1350BEC302B48078);

  public ref Vector2D AverageVertPosition {
    get => ref _Handle.AsRef<Vector2D>(_AverageVertPositionOffset);
  }
  private static readonly nint _AverageVertPositionIsValidOffset = Schema.GetOffset(0x1350BEC33261C872);

  public ref bool AverageVertPositionIsValid {
    get => ref _Handle.AsRef<bool>(_AverageVertPositionIsValidOffset);
  }
  private static readonly nint _PanelSpaceStressPositionAOffset = Schema.GetOffset(0x1350BEC34DFDAE31);

  public ref Vector2D PanelSpaceStressPositionA {
    get => ref _Handle.AsRef<Vector2D>(_PanelSpaceStressPositionAOffset);
  }
  private static readonly nint _PanelSpaceStressPositionBOffset = Schema.GetOffset(0x1350BEC34AFDA978);

  public ref Vector2D PanelSpaceStressPositionB {
    get => ref _Handle.AsRef<Vector2D>(_PanelSpaceStressPositionBOffset);
  }
  private static readonly nint _StressPositionAIsValidOffset = Schema.GetOffset(0x1350BEC39B0D4BAD);

  public ref bool StressPositionAIsValid {
    get => ref _Handle.AsRef<bool>(_StressPositionAIsValidOffset);
  }
  private static readonly nint _StressPositionBIsValidOffset = Schema.GetOffset(0x1350BEC32AC62BB2);

  public ref bool StressPositionBIsValid {
    get => ref _Handle.AsRef<bool>(_StressPositionBIsValidOffset);
  }
  private static readonly nint _FlaggedForRemovalOffset = Schema.GetOffset(0x1350BEC35D1816FC);

  public ref bool FlaggedForRemoval {
    get => ref _Handle.AsRef<bool>(_FlaggedForRemovalOffset);
  }
  private static readonly nint _PhysicsEntitySpawnedAtTimeOffset = Schema.GetOffset(0x1350BEC3AA81B16F);

  public GameTime_t PhysicsEntitySpawnedAtTime {
    get => new GameTime_tImpl(_Handle + _PhysicsEntitySpawnedAtTimeOffset);
  }
  private static readonly nint _EntityHittingMeOffset = Schema.GetOffset(0x1350BEC3820AF257);

  public ref CHandle<CBaseEntity> EntityHittingMe {
    get => ref _Handle.AsRef<CHandle<CBaseEntity>>(_EntityHittingMeOffset);
  }
  private static readonly nint _NeighborsOffset = Schema.GetOffset(0x1350BEC3622F1068);

  public ref CUtlVector<uint> Neighbors {
    get => ref _Handle.AsRef<CUtlVector<uint>>(_NeighborsOffset);
  }


}