// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CSkeletonInstanceImpl : CGameSceneNodeImpl, CSkeletonInstance {

  public CSkeletonInstanceImpl(nint handle) : base(handle) {
  }

  private static readonly nint _ModelStateOffset = Schema.GetOffset(0xD6C6252E52AC8C4F);

  public CModelState ModelState {
    get => new CModelStateImpl(_Handle + _ModelStateOffset);
  }
  private static readonly nint _IsAnimationEnabledOffset = Schema.GetOffset(0xD6C6252E44F0C816);

  public ref bool IsAnimationEnabled {
    get => ref _Handle.AsRef<bool>(_IsAnimationEnabledOffset);
  }
  private static readonly nint _UseParentRenderBoundsOffset = Schema.GetOffset(0xD6C6252E15B8267D);

  public ref bool UseParentRenderBounds {
    get => ref _Handle.AsRef<bool>(_UseParentRenderBoundsOffset);
  }
  private static readonly nint _DisableSolidCollisionsForHierarchyOffset = Schema.GetOffset(0xD6C6252E50FCF465);

  public ref bool DisableSolidCollisionsForHierarchy {
    get => ref _Handle.AsRef<bool>(_DisableSolidCollisionsForHierarchyOffset);
  }
  private static readonly nint _DirtyMotionTypeOffset = Schema.GetOffset(0xD6C6252E6EB99391);

  public SchemaUntypedField DirtyMotionType {
    get => new SchemaUntypedField(_Handle + _DirtyMotionTypeOffset);
  }
  private static readonly nint _IsGeneratingLatchedParentSpaceStateOffset = Schema.GetOffset(0xD6C6252ED0EFEAB7);

  public SchemaUntypedField IsGeneratingLatchedParentSpaceState {
    get => new SchemaUntypedField(_Handle + _IsGeneratingLatchedParentSpaceStateOffset);
  }
  private static readonly nint _MaterialGroupOffset = Schema.GetOffset(0xD6C6252E2B778F03);

  public ref CUtlStringToken MaterialGroup {
    get => ref _Handle.AsRef<CUtlStringToken>(_MaterialGroupOffset);
  }
  private static readonly nint _HitboxSetOffset = Schema.GetOffset(0xD6C6252E80C42271);

  public ref byte HitboxSet {
    get => ref _Handle.AsRef<byte>(_HitboxSetOffset);
  }

  public void ModelStateUpdated() {
    Schema.Update(_Handle, 0xD6C6252E52AC8C4F);
  }
  public void IsAnimationEnabledUpdated() {
    Schema.Update(_Handle, 0xD6C6252E44F0C816);
  }
  public void UseParentRenderBoundsUpdated() {
    Schema.Update(_Handle, 0xD6C6252E15B8267D);
  }
  public void MaterialGroupUpdated() {
    Schema.Update(_Handle, 0xD6C6252E2B778F03);
  }
  public void HitboxSetUpdated() {
    Schema.Update(_Handle, 0xD6C6252E80C42271);
  }
}