// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CSosGroupActionSoundeventPrioritySchemaImpl : CSosGroupActionSchemaImpl, CSosGroupActionSoundeventPrioritySchema {

  public CSosGroupActionSoundeventPrioritySchemaImpl(nint handle) : base(handle) {
  }

  private static readonly nint _PriorityValueOffset = Schema.GetOffset(0x1E84D860257F7BF6);

  public string PriorityValue {
    get {
      var ptr = _Handle.Read<nint>(_PriorityValueOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _PriorityValueOffset, value);
  } 
  private static readonly nint _PriorityVolumeScalarOffset = Schema.GetOffset(0x1E84D860F21824AF);

  public string PriorityVolumeScalar {
    get {
      var ptr = _Handle.Read<nint>(_PriorityVolumeScalarOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _PriorityVolumeScalarOffset, value);
  } 
  private static readonly nint _PriorityContributeButDontReadOffset = Schema.GetOffset(0x1E84D8608078C7B6);

  public string PriorityContributeButDontRead {
    get {
      var ptr = _Handle.Read<nint>(_PriorityContributeButDontReadOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _PriorityContributeButDontReadOffset, value);
  } 
  private static readonly nint _PriorityReadButDontContributeOffset = Schema.GetOffset(0x1E84D860112DDB84);

  public string PriorityReadButDontContribute {
    get {
      var ptr = _Handle.Read<nint>(_PriorityReadButDontContributeOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _PriorityReadButDontContributeOffset, value);
  } 


}