// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CSoundEventAABBEntityImpl : CSoundEventEntityImpl, CSoundEventAABBEntity {

  public CSoundEventAABBEntityImpl(nint handle) : base(handle) {
  }

  private static readonly nint _MinsOffset = Schema.GetOffset(0x9E5B084A421BB730);

  public ref Vector Mins {
    get => ref _Handle.AsRef<Vector>(_MinsOffset);
  }
  private static readonly nint _MaxsOffset = Schema.GetOffset(0x9E5B084AC0C1CE6A);

  public ref Vector Maxs {
    get => ref _Handle.AsRef<Vector>(_MaxsOffset);
  }

  public void MinsUpdated() {
    Schema.Update(_Handle, 0x9E5B084A421BB730);
  }
  public void MaxsUpdated() {
    Schema.Update(_Handle, 0x9E5B084AC0C1CE6A);
  }
}