// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CStateActionUpdaterImpl : SchemaClass, CStateActionUpdater {

  public CStateActionUpdaterImpl(nint handle) : base(handle) {
  }

  private static readonly nint _ActionOffset = Schema.GetOffset(0xCA33DCAAE9CB47D5);

  public SchemaUntypedField Action {
    get => new SchemaUntypedField(_Handle + _ActionOffset);
  }
  private static readonly nint _BehaviorOffset = Schema.GetOffset(0xCA33DCAA436DB10A);

  public ref StateActionBehavior Behavior {
    get => ref _Handle.AsRef<StateActionBehavior>(_BehaviorOffset);
  }


}