// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CTargetSelectorUpdateNodeImpl : CAnimUpdateNodeBaseImpl, CTargetSelectorUpdateNode {

  public CTargetSelectorUpdateNodeImpl(nint handle) : base(handle) {
  }

  private static readonly nint _AngleModeOffset = Schema.GetOffset(0x37AB6CCBD21DC8BC);

  public ref TargetSelectorAngleMode_t AngleMode {
    get => ref _Handle.AsRef<TargetSelectorAngleMode_t>(_AngleModeOffset);
  }
  private static readonly nint _ChildrenOffset = Schema.GetOffset(0x37AB6CCB7415FA72);

  public ref CUtlVector<CAnimUpdateNodeRef> Children {
    get => ref _Handle.AsRef<CUtlVector<CAnimUpdateNodeRef>>(_ChildrenOffset);
  }
  private static readonly nint _TargetPositionOffset = Schema.GetOffset(0x37AB6CCBD1F40125);

  public CAnimParamHandle TargetPosition {
    get => new CAnimParamHandleImpl(_Handle + _TargetPositionOffset);
  }
  private static readonly nint _TargetFacePositionParameterOffset = Schema.GetOffset(0x37AB6CCB1102D56F);

  public CAnimParamHandle TargetFacePositionParameter {
    get => new CAnimParamHandleImpl(_Handle + _TargetFacePositionParameterOffset);
  }
  private static readonly nint _MoveHeadingParameterOffset = Schema.GetOffset(0x37AB6CCB3A7267CF);

  public CAnimParamHandle MoveHeadingParameter {
    get => new CAnimParamHandleImpl(_Handle + _MoveHeadingParameterOffset);
  }
  private static readonly nint _DesiredMoveHeadingParameterOffset = Schema.GetOffset(0x37AB6CCBC6298DFB);

  public CAnimParamHandle DesiredMoveHeadingParameter {
    get => new CAnimParamHandleImpl(_Handle + _DesiredMoveHeadingParameterOffset);
  }
  private static readonly nint _TargetPositionIsWorldSpaceOffset = Schema.GetOffset(0x37AB6CCBABCF9ECD);

  public ref bool TargetPositionIsWorldSpace {
    get => ref _Handle.AsRef<bool>(_TargetPositionIsWorldSpaceOffset);
  }
  private static readonly nint _TargetFacePositionIsWorldSpaceOffset = Schema.GetOffset(0x37AB6CCB504B4258);

  public ref bool TargetFacePositionIsWorldSpace {
    get => ref _Handle.AsRef<bool>(_TargetFacePositionIsWorldSpaceOffset);
  }
  private static readonly nint _EnablePhaseMatchingOffset = Schema.GetOffset(0x37AB6CCB6BC1372A);

  public ref bool EnablePhaseMatching {
    get => ref _Handle.AsRef<bool>(_EnablePhaseMatchingOffset);
  }
  private static readonly nint _PhaseMatchingMaxRootMotionSkipOffset = Schema.GetOffset(0x37AB6CCB547A4008);

  public ref float PhaseMatchingMaxRootMotionSkip {
    get => ref _Handle.AsRef<float>(_PhaseMatchingMaxRootMotionSkipOffset);
  }


}