// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CTonemapTriggerImpl : CBaseTriggerImpl, CTonemapTrigger {

  public CTonemapTriggerImpl(nint handle) : base(handle) {
  }

  private static readonly nint _TonemapControllerNameOffset = Schema.GetOffset(0x82562698C641A282);

  public string TonemapControllerName {
    get {
      var ptr = _Handle.Read<nint>(_TonemapControllerNameOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _TonemapControllerNameOffset, value);
  } 
  private static readonly nint _TonemapControllerOffset = Schema.GetOffset(0x82562698F5E1A34F);

  public ref CHandle<CEntityInstance> TonemapController {
    get => ref _Handle.AsRef<CHandle<CEntityInstance>>(_TonemapControllerOffset);
  }


}