// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CTriggerPushImpl : CBaseTriggerImpl, CTriggerPush {

  public CTriggerPushImpl(nint handle) : base(handle) {
  }

  private static readonly nint _PushEntitySpaceOffset = Schema.GetOffset(0x92E0F2F21952BFD6);

  public ref QAngle PushEntitySpace {
    get => ref _Handle.AsRef<QAngle>(_PushEntitySpaceOffset);
  }
  private static readonly nint _PushDirEntitySpaceOffset = Schema.GetOffset(0x92E0F2F2A3C4D4F3);

  public ref Vector PushDirEntitySpace {
    get => ref _Handle.AsRef<Vector>(_PushDirEntitySpaceOffset);
  }
  private static readonly nint _TriggerOnStartTouchOffset = Schema.GetOffset(0x92E0F2F2365C0A51);

  public ref bool TriggerOnStartTouch {
    get => ref _Handle.AsRef<bool>(_TriggerOnStartTouchOffset);
  }
  private static readonly nint _UsePathSimpleOffset = Schema.GetOffset(0x92E0F2F21BFD6EF1);

  public ref bool UsePathSimple {
    get => ref _Handle.AsRef<bool>(_UsePathSimpleOffset);
  }
  private static readonly nint _PathSimpleNameOffset = Schema.GetOffset(0x92E0F2F2AB7E7D7F);

  public string PathSimpleName {
    get {
      var ptr = _Handle.Read<nint>(_PathSimpleNameOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _PathSimpleNameOffset, value);
  } 
  private static readonly nint _PathSimpleOffset = Schema.GetOffset(0x92E0F2F2FA868DCC);

  public CPathSimple? PathSimple {
    get {
      var ptr = _Handle.Read<nint>(_PathSimpleOffset);
      return ptr.IsValidPtr() ? new CPathSimpleImpl(ptr) : null;
    }
  }
  private static readonly nint _SplinePushTypeOffset = Schema.GetOffset(0x92E0F2F229A29DE0);

  public ref uint SplinePushType {
    get => ref _Handle.AsRef<uint>(_SplinePushTypeOffset);
  }


}