// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CTriggerGameEventImpl : CBaseTriggerImpl, CTriggerGameEvent {

  public CTriggerGameEventImpl(nint handle) : base(handle) {
  }

  private static readonly nint _StrStartTouchEventNameOffset = Schema.GetOffset(0xF8B194884B1EB67A);

  public string StrStartTouchEventName {
    get {
      var ptr = _Handle.Read<nint>(_StrStartTouchEventNameOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _StrStartTouchEventNameOffset, value);
  } 
  private static readonly nint _StrEndTouchEventNameOffset = Schema.GetOffset(0xF8B194886EDE6893);

  public string StrEndTouchEventName {
    get {
      var ptr = _Handle.Read<nint>(_StrEndTouchEventNameOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _StrEndTouchEventNameOffset, value);
  } 
  private static readonly nint _StrTriggerIDOffset = Schema.GetOffset(0xF8B19488EA731D41);

  public string StrTriggerID {
    get {
      var ptr = _Handle.Read<nint>(_StrTriggerIDOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _StrTriggerIDOffset, value);
  } 

  public void StrStartTouchEventNameUpdated() {
    Schema.Update(_Handle, 0xF8B194884B1EB67A);
  }
  public void StrEndTouchEventNameUpdated() {
    Schema.Update(_Handle, 0xF8B194886EDE6893);
  }
  public void StrTriggerIDUpdated() {
    Schema.Update(_Handle, 0xF8B19488EA731D41);
  }
}