// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CTriggerVolumeImpl : CBaseModelEntityImpl, CTriggerVolume {

  public CTriggerVolumeImpl(nint handle) : base(handle) {
  }

  private static readonly nint _FilterNameOffset = Schema.GetOffset(0x8A35845409C86445);

  public string FilterName {
    get {
      var ptr = _Handle.Read<nint>(_FilterNameOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _FilterNameOffset, value);
  } 
  private static readonly nint _FilterOffset = Schema.GetOffset(0x8A35845445D9E0B1);

  public ref CHandle<CBaseFilter> Filter {
    get => ref _Handle.AsRef<CHandle<CBaseFilter>>(_FilterOffset);
  }


}