// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CTwistConstraintImpl : CBaseConstraintImpl, CTwistConstraint {

  public CTwistConstraintImpl(nint handle) : base(handle) {
  }

  private static readonly nint _InverseOffset = Schema.GetOffset(0xA3EC320A0DE8C163);

  public ref bool Inverse {
    get => ref _Handle.AsRef<bool>(_InverseOffset);
  }
  private static readonly nint _ParentBindRotationOffset = Schema.GetOffset(0xA3EC320AE46C74E5);

  public ref Quaternion ParentBindRotation {
    get => ref _Handle.AsRef<Quaternion>(_ParentBindRotationOffset);
  }
  private static readonly nint _ChildBindRotationOffset = Schema.GetOffset(0xA3EC320A0FCDDACB);

  public ref Quaternion ChildBindRotation {
    get => ref _Handle.AsRef<Quaternion>(_ChildBindRotationOffset);
  }


}