// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CVoiceContainerStaticAdditiveSynth__CGainScalePerInstanceImpl : SchemaClass, CVoiceContainerStaticAdditiveSynth__CGainScalePerInstance {

  public CVoiceContainerStaticAdditiveSynth__CGainScalePerInstanceImpl(nint handle) : base(handle) {
  }

  private static readonly nint _MinVolumeOffset = Schema.GetOffset(0x9089F81B2CA4E2A3);

  public ref float MinVolume {
    get => ref _Handle.AsRef<float>(_MinVolumeOffset);
  }
  private static readonly nint _InstancesAtMinVolumeOffset = Schema.GetOffset(0x9089F81BBA3DF3B8);

  public ref int InstancesAtMinVolume {
    get => ref _Handle.AsRef<int>(_InstancesAtMinVolumeOffset);
  }
  private static readonly nint _MaxVolumeOffset = Schema.GetOffset(0x9089F81B25691B11);

  public ref float MaxVolume {
    get => ref _Handle.AsRef<float>(_MaxVolumeOffset);
  }
  private static readonly nint _InstancesAtMaxVolumeOffset = Schema.GetOffset(0x9089F81B18EB3E46);

  public ref int InstancesAtMaxVolume {
    get => ref _Handle.AsRef<int>(_InstancesAtMaxVolumeOffset);
  }


}