// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class EventClientOutput_tImpl : SchemaClass, EventClientOutput_t {

  public EventClientOutput_tImpl(nint handle) : base(handle) {
  }

  private static readonly nint _LoopStateOffset = Schema.GetOffset(0xDC610E16F928A2EC);

  public EngineLoopState_t LoopState {
    get => new EngineLoopState_tImpl(_Handle + _LoopStateOffset);
  }
  private static readonly nint _RenderTimeOffset = Schema.GetOffset(0xDC610E163C2AE65A);

  public ref float RenderTime {
    get => ref _Handle.AsRef<float>(_RenderTimeOffset);
  }
  private static readonly nint _RealTimeOffset = Schema.GetOffset(0xDC610E161168EC02);

  public ref float RealTime {
    get => ref _Handle.AsRef<float>(_RealTimeOffset);
  }
  private static readonly nint _RenderFrameTimeUnboundedOffset = Schema.GetOffset(0xDC610E16735692FF);

  public ref float RenderFrameTimeUnbounded {
    get => ref _Handle.AsRef<float>(_RenderFrameTimeUnboundedOffset);
  }
  private static readonly nint _RenderOnlyOffset = Schema.GetOffset(0xDC610E16E274559F);

  public ref bool RenderOnly {
    get => ref _Handle.AsRef<bool>(_RenderOnlyOffset);
  }


}