// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class EventClientPreOutput_tImpl : SchemaClass, EventClientPreOutput_t {

  public EventClientPreOutput_tImpl(nint handle) : base(handle) {
  }

  private static readonly nint _LoopStateOffset = Schema.GetOffset(0xB79CB11BF928A2EC);

  public EngineLoopState_t LoopState {
    get => new EngineLoopState_tImpl(_Handle + _LoopStateOffset);
  }
  private static readonly nint _RenderTimeOffset = Schema.GetOffset(0xB79CB11B3C2AE65A);

  public ref double RenderTime {
    get => ref _Handle.AsRef<double>(_RenderTimeOffset);
  }
  private static readonly nint _RenderFrameTimeOffset = Schema.GetOffset(0xB79CB11BF2FB2D81);

  public ref double RenderFrameTime {
    get => ref _Handle.AsRef<double>(_RenderFrameTimeOffset);
  }
  private static readonly nint _RenderFrameTimeUnboundedOffset = Schema.GetOffset(0xB79CB11B735692FF);

  public ref double RenderFrameTimeUnbounded {
    get => ref _Handle.AsRef<double>(_RenderFrameTimeUnboundedOffset);
  }
  private static readonly nint _RealTimeOffset = Schema.GetOffset(0xB79CB11B1168EC02);

  public ref float RealTime {
    get => ref _Handle.AsRef<float>(_RealTimeOffset);
  }
  private static readonly nint _RenderOnlyOffset = Schema.GetOffset(0xB79CB11BE274559F);

  public ref bool RenderOnly {
    get => ref _Handle.AsRef<bool>(_RenderOnlyOffset);
  }


}