// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class EventClientProcessInput_tImpl : SchemaClass, EventClientProcessInput_t {

  public EventClientProcessInput_tImpl(nint handle) : base(handle) {
  }

  private static readonly nint _LoopStateOffset = Schema.GetOffset(0x406EC290F928A2EC);

  public EngineLoopState_t LoopState {
    get => new EngineLoopState_tImpl(_Handle + _LoopStateOffset);
  }
  private static readonly nint _RealTimeOffset = Schema.GetOffset(0x406EC2901168EC02);

  public ref float RealTime {
    get => ref _Handle.AsRef<float>(_RealTimeOffset);
  }
  private static readonly nint _TickIntervalOffset = Schema.GetOffset(0x406EC290D279D07B);

  public ref float TickInterval {
    get => ref _Handle.AsRef<float>(_TickIntervalOffset);
  }
  private static readonly nint _TickStartTimeOffset = Schema.GetOffset(0x406EC29068A38BE7);

  public ref double TickStartTime {
    get => ref _Handle.AsRef<double>(_TickStartTimeOffset);
  }


}