// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class FeBuildSDFRigid_tImpl : FeSDFRigid_tImpl, FeBuildSDFRigid_t {

  public FeBuildSDFRigid_tImpl(nint handle) : base(handle) {
  }

  private static readonly nint _PriorityOffset = Schema.GetOffset(0x8C389301E7EFB335);

  public ref int Priority {
    get => ref _Handle.AsRef<int>(_PriorityOffset);
  }
  private static readonly nint _VertexMapHashOffset = Schema.GetOffset(0x8C38930106BCA0A3);

  public ref uint VertexMapHash {
    get => ref _Handle.AsRef<uint>(_VertexMapHashOffset);
  }
  private static readonly nint _AntitunnelGroupBitsOffset = Schema.GetOffset(0x8C389301A5C6E91A);

  public ref uint AntitunnelGroupBits {
    get => ref _Handle.AsRef<uint>(_AntitunnelGroupBitsOffset);
  }


}