// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class FeCollisionPlane_tImpl : SchemaClass, FeCollisionPlane_t {

  public FeCollisionPlane_tImpl(nint handle) : base(handle) {
  }

  private static readonly nint _CtrlParentOffset = Schema.GetOffset(0xF8EBA99555049230);

  public ref ushort CtrlParent {
    get => ref _Handle.AsRef<ushort>(_CtrlParentOffset);
  }
  private static readonly nint _ChildNodeOffset = Schema.GetOffset(0xF8EBA99592A8E0E9);

  public ref ushort ChildNode {
    get => ref _Handle.AsRef<ushort>(_ChildNodeOffset);
  }
  private static readonly nint _PlaneOffset = Schema.GetOffset(0xF8EBA995671CB5D5);

  public RnPlane_t Plane {
    get => new RnPlane_tImpl(_Handle + _PlaneOffset);
  }
  private static readonly nint _StrengthOffset = Schema.GetOffset(0xF8EBA995AFA3323A);

  public ref float Strength {
    get => ref _Handle.AsRef<float>(_StrengthOffset);
  }


}