// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class FeFitInfluence_tImpl : SchemaClass, FeFitInfluence_t {

  public FeFitInfluence_tImpl(nint handle) : base(handle) {
  }

  private static readonly nint _VertexNodeOffset = Schema.GetOffset(0xF8271D2105342743);

  public ref uint VertexNode {
    get => ref _Handle.AsRef<uint>(_VertexNodeOffset);
  }
  private static readonly nint _WeightOffset = Schema.GetOffset(0xF8271D21CFFC66CB);

  public ref float Weight {
    get => ref _Handle.AsRef<float>(_WeightOffset);
  }
  private static readonly nint _MatrixNodeOffset = Schema.GetOffset(0xF8271D2189590174);

  public ref uint MatrixNode {
    get => ref _Handle.AsRef<uint>(_MatrixNodeOffset);
  }


}