// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class FeHingeLimit_tImpl : SchemaClass, FeHingeLimit_t {

  public FeHingeLimit_tImpl(nint handle) : base(handle) {
  }

  public ISchemaFixedArray<ushort> Node {
    get => new SchemaFixedArray<ushort>(_Handle, 0x3E7F1FF5CD6694B9, 6, 2, 2);
  }
  private static readonly nint _FlagsOffset = Schema.GetOffset(0x3E7F1FF5B8D52E48);

  public ref uint Flags {
    get => ref _Handle.AsRef<uint>(_FlagsOffset);
  }
  private static readonly nint _Weight4Offset = Schema.GetOffset(0x3E7F1FF56956236D);

  public ref float Weight4 {
    get => ref _Handle.AsRef<float>(_Weight4Offset);
  }
  private static readonly nint _Weight5Offset = Schema.GetOffset(0x3E7F1FF5685621DA);

  public ref float Weight5 {
    get => ref _Handle.AsRef<float>(_Weight5Offset);
  }
  private static readonly nint _AngleCenterOffset = Schema.GetOffset(0x3E7F1FF57BF2D76B);

  public ref float AngleCenter {
    get => ref _Handle.AsRef<float>(_AngleCenterOffset);
  }
  private static readonly nint _AngleExtentsOffset = Schema.GetOffset(0x3E7F1FF59D58EF0B);

  public ref float AngleExtents {
    get => ref _Handle.AsRef<float>(_AngleExtentsOffset);
  }


}