// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class FeRodConstraint_tImpl : SchemaClass, FeRodConstraint_t {

  public FeRodConstraint_tImpl(nint handle) : base(handle) {
  }

  public ISchemaFixedArray<ushort> Node {
    get => new SchemaFixedArray<ushort>(_Handle, 0xC672146DCD6694B9, 2, 2, 2);
  }
  private static readonly nint _MaxDistOffset = Schema.GetOffset(0xC672146DC9FFDD57);

  public ref float MaxDist {
    get => ref _Handle.AsRef<float>(_MaxDistOffset);
  }
  private static readonly nint _MinDistOffset = Schema.GetOffset(0xC672146D2C1C02AD);

  public ref float MinDist {
    get => ref _Handle.AsRef<float>(_MinDistOffset);
  }
  private static readonly nint _Weight0Offset = Schema.GetOffset(0xC672146D65561D21);

  public ref float Weight0 {
    get => ref _Handle.AsRef<float>(_Weight0Offset);
  }
  private static readonly nint _RelaxationFactorOffset = Schema.GetOffset(0xC672146D357F3BFF);

  public ref float RelaxationFactor {
    get => ref _Handle.AsRef<float>(_RelaxationFactorOffset);
  }


}