// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class FeSimdRodConstraint_tImpl : SchemaClass, FeSimdRodConstraint_t {

  public FeSimdRodConstraint_tImpl(nint handle) : base(handle) {
  }

  private static readonly nint _NodeOffset = Schema.GetOffset(0x596F7846CD6694B9);

  public SchemaUntypedField Node {
    get => new SchemaUntypedField(_Handle + _NodeOffset);
  }
  private static readonly nint _F4MaxDistOffset = Schema.GetOffset(0x596F7846287D425F);

  public ref fltx4 F4MaxDist {
    get => ref _Handle.AsRef<fltx4>(_F4MaxDistOffset);
  }
  private static readonly nint _F4MinDistOffset = Schema.GetOffset(0x596F7846C67A2525);

  public ref fltx4 F4MinDist {
    get => ref _Handle.AsRef<fltx4>(_F4MinDistOffset);
  }
  private static readonly nint _F4Weight0Offset = Schema.GetOffset(0x596F78461FFC3579);

  public ref fltx4 F4Weight0 {
    get => ref _Handle.AsRef<fltx4>(_F4Weight0Offset);
  }
  private static readonly nint _F4RelaxationFactorOffset = Schema.GetOffset(0x596F7846DF311F87);

  public ref fltx4 F4RelaxationFactor {
    get => ref _Handle.AsRef<fltx4>(_F4RelaxationFactorOffset);
  }


}