// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class FilterHealthImpl : CBaseFilterImpl, FilterHealth {

  public FilterHealthImpl(nint handle) : base(handle) {
  }

  private static readonly nint _AdrenalineActiveOffset = Schema.GetOffset(0x4DD06C81671CFB30);

  public ref bool AdrenalineActive {
    get => ref _Handle.AsRef<bool>(_AdrenalineActiveOffset);
  }
  private static readonly nint _HealthMinOffset = Schema.GetOffset(0x4DD06C8117D5C166);

  public ref int HealthMin {
    get => ref _Handle.AsRef<int>(_HealthMinOffset);
  }
  private static readonly nint _HealthMaxOffset = Schema.GetOffset(0x4DD06C8129E96574);

  public ref int HealthMax {
    get => ref _Handle.AsRef<int>(_HealthMaxOffset);
  }


}