// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class FootStepTriggerImpl : SchemaClass, FootStepTrigger {

  public FootStepTriggerImpl(nint handle) : base(handle) {
  }

  private static readonly nint _TagsOffset = Schema.GetOffset(0xD1D326CDB46C8540);

  public ref CUtlVector<int> Tags {
    get => ref _Handle.AsRef<CUtlVector<int>>(_TagsOffset);
  }
  private static readonly nint _FootIndexOffset = Schema.GetOffset(0xD1D326CD67D56BAB);

  public ref int FootIndex {
    get => ref _Handle.AsRef<int>(_FootIndexOffset);
  }
  private static readonly nint _TriggerPhaseOffset = Schema.GetOffset(0xD1D326CD486B84EE);

  public ref StepPhase TriggerPhase {
    get => ref _Handle.AsRef<StepPhase>(_TriggerPhaseOffset);
  }


}