// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class MoodAnimation_tImpl : SchemaClass, MoodAnimation_t {

  public MoodAnimation_tImpl(nint handle) : base(handle) {
  }

  private static readonly nint _NameOffset = Schema.GetOffset(0x8982458763D22D49);

  public SchemaUntypedField Name {
    get => new SchemaUntypedField(_Handle + _NameOffset);
  }
  private static readonly nint _WeightOffset = Schema.GetOffset(0x898245877B81E7AB);

  public ref float Weight {
    get => ref _Handle.AsRef<float>(_WeightOffset);
  }


}