// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class NavGravity_tImpl : SchemaClass, NavGravity_t {

  public NavGravity_tImpl(nint handle) : base(handle) {
  }

  private static readonly nint _GravityOffset = Schema.GetOffset(0xAF45EC63A5AE4779);

  public ref Vector Gravity {
    get => ref _Handle.AsRef<Vector>(_GravityOffset);
  }
  private static readonly nint _DefaultOffset = Schema.GetOffset(0xAF45EC6385F067BE);

  public ref bool Default {
    get => ref _Handle.AsRef<bool>(_DefaultOffset);
  }


}