// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class NodeData_tImpl : SchemaClass, NodeData_t {

  public NodeData_tImpl(nint handle) : base(handle) {
  }

  private static readonly nint _ParentOffset = Schema.GetOffset(0xB09FAAA60AABB9D1);

  public ref int Parent {
    get => ref _Handle.AsRef<int>(_ParentOffset);
  }
  private static readonly nint _OriginOffset = Schema.GetOffset(0xB09FAAA6F26E589B);

  public ref Vector Origin {
    get => ref _Handle.AsRef<Vector>(_OriginOffset);
  }
  private static readonly nint _MinBoundsOffset = Schema.GetOffset(0xB09FAAA6114799FE);

  public ref Vector MinBounds {
    get => ref _Handle.AsRef<Vector>(_MinBoundsOffset);
  }
  private static readonly nint _MaxBoundsOffset = Schema.GetOffset(0xB09FAAA6C0B4CE60);

  public ref Vector MaxBounds {
    get => ref _Handle.AsRef<Vector>(_MaxBoundsOffset);
  }
  private static readonly nint _MinimumDistanceOffset = Schema.GetOffset(0xB09FAAA6D8B1200E);

  public ref float MinimumDistance {
    get => ref _Handle.AsRef<float>(_MinimumDistanceOffset);
  }
  private static readonly nint _ChildNodeIndicesOffset = Schema.GetOffset(0xB09FAAA63648C692);

  public ref CUtlVector<int> ChildNodeIndices {
    get => ref _Handle.AsRef<CUtlVector<int>>(_ChildNodeIndicesOffset);
  }
  private static readonly nint _WorldNodePrefixOffset = Schema.GetOffset(0xB09FAAA662126457);

  public string WorldNodePrefix {
    get {
      var ptr = _Handle.Read<nint>(_WorldNodePrefixOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _WorldNodePrefixOffset, value);
  } 


}