// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class ParticleControlPointDriver_tImpl : SchemaClass, ParticleControlPointDriver_t {

  public ParticleControlPointDriver_tImpl(nint handle) : base(handle) {
  }

  private static readonly nint _ControlPointOffset = Schema.GetOffset(0xB7C66843E9EC8FF5);

  public ref int ControlPoint {
    get => ref _Handle.AsRef<int>(_ControlPointOffset);
  }
  private static readonly nint _AttachTypeOffset = Schema.GetOffset(0xB7C66843432E8381);

  public ref ParticleAttachment_t AttachType {
    get => ref _Handle.AsRef<ParticleAttachment_t>(_AttachTypeOffset);
  }
  private static readonly nint _AttachmentNameOffset = Schema.GetOffset(0xB7C66843295DA9CB);

  public string AttachmentName {
    get {
      var ptr = _Handle.Read<nint>(_AttachmentNameOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _AttachmentNameOffset, value);
  } 
  private static readonly nint _OffsetOffset = Schema.GetOffset(0xB7C66843BD25CC2A);

  public ref Vector Offset {
    get => ref _Handle.AsRef<Vector>(_OffsetOffset);
  }
  private static readonly nint _Offset1Offset = Schema.GetOffset(0xB7C6684346F6B3C0);

  public ref QAngle Offset1 {
    get => ref _Handle.AsRef<QAngle>(_Offset1Offset);
  }
  private static readonly nint _EntityNameOffset = Schema.GetOffset(0xB7C6684380D1D3E1);

  public string EntityName {
    get {
      var ptr = _Handle.Read<nint>(_EntityNameOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _EntityNameOffset, value);
  } 


}