// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class ParticleNamedValueConfiguration_tImpl : SchemaClass, ParticleNamedValueConfiguration_t {

  public ParticleNamedValueConfiguration_tImpl(nint handle) : base(handle) {
  }

  private static readonly nint _ConfigNameOffset = Schema.GetOffset(0x4C42AD0EA7B74064);

  public string ConfigName {
    get {
      var ptr = _Handle.Read<nint>(_ConfigNameOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _ConfigNameOffset, value);
  } 
  private static readonly nint _ConfigValueOffset = Schema.GetOffset(0x4C42AD0ECF981D3C);

  public SchemaUntypedField ConfigValue {
    get => new SchemaUntypedField(_Handle + _ConfigValueOffset);
  }
  private static readonly nint _BoundValuePathOffset = Schema.GetOffset(0x4C42AD0ED4977C9F);

  public string BoundValuePath {
    get {
      var ptr = _Handle.Read<nint>(_BoundValuePathOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _BoundValuePathOffset, value);
  } 
  private static readonly nint _AttachTypeOffset = Schema.GetOffset(0x4C42AD0E432E8381);

  public ref ParticleAttachment_t AttachType {
    get => ref _Handle.AsRef<ParticleAttachment_t>(_AttachTypeOffset);
  }
  private static readonly nint _StrEntityScopeOffset = Schema.GetOffset(0x4C42AD0ECCAF0621);

  public string StrEntityScope {
    get {
      var ptr = _Handle.Read<nint>(_StrEntityScopeOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _StrEntityScopeOffset, value);
  } 
  private static readonly nint _StrAttachmentNameOffset = Schema.GetOffset(0x4C42AD0EEB143B4E);

  public string StrAttachmentName {
    get {
      var ptr = _Handle.Read<nint>(_StrAttachmentNameOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _StrAttachmentNameOffset, value);
  } 


}