// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class ParticleChildrenInfo_tImpl : SchemaClass, ParticleChildrenInfo_t {

  public ParticleChildrenInfo_tImpl(nint handle) : base(handle) {
  }

  private static readonly nint _ChildRefOffset = Schema.GetOffset(0x1EF548F3D87838A);

  public ref CStrongHandle<InfoForResourceTypeIParticleSystemDefinition> ChildRef {
    get => ref _Handle.AsRef<CStrongHandle<InfoForResourceTypeIParticleSystemDefinition>>(_ChildRefOffset);
  }
  private static readonly nint _DelayOffset = Schema.GetOffset(0x1EF548F7D68FD6E);

  public ref float Delay {
    get => ref _Handle.AsRef<float>(_DelayOffset);
  }
  private static readonly nint _EndCapOffset = Schema.GetOffset(0x1EF548FC47CB04A);

  public ref bool EndCap {
    get => ref _Handle.AsRef<bool>(_EndCapOffset);
  }
  private static readonly nint _DisableChildOffset = Schema.GetOffset(0x1EF548F81AECD9B);

  public ref bool DisableChild {
    get => ref _Handle.AsRef<bool>(_DisableChildOffset);
  }
  private static readonly nint _DetailLevelOffset = Schema.GetOffset(0x1EF548F11D9E786);

  public ref ParticleDetailLevel_t DetailLevel {
    get => ref _Handle.AsRef<ParticleDetailLevel_t>(_DetailLevelOffset);
  }


}