// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class PermModelInfo_tImpl : SchemaClass, PermModelInfo_t {

  public PermModelInfo_tImpl(nint handle) : base(handle) {
  }

  private static readonly nint _FlagsOffset = Schema.GetOffset(0x1B48585FCE6E9C28);

  public ref uint Flags {
    get => ref _Handle.AsRef<uint>(_FlagsOffset);
  }
  private static readonly nint _HullMinOffset = Schema.GetOffset(0x1B48585FAC1193D6);

  public ref Vector HullMin {
    get => ref _Handle.AsRef<Vector>(_HullMinOffset);
  }
  private static readonly nint _HullMaxOffset = Schema.GetOffset(0x1B48585F9E269884);

  public ref Vector HullMax {
    get => ref _Handle.AsRef<Vector>(_HullMaxOffset);
  }
  private static readonly nint _ViewMinOffset = Schema.GetOffset(0x1B48585F22A936E8);

  public ref Vector ViewMin {
    get => ref _Handle.AsRef<Vector>(_ViewMinOffset);
  }
  private static readonly nint _ViewMaxOffset = Schema.GetOffset(0x1B48585F18BCAEE2);

  public ref Vector ViewMax {
    get => ref _Handle.AsRef<Vector>(_ViewMaxOffset);
  }
  private static readonly nint _MassOffset = Schema.GetOffset(0x1B48585FCD83D263);

  public ref float Mass {
    get => ref _Handle.AsRef<float>(_MassOffset);
  }
  private static readonly nint _EyePositionOffset = Schema.GetOffset(0x1B48585FA0F51EB1);

  public ref Vector EyePosition {
    get => ref _Handle.AsRef<Vector>(_EyePositionOffset);
  }
  private static readonly nint _MaxEyeDeflectionOffset = Schema.GetOffset(0x1B48585F1C6CE157);

  public ref float MaxEyeDeflection {
    get => ref _Handle.AsRef<float>(_MaxEyeDeflectionOffset);
  }
  private static readonly nint _SurfacePropertyOffset = Schema.GetOffset(0x1B48585F1A25534C);

  public string SurfaceProperty {
    get {
      var ptr = _Handle.Read<nint>(_SurfacePropertyOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _SurfacePropertyOffset, value);
  } 
  private static readonly nint _KeyValueTextOffset = Schema.GetOffset(0x1B48585F2156929E);

  public string KeyValueText {
    get {
      var ptr = _Handle.Read<nint>(_KeyValueTextOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _KeyValueTextOffset, value);
  } 


}