// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class PermModelExtPart_tImpl : SchemaClass, PermModelExtPart_t {

  public PermModelExtPart_tImpl(nint handle) : base(handle) {
  }

  private static readonly nint _TransformOffset = Schema.GetOffset(0xCA30851D6EC5209B);

  public ref CTransform Transform {
    get => ref _Handle.AsRef<CTransform>(_TransformOffset);
  }
  private static readonly nint _NameOffset = Schema.GetOffset(0xCA30851DCAE8A266);

  public string Name {
    get {
      var ptr = _Handle.Read<nint>(_NameOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _NameOffset, value);
  } 
  private static readonly nint _ParentOffset = Schema.GetOffset(0xCA30851D0AABB9D1);

  public ref int Parent {
    get => ref _Handle.AsRef<int>(_ParentOffset);
  }
  private static readonly nint _RefModelOffset = Schema.GetOffset(0xCA30851D63E6E3DF);

  public ref CStrongHandle<InfoForResourceTypeCModel> RefModel {
    get => ref _Handle.AsRef<CStrongHandle<InfoForResourceTypeCModel>>(_RefModelOffset);
  }


}