// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class PointCameraSettings_tImpl : SchemaClass, PointCameraSettings_t {

  public PointCameraSettings_tImpl(nint handle) : base(handle) {
  }

  private static readonly nint _NearBlurryDistanceOffset = Schema.GetOffset(0x4BE8175CEB0CA47E);

  public ref float NearBlurryDistance {
    get => ref _Handle.AsRef<float>(_NearBlurryDistanceOffset);
  }
  private static readonly nint _NearCrispDistanceOffset = Schema.GetOffset(0x4BE8175CF0C9A8C7);

  public ref float NearCrispDistance {
    get => ref _Handle.AsRef<float>(_NearCrispDistanceOffset);
  }
  private static readonly nint _FarCrispDistanceOffset = Schema.GetOffset(0x4BE8175CE95AEE28);

  public ref float FarCrispDistance {
    get => ref _Handle.AsRef<float>(_FarCrispDistanceOffset);
  }
  private static readonly nint _FarBlurryDistanceOffset = Schema.GetOffset(0x4BE8175CF8892257);

  public ref float FarBlurryDistance {
    get => ref _Handle.AsRef<float>(_FarBlurryDistanceOffset);
  }


}