// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class PostProcessingFogScatteringParameters_tImpl : SchemaClass, PostProcessingFogScatteringParameters_t {

  public PostProcessingFogScatteringParameters_tImpl(nint handle) : base(handle) {
  }

  private static readonly nint _RadiusOffset = Schema.GetOffset(0xAE3B2EF52E1F6E07);

  public ref float Radius {
    get => ref _Handle.AsRef<float>(_RadiusOffset);
  }
  private static readonly nint _ScaleOffset = Schema.GetOffset(0xAE3B2EF555E6EFAD);

  public ref float Scale {
    get => ref _Handle.AsRef<float>(_ScaleOffset);
  }
  private static readonly nint _CubemapScaleOffset = Schema.GetOffset(0xAE3B2EF593A389D0);

  public ref float CubemapScale {
    get => ref _Handle.AsRef<float>(_CubemapScaleOffset);
  }
  private static readonly nint _VolumetricScaleOffset = Schema.GetOffset(0xAE3B2EF515A15A21);

  public ref float VolumetricScale {
    get => ref _Handle.AsRef<float>(_VolumetricScaleOffset);
  }
  private static readonly nint _GradientScaleOffset = Schema.GetOffset(0xAE3B2EF58473F465);

  public ref float GradientScale {
    get => ref _Handle.AsRef<float>(_GradientScaleOffset);
  }


}