// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class RotatorQueueEntry_tImpl : SchemaClass, RotatorQueueEntry_t {

  public RotatorQueueEntry_tImpl(nint handle) : base(handle) {
  }

  private static readonly nint _TargetOffset = Schema.GetOffset(0x2A6B84384FFCC265);

  public ref Quaternion Target {
    get => ref _Handle.AsRef<Quaternion>(_TargetOffset);
  }
  private static readonly nint _SpaceOffset = Schema.GetOffset(0x2A6B8438EC1BD596);

  public ref RotatorTargetSpace_t Space {
    get => ref _Handle.AsRef<RotatorTargetSpace_t>(_SpaceOffset);
  }


}