// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class SkeletonAnimCapture_t__Frame_tImpl : SchemaClass, SkeletonAnimCapture_t__Frame_t {

  public SkeletonAnimCapture_t__Frame_tImpl(nint handle) : base(handle) {
  }

  private static readonly nint _TimeOffset = Schema.GetOffset(0x413CC2EEC957229E);

  public ref float Time {
    get => ref _Handle.AsRef<float>(_TimeOffset);
  }
  private static readonly nint _StampOffset = Schema.GetOffset(0x413CC2EE11943004);

  public SkeletonAnimCapture_t__FrameStamp_t Stamp {
    get => new SkeletonAnimCapture_t__FrameStamp_tImpl(_Handle + _StampOffset);
  }
  private static readonly nint _TransformOffset = Schema.GetOffset(0x413CC2EE6EC5209B);

  public ref CTransform Transform {
    get => ref _Handle.AsRef<CTransform>(_TransformOffset);
  }
  private static readonly nint _TeleportOffset = Schema.GetOffset(0x413CC2EEE663C11E);

  public ref bool Teleport {
    get => ref _Handle.AsRef<bool>(_TeleportOffset);
  }
  private static readonly nint _CompositeBonesOffset = Schema.GetOffset(0x413CC2EE5F49062B);

  public ref CUtlVector<CTransform> CompositeBones {
    get => ref _Handle.AsRef<CUtlVector<CTransform>>(_CompositeBonesOffset);
  }
  private static readonly nint _SimStateBonesOffset = Schema.GetOffset(0x413CC2EE5DAE9398);

  public ref CUtlVector<CTransform> SimStateBones {
    get => ref _Handle.AsRef<CUtlVector<CTransform>>(_SimStateBonesOffset);
  }
  private static readonly nint _FeModelAnimsOffset = Schema.GetOffset(0x413CC2EE62EC797D);

  public ref CUtlVector<CTransform> FeModelAnims {
    get => ref _Handle.AsRef<CUtlVector<CTransform>>(_FeModelAnimsOffset);
  }
  private static readonly nint _FeModelPosOffset = Schema.GetOffset(0x413CC2EECA74E7F5);

  public ref CUtlVector<Vector> FeModelPos {
    get => ref _Handle.AsRef<CUtlVector<Vector>>(_FeModelPosOffset);
  }
  private static readonly nint _FlexControllerWeightsOffset = Schema.GetOffset(0x413CC2EECA3D8033);

  public ref CUtlVector<float> FlexControllerWeights {
    get => ref _Handle.AsRef<CUtlVector<float>>(_FlexControllerWeightsOffset);
  }


}