// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class TextureControls_tImpl : SchemaClass, TextureControls_t {

  public TextureControls_tImpl(nint handle) : base(handle) {
  }

  private static readonly nint _FinalTextureScaleUOffset = Schema.GetOffset(0x6019C255986FEDD1);

  public CParticleCollectionRendererFloatInput FinalTextureScaleU {
    get => new CParticleCollectionRendererFloatInputImpl(_Handle + _FinalTextureScaleUOffset);
  }
  private static readonly nint _FinalTextureScaleVOffset = Schema.GetOffset(0x6019C255956FE918);

  public CParticleCollectionRendererFloatInput FinalTextureScaleV {
    get => new CParticleCollectionRendererFloatInputImpl(_Handle + _FinalTextureScaleVOffset);
  }
  private static readonly nint _FinalTextureOffsetUOffset = Schema.GetOffset(0x6019C25524B7447E);

  public CParticleCollectionRendererFloatInput FinalTextureOffsetU {
    get => new CParticleCollectionRendererFloatInputImpl(_Handle + _FinalTextureOffsetUOffset);
  }
  private static readonly nint _FinalTextureOffsetVOffset = Schema.GetOffset(0x6019C25523B742EB);

  public CParticleCollectionRendererFloatInput FinalTextureOffsetV {
    get => new CParticleCollectionRendererFloatInputImpl(_Handle + _FinalTextureOffsetVOffset);
  }
  private static readonly nint _FinalTextureUVRotationOffset = Schema.GetOffset(0x6019C2550D61C771);

  public CParticleCollectionRendererFloatInput FinalTextureUVRotation {
    get => new CParticleCollectionRendererFloatInputImpl(_Handle + _FinalTextureUVRotationOffset);
  }
  private static readonly nint _ZoomScaleOffset = Schema.GetOffset(0x6019C25565643B72);

  public CParticleCollectionRendererFloatInput ZoomScale {
    get => new CParticleCollectionRendererFloatInputImpl(_Handle + _ZoomScaleOffset);
  }
  private static readonly nint _DistortionOffset = Schema.GetOffset(0x6019C25570283608);

  public CParticleCollectionRendererFloatInput Distortion {
    get => new CParticleCollectionRendererFloatInputImpl(_Handle + _DistortionOffset);
  }
  private static readonly nint _RandomizeOffsetsOffset = Schema.GetOffset(0x6019C25541B7E31C);

  public ref bool RandomizeOffsets {
    get => ref _Handle.AsRef<bool>(_RandomizeOffsetsOffset);
  }
  private static readonly nint _ClampUVsOffset = Schema.GetOffset(0x6019C255993F389C);

  public ref bool ClampUVs {
    get => ref _Handle.AsRef<bool>(_ClampUVsOffset);
  }
  private static readonly nint _PerParticleBlendOffset = Schema.GetOffset(0x6019C25569A29D11);

  public ref SpriteCardPerParticleScale_t PerParticleBlend {
    get => ref _Handle.AsRef<SpriteCardPerParticleScale_t>(_PerParticleBlendOffset);
  }
  private static readonly nint _PerParticleScaleOffset = Schema.GetOffset(0x6019C255E1BE0540);

  public ref SpriteCardPerParticleScale_t PerParticleScale {
    get => ref _Handle.AsRef<SpriteCardPerParticleScale_t>(_PerParticleScaleOffset);
  }
  private static readonly nint _PerParticleOffsetUOffset = Schema.GetOffset(0x6019C2559749CC58);

  public ref SpriteCardPerParticleScale_t PerParticleOffsetU {
    get => ref _Handle.AsRef<SpriteCardPerParticleScale_t>(_PerParticleOffsetUOffset);
  }
  private static readonly nint _PerParticleOffsetVOffset = Schema.GetOffset(0x6019C2559A49D111);

  public ref SpriteCardPerParticleScale_t PerParticleOffsetV {
    get => ref _Handle.AsRef<SpriteCardPerParticleScale_t>(_PerParticleOffsetVOffset);
  }
  private static readonly nint _PerParticleRotationOffset = Schema.GetOffset(0x6019C2557AD51358);

  public ref SpriteCardPerParticleScale_t PerParticleRotation {
    get => ref _Handle.AsRef<SpriteCardPerParticleScale_t>(_PerParticleRotationOffset);
  }
  private static readonly nint _PerParticleZoomOffset = Schema.GetOffset(0x6019C255F0492151);

  public ref SpriteCardPerParticleScale_t PerParticleZoom {
    get => ref _Handle.AsRef<SpriteCardPerParticleScale_t>(_PerParticleZoomOffset);
  }
  private static readonly nint _PerParticleDistortionOffset = Schema.GetOffset(0x6019C2553A9977DD);

  public ref SpriteCardPerParticleScale_t PerParticleDistortion {
    get => ref _Handle.AsRef<SpriteCardPerParticleScale_t>(_PerParticleDistortionOffset);
  }


}