// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class VMixPitchShiftDesc_tImpl : SchemaClass, VMixPitchShiftDesc_t {

  public VMixPitchShiftDesc_tImpl(nint handle) : base(handle) {
  }

  private static readonly nint _GrainSampleCountOffset = Schema.GetOffset(0xE7EEA08D6AA1D059);

  public ref int GrainSampleCount {
    get => ref _Handle.AsRef<int>(_GrainSampleCountOffset);
  }
  private static readonly nint _PitchShiftOffset = Schema.GetOffset(0xE7EEA08DD8E35569);

  public ref float PitchShift {
    get => ref _Handle.AsRef<float>(_PitchShiftOffset);
  }
  private static readonly nint _QualityOffset = Schema.GetOffset(0xE7EEA08D60857B42);

  public ref int Quality {
    get => ref _Handle.AsRef<int>(_QualityOffset);
  }
  private static readonly nint _ProcTypeOffset = Schema.GetOffset(0xE7EEA08DB256235D);

  public ref int ProcType {
    get => ref _Handle.AsRef<int>(_ProcTypeOffset);
  }


}