// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class VMixOscDesc_tImpl : SchemaClass, VMixOscDesc_t {

  public VMixOscDesc_tImpl(nint handle) : base(handle) {
  }

  private static readonly nint _OscTypeOffset = Schema.GetOffset(0x414F0016106B4054);

  public ref VMixLFOShape_t OscType {
    get => ref _Handle.AsRef<VMixLFOShape_t>(_OscTypeOffset);
  }
  private static readonly nint _FreqOffset = Schema.GetOffset(0x414F00164E0B0897);

  public ref float Freq {
    get => ref _Handle.AsRef<float>(_FreqOffset);
  }
  private static readonly nint _PhaseOffset = Schema.GetOffset(0x414F00163C22A9CA);

  public ref float Phase {
    get => ref _Handle.AsRef<float>(_PhaseOffset);
  }


}