// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class VoxelVisBlockOffset_tImpl : SchemaClass, VoxelVisBlockOffset_t {

  public VoxelVisBlockOffset_tImpl(nint handle) : base(handle) {
  }

  private static readonly nint _OffsetOffset = Schema.GetOffset(0x17D2B49827734C8E);

  public ref uint Offset {
    get => ref _Handle.AsRef<uint>(_OffsetOffset);
  }
  private static readonly nint _ElementCountOffset = Schema.GetOffset(0x17D2B49851A2EF12);

  public ref uint ElementCount {
    get => ref _Handle.AsRef<uint>(_ElementCountOffset);
  }


}