// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class VPhysXCollisionAttributes_tImpl : SchemaClass, VPhysXCollisionAttributes_t {

  public VPhysXCollisionAttributes_tImpl(nint handle) : base(handle) {
  }

  private static readonly nint _CollisionGroupOffset = Schema.GetOffset(0xBD3263AF91BF7016);

  public ref uint CollisionGroup {
    get => ref _Handle.AsRef<uint>(_CollisionGroupOffset);
  }
  private static readonly nint _InteractAsOffset = Schema.GetOffset(0xBD3263AF4FBB627B);

  public ref CUtlVector<uint> InteractAs {
    get => ref _Handle.AsRef<CUtlVector<uint>>(_InteractAsOffset);
  }
  private static readonly nint _InteractWithOffset = Schema.GetOffset(0xBD3263AFAD426A97);

  public ref CUtlVector<uint> InteractWith {
    get => ref _Handle.AsRef<CUtlVector<uint>>(_InteractWithOffset);
  }
  private static readonly nint _InteractExcludeOffset = Schema.GetOffset(0xBD3263AFC5ECE843);

  public ref CUtlVector<uint> InteractExclude {
    get => ref _Handle.AsRef<CUtlVector<uint>>(_InteractExcludeOffset);
  }
  private static readonly nint _CollisionGroupStringOffset = Schema.GetOffset(0xBD3263AFCF0517E7);

  public string CollisionGroupString {
    get {
      var ptr = _Handle.Read<nint>(_CollisionGroupStringOffset);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _CollisionGroupStringOffset, value);
  } 
  private static readonly nint _InteractAsStringsOffset = Schema.GetOffset(0xBD3263AF7A4D07B7);

  public ref CUtlVector<CUtlString> InteractAsStrings {
    get => ref _Handle.AsRef<CUtlVector<CUtlString>>(_InteractAsStringsOffset);
  }
  private static readonly nint _InteractWithStringsOffset = Schema.GetOffset(0xBD3263AF691AB483);

  public ref CUtlVector<CUtlString> InteractWithStrings {
    get => ref _Handle.AsRef<CUtlVector<CUtlString>>(_InteractWithStringsOffset);
  }
  private static readonly nint _InteractExcludeStringsOffset = Schema.GetOffset(0xBD3263AF97DC23CF);

  public ref CUtlVector<CUtlString> InteractExcludeStrings {
    get => ref _Handle.AsRef<CUtlVector<CUtlString>>(_InteractExcludeStringsOffset);
  }


}