// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class VPhysXBodyPart_tImpl : SchemaClass, VPhysXBodyPart_t {

  public VPhysXBodyPart_tImpl(nint handle) : base(handle) {
  }

  private static readonly nint _FlagsOffset = Schema.GetOffset(0x53DE59CDCE6E9C28);

  public ref uint Flags {
    get => ref _Handle.AsRef<uint>(_FlagsOffset);
  }
  private static readonly nint _MassOffset = Schema.GetOffset(0x53DE59CDCD83D263);

  public ref float Mass {
    get => ref _Handle.AsRef<float>(_MassOffset);
  }
  private static readonly nint _RnShapeOffset = Schema.GetOffset(0x53DE59CDD69E7012);

  public VPhysics2ShapeDef_t RnShape {
    get => new VPhysics2ShapeDef_tImpl(_Handle + _RnShapeOffset);
  }
  private static readonly nint _CollisionAttributeIndexOffset = Schema.GetOffset(0x53DE59CDC7B64DF7);

  public ref ushort CollisionAttributeIndex {
    get => ref _Handle.AsRef<ushort>(_CollisionAttributeIndexOffset);
  }
  private static readonly nint _ReservedOffset = Schema.GetOffset(0x53DE59CD94BD4B01);

  public ref ushort Reserved {
    get => ref _Handle.AsRef<ushort>(_ReservedOffset);
  }
  private static readonly nint _InertiaScaleOffset = Schema.GetOffset(0x53DE59CD4E6CAB2F);

  public ref float InertiaScale {
    get => ref _Handle.AsRef<float>(_InertiaScaleOffset);
  }
  private static readonly nint _LinearDampingOffset = Schema.GetOffset(0x53DE59CD4E6B7F64);

  public ref float LinearDamping {
    get => ref _Handle.AsRef<float>(_LinearDampingOffset);
  }
  private static readonly nint _AngularDampingOffset = Schema.GetOffset(0x53DE59CD0E32E897);

  public ref float AngularDamping {
    get => ref _Handle.AsRef<float>(_AngularDampingOffset);
  }
  private static readonly nint _LinearDragOffset = Schema.GetOffset(0x53DE59CDB3D686BC);

  public ref float LinearDrag {
    get => ref _Handle.AsRef<float>(_LinearDragOffset);
  }
  private static readonly nint _AngularDragOffset = Schema.GetOffset(0x53DE59CDDCE9A7D1);

  public ref float AngularDrag {
    get => ref _Handle.AsRef<float>(_AngularDragOffset);
  }
  private static readonly nint _OverrideMassCenterOffset = Schema.GetOffset(0x53DE59CD19E47DF8);

  public ref bool OverrideMassCenter {
    get => ref _Handle.AsRef<bool>(_OverrideMassCenterOffset);
  }
  private static readonly nint _MassCenterOverrideOffset = Schema.GetOffset(0x53DE59CD7249FAE4);

  public ref Vector MassCenterOverride {
    get => ref _Handle.AsRef<Vector>(_MassCenterOverrideOffset);
  }


}