// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class WaterWheelDrag_tImpl : SchemaClass, WaterWheelDrag_t {

  public WaterWheelDrag_tImpl(nint handle) : base(handle) {
  }

  private static readonly nint _FractionOfWheelSubmergedOffset = Schema.GetOffset(0x51DDFA66F2D4C09B);

  public ref float FractionOfWheelSubmerged {
    get => ref _Handle.AsRef<float>(_FractionOfWheelSubmergedOffset);
  }
  private static readonly nint _WheelDragOffset = Schema.GetOffset(0x51DDFA66B996F340);

  public ref float WheelDrag {
    get => ref _Handle.AsRef<float>(_WheelDragOffset);
  }


}