// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class WorldNodeOnDiskBufferData_tImpl : SchemaClass, WorldNodeOnDiskBufferData_t {

  public WorldNodeOnDiskBufferData_tImpl(nint handle) : base(handle) {
  }

  private static readonly nint _ElementCountOffset = Schema.GetOffset(0xC4F557DA51A2EF12);

  public ref int ElementCount {
    get => ref _Handle.AsRef<int>(_ElementCountOffset);
  }
  private static readonly nint _ElementSizeInBytesOffset = Schema.GetOffset(0xC4F557DAF602975C);

  public ref int ElementSizeInBytes {
    get => ref _Handle.AsRef<int>(_ElementSizeInBytesOffset);
  }
  private static readonly nint _InputLayoutFieldsOffset = Schema.GetOffset(0xC4F557DAFDECA2D8);

  public ref CUtlVector<RenderInputLayoutField_t> InputLayoutFields {
    get => ref _Handle.AsRef<CUtlVector<RenderInputLayoutField_t>>(_InputLayoutFieldsOffset);
  }
  private static readonly nint _DataOffset = Schema.GetOffset(0xC4F557DA27938BB7);

  public ref CUtlVector<byte> Data {
    get => ref _Handle.AsRef<CUtlVector<byte>>(_DataOffset);
  }


}