// <auto-generated />
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal static class ClassConvertor
{
    public static CEntityInstance ConvertEntityByDesignerName(nint address, string designerName)
    {
        return designerName switch
        {
$SWITCHES$
            _ => new CEntityInstanceImpl(address),
        };
    }
}